### ISSUE TITLE
error on autocomplete using neovim on simple Symfony Controller

### ISSUE THREAD

**Issue by tomsvogel** [phpactor/phpactor#104]
tried to add a HttpFoundation/JsonResponse for testing phpactor.

```
<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class AdminController extends Controller
{
    /**
     * @Route("/", name="admin_route")
     */
    public function adminAction(Request $request)
    {
      $res = new Json 
      return $this->render('AppBundle:Default:admin.html.twig');
    }



}

```

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Phpactor\WorseReflection\Reflection\Inference\NodeValueResolver
::resolveQualifiedName() must be an instance of Microsoft\PhpParser\Node, instance of Microsoft\PhpParser\MissingToken given, called in /Users/toms/.config/nvim/plugged/phpactor/
vendor/phpactor/worse-reflection/lib/Reflection/Inference/NodeValueResolver.php on line 108 in /Users/toms/.config/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Refl
ection/Inference/NodeValueResolver.php:184
Stack trace:
#0 /Users/toms/.config/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Reflection/Inference/NodeValueResolver.php(108): Phpactor\WorseReflection\Reflection\Inference\N
odeValueResolver->resolveQualifiedName(Object(Microsoft\PhpParser\MissingToken))
#1 /Users/toms/.config/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Reflection/Inference/NodeValueResolver.php(73): Phpactor\WorseReflection\Reflection\Inference\No
deValueResolver in /Users/toms/.config/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Reflection/Inference/NodeValueResolver.php on line 184

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Phpactor\WorseReflection\Reflection\Inference\NodeValueResolver::res
olveQualifiedName() must be an instance of Microsoft\PhpParser\Node, instance of Microsoft\PhpParser\MissingToken given, called in /Users/toms/.config/nvim/plugged/phpactor/vendo
r/phpactor/worse-reflection/lib/Reflection/Inference/NodeValueResolver.php on line 108 in /Users/toms/.config/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Reflectio
n/Inference/NodeValueResolver.php on line 184

Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Phpactor\WorseReflection\Reflection\Inference\NodeValueResolver::resolveQualifiedName() mu
st be an instance of Microsoft\PhpParser\Node, instance of Microsoft\PhpParser\MissingToken given, called in /Users/toms/.config/nvim/plugged/phpactor/vendor/phpactor/worse-refle
ction/lib/Reflection/Inference/NodeValueResolver.php on line 108 in /Users/toms/.config/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Reflection/Inference/NodeValueR
esolver.php on line 184

Call Stack:
    0.0749    6606048   1. Symfony\Component\Debug\ErrorHandler->handleException() /Users/toms/.config/nvim/plugged/phpactor/vendor/symfony/debug/ErrorHandler.php:0
```

**Comment by tomsvogel** [comment]
just realized it works if I add the use statement first.

**Comment by dantleech** [comment]
I can reproduce with that code if I try and auto-complete the class name (`Json...`). Auto-completing class names isn't supported yet (but [including use statements is](https://github.com/phpactor/phpactor/tree/master/plugin#example-configuration)).

Will fix this bug later today.

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/worse-reflection/commit/0f336b6f0f60ffdd28d85fd932c77e0542579d70

**Comment by tomsvogel** [comment]
thanks!
