### ISSUE TITLE
Twig version/namespace confusion with project code when running phpactor

### ISSUE THREAD

**Issue by ekes** [phpactor/phpactor#1043]
Running phpactor it's loading the project code `Twig\Environment` with the phpactor `Twig\Extension\CoreExtension`. The project code is Twig v1. It's getting phpactor's Twig v2 extensions and exploding.

```
> phpactor

Phpactor dev-master@72bb79a5682babdeaad3d4b5d7a73bd60148cabb
Usage:
  command [options] [arguments]

Options:
  -h, --help                     Display this help message
  -q, --quiet                    Do not output any message
  -V, --version                  Display this application version
      --ansi                     Force ANSI output
      --no-ansi                  Disable ANSI output
  -n, --no-interaction           Do not ask any interactive question
  -d, --working-dir=WORKING-DIR  Working directory
  -v|vv|vvv, --verbose           Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

PHP Fatal error:  Uncaught Error: Call to undefined method Twig\Extension\CoreExtension::getName() in $PROJECT/vendor/twig/twig/src/Environment.php:974
Stack trace:
#0 $PROJECT/vendor/twig/twig/src/Environment.php(148): Twig\Environment->addExtension()
#1 /home/user/.local/share/nvim/plugged/phpactor/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php(209): Twig\Environment->__construct()
#2 /home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Extension\CodeTransformExtra\CodeTransformExtraExtension->Phpactor\Extension\CodeTransformExtra\{closure}()
#3 /home/user/.local/share/nvim/plugged/phpactor/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php(293): Phpactor\Container\PhpactorContainer->get()
#4 /home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Extension\CodeTransformExtra\CodeTransformExtraExtensio in $PROJECT/vendor/twig/twig/src/Environment.php on line 974
Fatal error: Uncaught Error: Call to undefined method Twig\Extension\CoreExtension::getName() in $PROJECT/vendor/twig/twig/src/Environment.php:974
Stack trace:
#0 $PROJECT/vendor/twig/twig/src/Environment.php(148): Twig\Environment->addExtension()
#1 /home/user/.local/share/nvim/plugged/phpactor/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php(209): Twig\Environment->__construct()
#2 /home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Extension\CodeTransformExtra\CodeTransformExtraExtension->Phpactor\Extension\CodeTransformExtra\{closure}()
#3 /home/user/.local/share/nvim/plugged/phpactor/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php(293): Phpactor\Container\PhpactorContainer->get()
#4 /home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Extension\CodeTransformExtra\CodeTransformExtraExtensio in $PROJECT/vendor/twig/twig/src/Environment.php on line 974
```

**Comment by dantleech** [comment]
hmm, I'm also using Phpactor with a project that is on Twig 1.x and get no problems. 

Phpactor _should_ [deregister](https://github.com/phpactor/ncm2-phpactor) the autoloader after requiring it.

Is it possible that the autoloader (composer or otherwise) is eagerly loading things?

**Comment by ekes** [comment]
Think we can go with some quirk of the code base. It's a Drupal 8.8 site I've inherited which I'm using for the first with a newly installed system (so phpactor from git master72bb79a). I just tested it with a clean empty Drupal 8.8 and it doesn't have the issue.

But how to find how it's doing this? Any ideas, or routes to debug, gratefully accepted.

So far I've blasted the vendor directory, removed all the drupal composer project and other composer related requirements (that I recognised) from the composer.json file, and then added in the new Drupal core support for composer into it. Rebuilt. But same error.

So xdebug time. It's throwing the error when it restores the exception handler back in Symfony\Component\Console/Application::run Line 171

```
Call Stack:
    0.0002     352424   1. {main}() /home/user/.local/share/nvim/plugged/phpactor/bin/phpactor:0
    0.0504     835536   2. Phpactor\Application->run() /home/user/.local/share/nvim/plugged/phpactor/bin/phpactor:43
    0.0553     848208   3. Phpactor\Application->doRun() /home/user/.local/share/nvim/plugged/phpactor/vendor/symfony/console/Application.php:147
    0.0829    1487656   4. Phpactor\Application->doRun() /home/user/.local/share/nvim/plugged/phpactor/lib/Application.php:53
    0.0865    1575728   5. Phpactor\Application->doRunCommand() /home/user/.local/share/nvim/plugged/phpactor/vendor/symfony/console/Application.php:271
    0.0865    1575728   6. Symfony\Component\Console\Command\ListCommand->run() /home/user/.local/share/nvim/plugged/phpactor/vendor/symfony/console/Application.php:1001
    0.0867    1577504   7. Symfony\Component\Console\Command\ListCommand->execute() /home/user/.local/share/nvim/plugged/phpactor/vendor/symfony/console/Command/Command.php:255
    0.0894    1652512   8. Symfony\Component\Console\Helper\DescriptorHelper->describe() /home/user/.local/share/nvim/plugged/phpactor/vendor/symfony/console/Command/ListCommand.php:75
    0.0894    1652512   9. Symfony\Component\Console\Descriptor\TextDescriptor->describe() /home/user/.local/share/nvim/plugged/phpactor/vendor/symfony/console/Helper/DescriptorHelper.php:67
    0.0894    1652512  10. Symfony\Component\Console\Descriptor\TextDescriptor->describeApplication() /home/user/.local/share/nvim/plugged/phpactor/vendor/symfony/console/Descriptor/Descriptor.php:55
    0.0907    1653624  11. Symfony\Component\Console\Descriptor\ApplicationDescription->getCommands() /home/user/.local/share/nvim/plugged/phpactor/vendor/symfony/console/Descriptor/TextDescriptor.php:202
    0.0907    1653624  12. Symfony\Component\Console\Descriptor\ApplicationDescription->inspectApplication() /home/user/.local/share/nvim/plugged/phpactor/vendor/symfony/console/Descriptor/ApplicationDescription.php:68
    0.0907    1653624  13. Phpactor\Application->all() /home/user/.local/share/nvim/plugged/phpactor/vendor/symfony/console/Descriptor/ApplicationDescription.php:91
    0.1392    2601400  14. Phpactor\Application->has() /home/user/.local/share/nvim/plugged/phpactor/vendor/symfony/console/Application.php:743
    0.1392    2601400  15. Phpactor\Extension\Console\PhpactorCommandLoader->get() /home/user/.local/share/nvim/plugged/phpactor/vendor/symfony/console/Application.php:541
    0.1392    2601400  16. Phpactor\Extension\Console\PhpactorCommandLoader->get() /home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/console-extension/lib/PhpactorCommandLoader.php:11
    0.1392    2601400  17. Phpactor\Container\PhpactorContainer->get() /home/user/.local/share/nvim/plugged/phpactor/vendor/symfony/console/CommandLoader/ContainerCommandLoader.php:45
    0.1392    2601400  18. Phpactor\Extension\CodeTransformExtra\CodeTransformExtraExtension->Phpactor\Extension\CodeTransformExtra\{closure:/home/user/.local/share/nvim/plugged/phpactor/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php:133-137}() /home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php:79
    0.1395    2606056  19. Phpactor\Container\PhpactorContainer->get() /home/user/.local/share/nvim/plugged/phpactor/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php:135
    0.1395    2606056  20. Phpactor\Extension\CodeTransformExtra\CodeTransformExtraExtension->Phpactor\Extension\CodeTransformExtra\{closure:/home/user/.local/share/nvim/plugged/phpactor/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php:109-113}() /home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php:79
    0.1396    2606296  21. Phpactor\Container\PhpactorContainer->get() /home/user/.local/share/nvim/plugged/phpactor/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php:111
    0.1396    2606296  22. Phpactor\Extension\CodeTransform\CodeTransformExtension->Phpactor\Extension\CodeTransform\{closure:/home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/code-transform-extension/lib/CodeTransformExtension.php:49-51}() /home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php:79
    0.1397    2606424  23. Phpactor\Container\PhpactorContainer->get() /home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/code-transform-extension/lib/CodeTransformExtension.php:50
    0.1397    2606424  24. Phpactor\Extension\CodeTransform\CodeTransformExtension->Phpactor\Extension\CodeTransform\{closure:/home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/code-transform-extension/lib/CodeTransformExtension.php:53-60}() /home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php:79
    0.1397    2606424  25. Phpactor\Container\PhpactorContainer->get() /home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/code-transform-extension/lib/CodeTransformExtension.php:56
    0.1397    2606424  26. Phpactor\Extension\CodeTransformExtra\CodeTransformExtraExtension->Phpactor\Extension\CodeTransformExtra\{closure:/home/user/.local/share/nvim/plugged/phpactor/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php:156-161}() /home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php:79
    0.1401    2607504  27. Phpactor\Container\PhpactorContainer->get() /home/user/.local/share/nvim/plugged/phpactor/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php:159
    0.1401    2607504  28. Phpactor\Extension\CodeTransformExtra\CodeTransformExtraExtension->Phpactor\Extension\CodeTransformExtra\{closure:/home/user/.local/share/nvim/plugged/phpactor/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php:291-297}() /home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php:79
    0.1406    2608760  29. Phpactor\Container\PhpactorContainer->get() /home/user/.local/share/nvim/plugged/phpactor/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php:293
    0.1406    2608760  30. Phpactor\Extension\CodeTransformExtra\CodeTransformExtraExtension->Phpactor\Extension\CodeTransformExtra\{closure:/home/user/.local/share/nvim/plugged/phpactor/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php:207-215}() /home/user/.local/share/nvim/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php:79
    0.1423    2684000  31. Twig\Environment->__construct() /home/user/.local/share/nvim/plugged/phpactor/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php:209
    0.1451    2688024  32. Twig\Environment->addExtension() %project_directory%/vendor/twig/twig/src/Environment.php:148 
```
It's not in the autoloader at the beginning, when phpactor bootstraps itself, stepped through there. So I guess the first place to be looking is where ever the project code is loaded? All new to me this.

**Comment by ekes** [comment]
FOUND IT! And it's going to be a common problem - well for anyone doing Drupal dev.

`drush/drush`, the command line client for Drupal requires [https://github.com/drush-ops/drush/blob/c3abfe75894f8911c93d13d3724308a4e0872308/composer.json#L35] `chi-teck/drupal-code-generator` which includes a line that causes the Twig Environment class to be loaded in vendor/chi-teck/drupal-code-generator/src/bootstrap.php line 38 `list($twig_major_version) = sscanf(Environment::VERSION, '%d.%d.%d');` [https://github.com/Chi-teck/drupal-code-generator/blob/c59c31ee6d8eefe76a5d367feef902e259c90c7b/src/bootstrap.php#L37]. 

This doesn't seem to be in all versions of drupal-code-generator, but is in the one Drush depends on at the moment. Next task. See why that one.

**Comment by mamazu** [comment]
Looks like the issue has been fixed in the code generator package. Can we close this?

**Comment by dantleech** [comment]
:+1:
