### ISSUE TITLE
[WR] Call to getNamespacedName on null

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#113]
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getNamespacedName() on null in /home/daniel/.vim/bundle/phpactor/vendor/phpactor/wo
rse-reflection/lib/Reflection/ReflectionMethod.php:72
Stack trace:
#0 /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Reflection/ReflectionMethod.php(124): Phpactor\WorseReflection\Reflection\ReflectionMethod->class()
#1 /home/daniel/.vim/bundle/phpactor/lib/Application/Complete.php(158): Phpactor\WorseReflection\Reflection\ReflectionMethod->inferredReturnType()
#2 /home/daniel/.vim/bundle/phpactor/lib/Application/Complete.php(62): Phpactor\Application\Complete->getMethodInfo(Object(Phpactor\WorseReflection\Reflection\ReflectionMethod))
#3 /home/daniel/.vim/bundle/phpactor/lib/UserInterface/Console/Command/CompleteCommand.php(46): Phpactor\Application\Complete->complete('<?php\n\nnamespac...', 1119)
#4 /home/daniel/.vim/bundle/phpactor/vendor/symfony/console/Command/Command.php(260): Phpactor\UserInterface\Console\Co in /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/l
ib/Reflection/ReflectionMethod.php on line 72
Pr
```

in

```
<?php

namespace Fidry\AliceDataFixtures\Bridge\Propel2;

use PHPUnit\Framework\TestCase;
use Fidry\AliceDataFixtures\Bridge\Propel2\Persister\ModelPersister;
use Nelmio\Alice\Loader\SimpleFileLoader;
use Fidry\AliceDataFixtures\Loader\PersisterLoader;
use Fidry\AliceDataFixtures\Loader\SimpleLoader;
use Nelmio\Alice\Parser\Chainable\YamlParser;
use Symfony\Component\Yaml\Parser;
use Nelmio\Alice\Loader\NativeLoader;
use Fidry\AliceDataFixtures\Bridge\Propel2\PropelTestCase;

class PropelIntegrationTest extends PropelTestCase
{
    /**
     * @var PersisterLoader
     */
    private $loader;

    public function setUp()
    {
        $this->initDatabase();
        $connection = Propel::getConnection('default');
        $modelPersister = new ModelPersister($connection);
        $this->loader = new PersisterLoader(
            new SimpleLoader(
                new SimpleFileLoader(
                    new YamlParser(new Parser()),
                    new NativeLoader()
                )
            ),
            $modelPersister
        );
    }

    public function testLoad()
    {
        $this->loader->
    }
}


```

**Comment by dantleech** [comment]
Because containing structure is a trait and only classes and interfaces are recognised..
