### ISSUE TITLE
HoverHandler crashes on namespaced global functions

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1150]
When hovering on namespaced functions (e.g. `\Amp\call`), the HoverHandler crashes:
```
[Error - 10:09:01 PM] Request textDocument/hover failed.
  Message: Exception [Phpactor\WorseReflection\Core\Exception\SourceNotFound] Could not find source with "call"
  Code: -32603 
#0 /root/worse-reflection/lib/Core/Reflector/CoreReflector.php(178): Phpactor\WorseReflection\Core\SourceCodeLocator\ChainSourceLocator->locate(Object(Phpactor\WorseReflection\Core\Name))
#1 /root/worse-reflection/lib/Core/Reflector/ClassReflector/MemonizedReflector.php(95): Phpactor\WorseReflection\Core\Reflector\CoreReflector->reflectFunction(Object(Phpactor\WorseReflection\Core\Name))
#2 /root/worse-reflection/lib/Core/Cache/TtlCache.php(44): Phpactor\WorseReflection\Core\Reflector\ClassReflector\MemonizedReflector->Phpactor\WorseReflection\Core\Reflector\ClassReflector\{closure}()
#3 /root/worse-reflection/lib/Core/Reflector/ClassReflector/MemonizedReflector.php(96): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet('__func__call', Object(Closure))
#4 /root/worse-reflection/lib/Core/Reflector/CompositeReflector.php(110): Phpactor\WorseReflection\Core\Reflector\ClassReflector\MemonizedReflector->reflectFunction('call')
#5 /root/language-server-phpactor-extensions/lib/LanguageServerHover/Handler/HoverHandler.php(179): Phpactor\WorseReflection\Core\Reflector\CompositeReflector->reflectFunction('call')
#6 /root/language-server-phpactor-extensions/lib/LanguageServerHover/Handler/HoverHandler.php(126): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->renderFunction(Object(Phpactor\WorseReflection\Core\Inference\SymbolContext))
#7 /root/language-server-phpactor-extensions/lib/LanguageServerHover/Handler/HoverHandler.php(109): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->renderSymbolContext(Object(Phpactor\WorseReflection\Core\Inference\SymbolContext))
#8 /root/language-server-phpactor-extensions/lib/LanguageServerHover/Handler/HoverHandler.php(99): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->infoFromSymbolContext(Object(Phpactor\WorseReflection\Core\Inference\SymbolContext))
#9 /root/language-server-phpactor-extensions/lib/LanguageServerHover/Handler/HoverHandler.php(74): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->infoFromReflecionOffset(Object(Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionOffset))
#10 /root/phpactor/vendor/amphp/amp/lib/functions.php(90): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->Phpactor\Extension\LanguageServerHover\Handler\{closure}()
#11 /root/language-server-phpactor-extensions/lib/LanguageServerHover/Handler/HoverHandler.php(87): Amp\call(Object(Closure))
#12 /root/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(86): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->hover(Object(Phpactor\LanguageServerProtocol\TextDocumentIdentifier), Object(Phpactor\LanguageServerProtocol\Position), Object(class@anonymous))
#13 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#14 /root/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#15 /root/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#16 /root/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(102): Amp\call(Object(Closure))
#17 /root/phpactor/vendor/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#18 /root/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\HandlerMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#19 /root/phpactor/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(35): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#20 /root/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#21 /root/phpactor/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(37): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#22 /root/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#23 /root/phpactor/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#24 /root/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#25 /root/phpactor/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#26 /root/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#27 /root/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(39): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#28 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#29 /root/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#30 /root/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#31 /root/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(64): Amp\call(Object(Closure))
#32 /root/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#33 /root/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#34 /root/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(204): Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher->dispatch(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#35 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#36 /root/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#37 /root/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#38 /root/phpactor/vendor/amphp/amp/lib/functions.php(121): Amp\call(Object(Closure))
#39 /root/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(221): Amp\asyncCall(Object(Closure))
#40 /root/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(195): Phpactor\LanguageServer\Core\Server\LanguageServer->dispatchRequest(Object(Phpactor\LanguageServer\Core\Server\Transmitter\ConnectionMessageTransmitter), Object(Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher), Object(Phpactor\LanguageServer\Core\Server\StreamProvider\Connection), Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#41 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#42 /root/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#43 /root/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#44 /root/phpactor/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve(Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#45 /root/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, 'Content-Length:...')
#46 /root/phpactor/vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve('Content-Length:...')
#47 /root/phpactor/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve('Content-Length:...')
#48 /root/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(183): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('a', Resource id #1, NULL)
#49 /root/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(96): Amp\Loop\NativeDriver->selectStreams(Array, Array, 0.5)
#50 /root/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch(true)
#51 /root/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#52 /root/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#53 /root/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(113): Amp\Loop::run(Object(Closure))
#54 /root/phpactor/vendor/phpactor/language-server-extension/lib/LanguageServer/Command/StartCommand.php(59): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#55 /root/phpactor/vendor/symfony/console/Command/Command.php(255): Phpactor\Extension\LanguageServer\Command\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#56 /root/phpactor/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#57 /root/phpactor/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Phpactor\Extension\LanguageServer\Command\StartCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#58 /root/phpactor/lib/Application.php(53): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#59 /root/phpactor/vendor/symfony/console/Application.php(149): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#60 /root/phpactor/bin/phpactor(42): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#61 {main}
```
The problem, I think, is on [this line](https://github.com/phpactor/language-server-phpactor-extensions/blob/master/lib/LanguageServerHover/Handler/HoverHandler.php#L179). `$name` is not qualified, it's just `call`, rather than `Amp\call`. When I change it to `$function = $this->reflector->reflectFunction((string)$symbolContext->name());` then it works, but I am unsure if that is the proper way to get the fully qualified name.

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/language-server-phpactor-extensions/pull/13
