### ISSUE TITLE
Exception when completion inside an unresolvable method

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1198]
In the following example `willThrow` is not defined as `execute` is a magic method and does not have a return type (it should be `MethodProphecy`, btw, probably we can infer it better). Typing `AccessDenied` continuously pops this exception. Extremely annoying.

```php
$prophecy->execute(Argument::any())->willThrow(AccessDenied<>);
```
```
[Error - 11:37:45 AM] Request textDocument/completion failed.
  Message: Exception [Phpactor\WorseReflection\Core\Exception\CouldNotResolveNode] Class for member "willThrow" could not be determined
  Code: -32603 
#0 /root/phpactor/completion/lib/Bridge/TolerantParser/WorseReflection/WorseNamedParameterCompletor.php(120): Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\AbstractReflectionMethodCall->class()
#1 /root/phpactor/completion/lib/Bridge/TolerantParser/WorseReflection/WorseNamedParameterCompletor.php(66): Phpactor\Completion\Bridge\TolerantParser\WorseReflection\WorseNamedParameterCompletor->fromCallExpression()
#2 /root/phpactor/completion/lib/Bridge/TolerantParser/ChainTolerantCompletor.php(58): Phpactor\Completion\Bridge\TolerantParser\WorseReflection\WorseNamedParameterCompletor->complete()
#3 /root/phpactor/completion/lib/Core/ChainCompletor.php(31): Phpactor\Completion\Bridge\TolerantParser\ChainTolerantCompletor->complete()
#4 /root/phpactor/completion/lib/Core/Completor/DedupeCompletor.php(35): Phpactor\Completion\Core\ChainCompletor->complete()
#5 /root/phpactor/language-server-phpactor-extensions/lib/LanguageServerCompletion/Handler/CompletionHandler.php(102): Phpactor\Completion\Core\Completor\DedupeCompletor->complete()
#6 [internal function]: Phpactor\Extension\LanguageServerCompletion\Handler\CompletionHandler->Phpactor\Extension\LanguageServerCompletion\Handler\{closure}()
#7 /root/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#8 /root/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#9 /root/phpactor/language-server-phpactor-extensions/lib/LanguageServerCompletion/Handler/CompletionHandler.php(139): Amp\call()
#10 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(86): Phpactor\Extension\LanguageServerCompletion\Handler\CompletionHandler->completion()
#11 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#12 /root/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#13 /root/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#14 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(102): Amp\call()
#15 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch()
#16 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\HandlerMiddleware->process()
#17 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(35): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#18 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process()
#19 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(37): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#20 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process()
#21 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#22 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process()
#23 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#24 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process()
#25 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(39): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#26 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#27 /root/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#28 /root/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#29 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(64): Amp\call()
#30 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process()
#31 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#32 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(204): Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher->dispatch()
#33 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#34 /root/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#35 /root/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#36 /root/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(121): Amp\call()
#37 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(221): Amp\asyncCall()
#38 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(195): Phpactor\LanguageServer\Core\Server\LanguageServer->dispatchRequest()
#39 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#40 /root/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#41 /root/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#42 /root/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve()
#43 /root/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#44 /root/phpactor/phpactor/vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve()
#45 /root/phpactor/phpactor/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve()
#46 /root/phpactor/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(321): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#47 /root/phpactor/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams()
#48 /root/phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#49 /root/phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#50 /root/phpactor/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#51 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(113): Amp\Loop::run()
#52 /root/phpactor/phpactor/vendor/phpactor/language-server-extension/lib/LanguageServer/Command/StartCommand.php(59): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#53 /root/phpactor/phpactor/vendor/symfony/console/Command/Command.php(255): Phpactor\Extension\LanguageServer\Command\StartCommand->execute()
#54 /root/phpactor/phpactor/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#55 /root/phpactor/phpactor/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#56 /root/phpactor/phpactor/lib/Application.php(53): Symfony\Component\Console\Application->doRun()
#57 /root/phpactor/phpactor/vendor/symfony/console/Application.php(166): Phpactor\Application->doRun()
#58 /root/phpactor/phpactor/bin/phpactor(42): Symfony\Component\Console\Application->run()
#59 {main}
```

**Comment by dantleech** [comment]
This should be fixed already -- can you try updating worse-reflection?

**Comment by BladeMF** [comment]
Yes, when I have the time I need to go through the procedure of updating everything :-)

**Comment by camilledejoye** [comment]
I ended up with a makefile for this on my end.
Don't wait too much time before doing one, because the more packages you touch the worse it gets :smile:

**Comment by BladeMF** [comment]
Care to share?

**Comment by BladeMF** [comment]
I only did a link script which recreated the links after composer install.

**Comment by camilledejoye** [comment]
Sorry don't have it on this computer and I would be a bit ashamed :)
Some ugly loops in shell to go over all package (they are in a dedicated folder).

I think the idea is better than my solution and I won't be helping you anyway :D

**Comment by dantleech** [comment]
Assuming this is fixed, please open again if not :)
