### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1206]
```
[Error  - 11:51:04] Request textDocument/completion failed.
  Message: Exception [Error] Call to a member function getText() on null
  Code: -32603 
#0 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(104): Phpactor\WorseReflection\Core\Inference\FrameBuilder\CatchWalker->walk()
#1 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Cache/TtlCache.php(44): Phpactor\WorseReflection\Core\Inference\FrameBuilder->Phpactor\WorseReflection\Core\Inference\{closure}()
#2 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(125): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet()
#3 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(109): Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode()
#4 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Cache/TtlCache.php(44): Phpactor\WorseReflection\Core\Inference\FrameBuilder->Phpactor\WorseReflection\Core\Inference\{closure}()
#5 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(125): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet()
#6 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(109): Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode()
#7 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Cache/TtlCache.php(44): Phpactor\WorseReflection\Core\Inference\FrameBuilder->Phpactor\WorseReflection\Core\Inference\{closure}()
#8 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(125): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet()
#9 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(109): Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode()
#10 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Cache/TtlCache.php(44): Phpactor\WorseReflection\Core\Inference\FrameBuilder->Phpactor\WorseReflection\Core\Inference\{closure}()
#11 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(125): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet()
#12 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(73): Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode()
#13 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflector/TolerantSourceCodeReflector.php(63): Phpactor\WorseReflection\Core\Inference\FrameBuilder->build()
#14 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CompositeReflector.php(89): Phpactor\WorseReflection\Bridge\TolerantParser\Reflector\TolerantSourceCodeReflector->reflectOffset()
#15 /home/daniel/www/phpactor/phpactor/vendor/phpactor/completion/lib/Bridge/TolerantParser/WorseReflection/Helper/VariableCompletionHelper.php(40): Phpactor\WorseReflection\Core\Reflector\CompositeReflector->reflectOffset()
#16 /home/daniel/www/phpactor/phpactor/vendor/phpactor/completion/lib/Bridge/TolerantParser/WorseReflection/WorseLocalVariableCompletor.php(49): Phpactor\Completion\Bridge\TolerantParser\WorseReflection\Helper\VariableCompletionHelper->variableCompletions()
#17 /home/daniel/www/phpactor/phpactor/vendor/phpactor/completion/lib/Bridge/TolerantParser/ChainTolerantCompletor.php(58): Phpactor\Completion\Bridge\TolerantParser\WorseReflection\WorseLocalVariableCompletor->complete()
#18 /home/daniel/www/phpactor/phpactor/vendor/phpactor/completion/lib/Core/ChainCompletor.php(31): Phpactor\Completion\Bridge\TolerantParser\ChainTolerantCompletor->complete()
#19 /home/daniel/www/phpactor/phpactor/vendor/phpactor/completion/lib/Core/Completor/DedupeCompletor.php(35): Phpactor\Completion\Core\ChainCompletor->complete()
#20 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerCompletion/Handler/CompletionHandler.php(102): Phpactor\Completion\Core\Completor\DedupeCompletor->complete()
#21 [internal function]: Phpactor\Extension\LanguageServerCompletion\Handler\CompletionHandler->Phpactor\Extension\LanguageServerCompletion\Handler\{closure}()
#22 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#23 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#24 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerCompletion/Handler/CompletionHandler.php(139): Amp\call()
#25 /home/daniel/www/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(86): Phpactor\Extension\LanguageServerCompletion\Handler\CompletionHandler->completion()
#26 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#27 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#28 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#29 /home/daniel/www/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(102): Amp\call()
#30 /home/daniel/www/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch()
#31 /home/daniel/www/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\HandlerMiddleware->process()
#32 /home/daniel/www/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(35): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#33 /home/daniel/www/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process()
#34 /home/daniel/www/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(37): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#35 /home/daniel/www/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process()
#36 /home/daniel/www/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#37 /home/daniel/www/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process()
#38 /home/daniel/www/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#39 /home/daniel/www/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process()
#40 /home/daniel/www/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(39): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#41 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#42 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#43 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#44 /home/daniel/www/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(64): Amp\call()
#45 /home/daniel/www/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process()
```

**Comment by dantleech** [comment]
Should be fixed in https://github.com/phpactor/worse-reflection/commit/2a5e596d00dca8a80723863ea5e495aeca2f4ab5
