### ISSUE TITLE
Hovering unknown functions cause exception

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1215]
When hovering functions which are not defined this exception is caused:
```
[Error - 10:13:36 AM] Request textDocument/hover failed.
  Message: Exception [InvalidArgumentException] Do not know how to create class from type "NULL"
  Code: -32603 
#0 /root/phpactor/worse-reflection/lib/Core/Reflector/CoreReflector.php(176): Phpactor\WorseReflection\Core\Name::fromUnknown()
#1 /root/phpactor/worse-reflection/lib/Core/Reflector/ClassReflector/MemonizedReflector.php(95): Phpactor\WorseReflection\Core\Reflector\CoreReflector->reflectFunction()
#2 /root/phpactor/worse-reflection/lib/Core/Cache/TtlCache.php(44): Phpactor\WorseReflection\Core\Reflector\ClassReflector\MemonizedReflector->Phpactor\WorseReflection\Core\Reflector\ClassReflector\{closure}()
#3 /root/phpactor/worse-reflection/lib/Core/Reflector/ClassReflector/MemonizedReflector.php(96): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet()
#4 /root/phpactor/worse-reflection/lib/Core/Reflector/CompositeReflector.php(110): Phpactor\WorseReflection\Core\Reflector\ClassReflector\MemonizedReflector->reflectFunction()
#5 /root/phpactor/language-server-phpactor-extensions/lib/LanguageServerHover/Handler/HoverHandler.php(179): Phpactor\WorseReflection\Core\Reflector\CompositeReflector->reflectFunction()
#6 /root/phpactor/language-server-phpactor-extensions/lib/LanguageServerHover/Handler/HoverHandler.php(126): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->renderFunction()
#7 /root/phpactor/language-server-phpactor-extensions/lib/LanguageServerHover/Handler/HoverHandler.php(109): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->renderSymbolContext()
#8 /root/phpactor/language-server-phpactor-extensions/lib/LanguageServerHover/Handler/HoverHandler.php(99): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->infoFromSymbolContext()
#9 /root/phpactor/language-server-phpactor-extensions/lib/LanguageServerHover/Handler/HoverHandler.php(74): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->infoFromReflecionOffset()
#10 /root/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(90): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->Phpactor\Extension\LanguageServerHover\Handler\{closure}()
#11 /root/phpactor/language-server-phpactor-extensions/lib/LanguageServerHover/Handler/HoverHandler.php(87): Amp\call()
#12 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(86): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->hover()
#13 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#14 /root/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#15 /root/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#16 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(102): Amp\call()
#17 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch()
#18 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\HandlerMiddleware->process()
#19 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(35): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#20 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process()
#21 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(37): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#22 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process()
#23 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#24 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process()
#25 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#26 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process()
#27 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(39): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#28 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#29 /root/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#30 /root/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#31 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(64): Amp\call()
#32 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process()
#33 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#34 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(223): Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher->dispatch()
#35 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#36 /root/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#37 /root/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#38 /root/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(121): Amp\call()
#39 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(240): Amp\asyncCall()
#40 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(214): Phpactor\LanguageServer\Core\Server\LanguageServer->dispatchRequest()
#41 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#42 /root/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#43 /root/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#44 /root/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve()
#45 /root/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#46 /root/phpactor/phpactor/vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve()
#47 /root/phpactor/phpactor/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve()
#48 /root/phpactor/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(321): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#49 /root/phpactor/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams()
#50 /root/phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#51 /root/phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#52 /root/phpactor/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#53 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(113): Amp\Loop::run()
#54 /root/phpactor/phpactor/vendor/phpactor/language-server-extension/lib/LanguageServer/Command/StartCommand.php(59): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#55 /root/phpactor/phpactor/vendor/symfony/console/Command/Command.php(256): Phpactor\Extension\LanguageServer\Command\StartCommand->execute()
#56 /root/phpactor/phpactor/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#57 /root/phpactor/phpactor/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#58 /root/phpactor/phpactor/lib/Application.php(54): Symfony\Component\Console\Application->doRun()
#59 /root/phpactor/phpactor/vendor/symfony/console/Application.php(166): Phpactor\Application->doRun()
#60 /root/phpactor/phpactor/bin/phpactor(42): Symfony\Component\Console\Application->run()
#61 {main}
```

**Comment by dantleech** [comment]
Thanks - fixed in https://github.com/phpactor/language-server-phpactor-extensions/commit/4f7e7d9284da684958364d65900deaeabd6b48ca pending release
