### ISSUE TITLE
Extension "Phpactor\Extension\ReferenceFinder\ReferenceFinderExtension" does not exist

### ISSUE THREAD

**Issue by umpirsky** [phpactor/phpactor#1224]
```
$ git checkout 0.17.0
HEAD is now at dac62dd Master 17 (#1203)

$ composer install                       
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
65 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> bin/phpactor extension:update
Extension "Phpactor\Extension\ReferenceFinder\ReferenceFinderExtension" does not exist
PHP Fatal error:  Uncaught Error: Class "Phpactor\Extension\ReferenceFinder\ReferenceFinderExtension" not found in /home/umpirsky/Projects/phpactor/vendor/phpactor/worse-reference-finder-extension/lib/WorseReferenceFinderExtension.php:28
Stack trace:
#0 /home/umpirsky/Projects/phpactor/lib/Phpactor.php(190): Phpactor\Extension\WorseReferenceFinder\WorseReferenceFinderExtension->load()
#1 /home/umpirsky/Projects/phpactor/lib/Application.php(112): Phpactor\Phpactor::boot()
#2 /home/umpirsky/Projects/phpactor/lib/Application.php(39): Phpactor\Application->initialize()
#3 /home/umpirsky/Projects/phpactor/vendor/symfony/console/Application.php(166): Phpactor\Application->doRun()
#4 /home/umpirsky/Projects/phpactor/bin/phpactor(42): Symfony\Component\Console\Application->run()
#5 {main}
  thrown in /home/umpirsky/Projects/phpactor/vendor/phpactor/worse-reference-finder-extension/lib/WorseReferenceFinderExtension.php on line 28
Fatal error: Uncaught Error: Class "Phpactor\Extension\ReferenceFinder\ReferenceFinderExtension" not found in /home/umpirsky/Projects/phpactor/vendor/phpactor/worse-reference-finder-extension/lib/WorseReferenceFinderExtension.php:28
Stack trace:
#0 /home/umpirsky/Projects/phpactor/lib/Phpactor.php(190): Phpactor\Extension\WorseReferenceFinder\WorseReferenceFinderExtension->load()
#1 /home/umpirsky/Projects/phpactor/lib/Application.php(112): Phpactor\Phpactor::boot()
#2 /home/umpirsky/Projects/phpactor/lib/Application.php(39): Phpactor\Application->initialize()
#3 /home/umpirsky/Projects/phpactor/vendor/symfony/console/Application.php(166): Phpactor\Application->doRun()
#4 /home/umpirsky/Projects/phpactor/bin/phpactor(42): Symfony\Component\Console\Application->run()
#5 {main}
  thrown in /home/umpirsky/Projects/phpactor/vendor/phpactor/worse-reference-finder-extension/lib/WorseReferenceFinderExtension.php on line 28
Script bin/phpactor extension:update handling the post-install-cmd event returned with error code 255

$ php -v
PHP 8.0.3 (cli) (built: Mar  5 2021 07:54:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
```

**Comment by dantleech** [comment]
Can't reproduce this :thinking:

**Comment by umpirsky** [comment]
PHP 8.0.3?

**Comment by dantleech** [comment]
PHP 8.0.x - maybe `mv extensions/extensions.json extensions.extensions.json.back` and try again. if that works see if there is anything weird in `extensions.json`

**Comment by umpirsky** [comment]
No, same error.

**Comment by dantleech** [comment]
Maybe mv the entire directory? `extensions extensions.back`

**Comment by umpirsky** [comment]
Nope, same error. :cry:

**Comment by dantleech** [comment]
Can you check that, er, the extension exists? `Phpactor\Extension\ReferenceFinder\ReferenceFinderExtension` it's certainly in `composer.json`. Maybe also `rm -Rf vendor` to be sure.

**Comment by umpirsky** [comment]
It does, but for some reason `rm -Rf vendor` solved the issue. Thanks!

**Comment by umpirsky** [comment]
FYI:

```
> bin/phpactor extension:update
<warning>Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2</warning>
Loading composer repositories with package information
<warning>Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2</warning>
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dantleech/what-changed 0.4.1 requires php ^7.3 -> your PHP version (8.0.3) does not satisfy that requirement.
    - dantleech/what-changed 0.4.1 requires php ^7.3 -> your PHP version (8.0.3) does not satisfy that requirement.
    - Installation request for dantleech/what-changed 0.4.1 -> satisfiable by dantleech/what-changed[0.4.1].

<warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>

In LazyComposerInstaller.php line 50:
                            
  Composer exited with "2"  
                            

extension:update

Script bin/phpactor extension:update handling the post-install-cmd event returned with error code 255

```

**Comment by dantleech** [comment]
`what-changed` supports 8.0 now, 17.1 is the latest tag :man_shrugging: glad it's solved.
