### ISSUE TITLE
Error on complete constructor

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#123]
Apparently caused by `private $exists = true`
```
Type number and <Enter> or click with mouse (empty cancels): 1PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method name
d "getName" of class "Microsoft\PhpParser\Node\Expression\AssignmentExpression".
Did you mean to call "getNamespaceDefinition"? in /home/daniel/.vim/bundle/phpactor/vendor/phpactor/code-builder/lib/Adapter/TolerantParser/TolerantUpdater.php:225
Stack trace:
#0 /home/daniel/.vim/bundle/phpactor/vendor/phpactor/code-builder/lib/Adapter/TolerantParser/TolerantUpdater.php(161): Phpactor\CodeBuilder\Adapter\TolerantParser\TolerantUpdater->updatePrope
rties(Object(Phpactor\CodeBuilder\Domain\Prototype\ClassPrototype), Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#1 /home/daniel/.vim/bundle/phpactor/vendor/phpactor/code-builder/lib/Adapter/TolerantParser/TolerantUpdater.php(139): Phpactor\CodeBuilder\Adapter\TolerantParser\TolerantUpdater->updateClass
(Object(Phpactor\CodeBuilder\Domain\Prototype\ClassPrototype), Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#2 /home/daniel/.vim in /home/daniel/.vim/bundle/phpactor/vendor/phpactor/code-builder/lib/Adapter/TolerantParser/TolerantUpdater.php on line 225
```

```
<?php

namespace Phpactor\ClassMover\Domain\Reference;

use Phpactor\ClassMover\Domain\Name\ImportedName;

final class ImportedNameReference
{
    private $exists = true;

    private function __construct(Position $position, ImportedName $importedName)
    {
    }

    public static function none()
    {
        $new = new self();
        $new->exists = false;

        return $new;
    }

    public static function fromImportedNameAndPosition(ImportedName $importedName, Position $position): ImportedNamespaceReference
    {
        $new = new self();
        $new->position = $position;
        $new->importedName = $importedName;

        return $new;
    }

    public function exists()
    {
        return $this->exists;
    }

    public function __toString()
    {
        return (string) $this->fullName;
    }

    public function position(): Position
    {
        return $this->position;
    }

    public function importedName(): ImportedName
    {
        return $this->importedName;
    }
}
```

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/code-builder/commit/569a4947d805e54d256756572c412c36f8ac879f
