### ISSUE TITLE
Rename error

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1240]
```
Starting language server, use -vvv for verbose output
[Error  - 18:21:32] Request textDocument/rename failed.
  Message: Exception [Phpactor\TextDocument\Exception\TextDocumentNotFound] Text Document not found at URI "file:///home/daniel/www/phpbench/phpbench/vendor/padraic/phar-updater/src/Updater.php"
  Code: -32603 
#0 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerReferenceFinder/Adapter/Indexer/WorkspaceUpdateReferenceFinder.php(52): Phpactor\TextDocument\TextDocumentBuilder::fromUri()
#1 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerReferenceFinder/Adapter/Indexer/WorkspaceUpdateReferenceFinder.php(41): Phpactor\Extension\LanguageServerReferenceFinder\Adapter\Indexer\WorkspaceUpdateReferenceFinder->indexWorkspace()
#2 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerRename/Adapter/ReferenceFinder/ClassMover/ClassRenamer.php(84): Phpactor\Extension\LanguageServerReferenceFinder\Adapter\Indexer\WorkspaceUpdateReferenceFinder->findReferences()
```

**Comment by BladeMF** [comment]
I had a ton of those. Never got around to fixing them :-(

**Comment by dantleech** [comment]
Should be fixed now ...
