### ISSUE TITLE
[RuntimeException] preg_replace could not parse string

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1245]
```
Starting language server, use -vvv for verbose output
[Error  - 09:14:27] Request textDocument/completion failed.
  Message: Exception [RuntimeException] preg_replace could not parse string
  Code: -32603 
#0 /home/daniel/www/phpactor/phpactor/vendor/phpactor/completion/lib/Bridge/TolerantParser/ChainTolerantCompletor.php(75): Phpactor\Completion\Core\Util\OffsetHelper::lastNonWhitespaceCharacterOffset()
#1 /home/daniel/www/phpactor/phpactor/vendor/phpactor/completion/lib/Bridge/TolerantParser/ChainTolerantCompletor.php(36): Phpactor\Completion\Bridge\TolerantParser\ChainTolerantCompletor->truncateSource()
#2 /home/daniel/www/phpactor/phpactor/vendor/phpactor/completion/lib/Core/ChainCompletor.php(31): Phpactor\Completion\Bridge\TolerantParser\ChainTolerantCompletor->complete()
#3 /home/daniel/www/phpactor/phpactor/vendor/phpactor/completion/lib/Core/Completor/DedupeCompletor.php(35): Phpactor\Completion\Core\ChainCompletor->complete()
#4 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerCompletion/Handler/CompletionHandler.php(102): Phpactor\Completion\Core\Completor\DedupeCompletor->complete()
#5 [internal function]: Phpactor\Extension\LanguageServerCompletion\Handler\CompletionHandler->Phpactor\Extension\LanguageServerCompletion\Handler\{closure}()
#6 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#7 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#8 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerCompletion/Handler/CompletionHandler.php(139): Amp\call()
#9 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(86): Phpactor\Extension\LanguageServerCompletion\Handler\CompletionHandler->completion()
#10 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#11 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#12 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#13 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(102): Amp\call()
#14 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch()
#15 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\HandlerMiddleware->process()
#16 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(35): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#17 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process()
#18 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(37): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#19 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process()
#20 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#21 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process()
#22 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#23 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process()
#24 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(39): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#25 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#26 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#27 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#28 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(64): Amp\call()
#29 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process()
#30 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#31 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(223): Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher->dispatch()
#32 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#33 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#34 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#35 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(121): Amp\call()
#36 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(240): Amp\asyncCall()
#37 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(214): Phpactor\LanguageServer\Core\Server\LanguageServer->dispatchRequest()
#38 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()

```

**Comment by dantleech** [comment]
Inclded the string it could not parse in the excetion message
