### ISSUE TITLE
[InvalidArgumentException] Do not know how to create class from type "NULL"

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1246]
```
Starting language server, use -vvv for verbose output
[Error  - 14:15:51] Request textDocument/definition failed.
  Message: Exception [InvalidArgumentException] Do not know how to create class from type "NULL"
  Code: -32603 
#0 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CoreReflector.php(176): Phpactor\WorseReflection\Core\Name::fromUnknown()
#1 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/ClassReflector/MemonizedReflector.php(95): Phpactor\WorseReflection\Core\Reflector\CoreReflector->reflectFunction()
#2 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Cache/TtlCache.php(44): Phpactor\WorseReflection\Core\Reflector\ClassReflector\MemonizedReflector->Phpactor\WorseReflection\Core\Reflector\ClassReflector\{closure}()
#3 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/ClassReflector/MemonizedReflector.php(96): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet()
#4 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CompositeReflector.php(110): Phpactor\WorseReflection\Core\Reflector\ClassReflector\MemonizedReflector->reflectFunction()
#5 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reference-finders/lib/WorseReflectionDefinitionLocator.php(121): Phpactor\WorseReflection\Core\Reflector\CompositeReflector->reflectFunction()
#6 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reference-finders/lib/WorseReflectionDefinitionLocator.php(80): Phpactor\WorseReferenceFinder\WorseReflectionDefinitionLocator->gotoFunction()
#7 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reference-finders/lib/WorseReflectionDefinitionLocator.php(66): Phpactor\WorseReferenceFinder\WorseReflectionDefinitionLocator->gotoDefinition()
#8 /home/daniel/www/phpactor/phpactor/vendor/phpactor/reference-finder/lib/ChainDefinitionLocationProvider.php(37): Phpactor\WorseReferenceFinder\WorseReflectionDefinitionLocator->locateDefinition()
#9 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerReferenceFinder/Handler/GotoDefinitionHandler.php(58): Phpactor\ReferenceFinder\ChainDefinitionLocationProvider->locateDefinition()
#10 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(90): Phpactor\Extension\LanguageServerReferenceFinder\Handler\GotoDefinitionHandler->Phpactor\Extension\LanguageServerReferenceFinder\Handler\{closure}()
#11 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerReferenceFinder/Handler/GotoDefinitionHandler.php(68): Amp\call()
#12 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(86): Phpactor\Extension\LanguageServerReferenceFinder\Handler\GotoDefinitionHandler->definition()
#13 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#14 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#15 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#16 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(102): Amp\call()
#17 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch()
#18 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\HandlerMiddleware->process()
```

**Comment by CaptainQuirk** [comment]
I'm also seeing this when using `<C-x><C-o>`  ! Did you manage to pinpoint the origin of this issue ?

I'm using the RPC plugin.

I have this configuration line regarding phpactor

```vim
autocmd FileType php setlocal omnifunc=phpactor#Complete
```

```
[2022-09-06 09:47:19] phpactor.ERROR: RESPONSE {"channel":"rpc","action":"error","parameters":{"message":"Do not know how to create class from type \"NULL\"","details":"0: Do not know how to create class from type \"NULL\"\n#0 /home/leonard/.local/etc/vim/bundle/phpactor/lib/WorseReflection/Core/Reflector/CoreReflector.php(141): Phpactor\\WorseReflection\\Core\\Name::fromUnknown()\n#1 /home/leonard/.local/etc/vim/bundle/phpactor/lib/WorseReflection/Core/Reflector/ClassReflector/MemonizedReflector.php(81): Phpactor\\WorseReflection\\Core\\Reflector\\CoreReflector->reflectClassLike()\n#2 /home/leonard/.local/etc/vim/bundle/phpactor/lib/WorseReflection/Core/Reflector/ClassReflector/MemonizedReflector.php(113): Phpactor\\WorseReflection\\Core\\Reflector\\ClassReflector\\MemonizedReflector->Phpactor\\WorseReflection\\Core\\Reflector\\ClassReflector\\{closure}()\n#3 /home/leonard/.local/etc/vim/bundle/phpactor/lib/WorseReflection/Core/Cache/TtlCache.php(50): Phpactor\\WorseReflection\\Core\\Reflector\\ClassReflector\\MemonizedReflector->Phpactor\\WorseReflection\\Core\\Reflector\\ClassReflector\\{closure}()\n#4 /home/leonard/.local/etc/vim/bundle/phpactor/lib/WorseReflection/Core/Reflector/ClassReflector/MemonizedReflector.php(118): Phpactor\\WorseReflection\\Core\\Cache\\TtlCache->getOrSet()\n#5 /home/leonard/.local/etc/vim/bundle/phpactor/lib/WorseReflection/Core/Reflector/ClassReflector/MemonizedReflector.php(82): Phpactor\\WorseReflection\\Core\\Reflector\\ClassReflector\\MemonizedReflector->getOrSet()\n#6 /home/leonard/.local/etc/vim/bundle/phpactor/lib/WorseReflection/Core/Reflector/CompositeReflector.php(61): Phpactor\\WorseReflection\\Core\\Reflector\\ClassReflector\\MemonizedReflector->reflectClassLike()\n#7 /home/leonard/.local/etc/vim/bundle/phpactor/lib/Completion/Bridge/WorseReflection/SuggestionDocumentor/WorseSuggestionDocumentor.php(30): Phpactor\\WorseReflection\\Core\\Reflector\\CompositeReflector->reflectClassLike()\n#8 /home/leonard/.local/etc/vim/bundle/phpactor/lib/Completion/Core/Suggestion.php(235): Phpactor\\Completion\\Bridge\\WorseReflection\\SuggestionDocumentor\\WorseSuggestionDocumentor->Phpactor\\Completion\\Bridge\\WorseReflection\\SuggestionDocumentor\\{closure}()\n#9 /home/leonard/.local/etc/vim/bundle/phpactor/lib/Completion/Core/Suggestion.php(152): Phpactor\\Completion\\Core\\Suggestion->documentation()\n#10 /home/leonard/.local/etc/vim/bundle/phpactor/lib/Extension/CompletionRpc/Handler/CompleteHandler.php(58): Phpactor\\Completion\\Core\\Suggestion->toArray()\n#11 [internal function]: Phpactor\\Extension\\CompletionRpc\\Handler\\CompleteHandler->Phpactor\\Extension\\CompletionRpc\\Handler\\{closure}()\n#12 /home/leonard/.local/etc/vim/bundle/phpactor/lib/Extension/CompletionRpc/Handler/CompleteHandler.php(59): array_map()\n#13 /home/leonard/.local/etc/vim/bundle/phpactor/lib/Extension/Rpc/RequestHandler/RequestHandler.php(30): Phpactor\\Extension\\CompletionRpc\\Handler\\CompleteHandler->handle()\n#14 /home/leonard/.local/etc/vim/bundle/phpactor/lib/Extension/Rpc/RequestHandler/ExceptionCatchingHandler.php(23): Phpactor\\Extension\\Rpc\\RequestHandler\\RequestHandler->handle()\n#15 /home/leonard/.local/etc/vim/bundle/phpactor/lib/Extension/Rpc/RequestHandler/LoggingHandler.php(33): Phpactor\\Extension\\Rpc\\RequestHandler\\ExceptionCatchingHandler->handle()\n#16 /home/leonard/.local/etc/vim/bundle/phpactor/lib/Extension/Rpc/Command/RpcCommand.php(80): Phpactor\\Extension\\Rpc\\RequestHandler\\LoggingHandler->handle()\n#17 /home/leonard/.local/etc/vim/bundle/phpactor/lib/Extension/Rpc/Command/RpcCommand.php(60): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->processRequest()\n#18 /home/leonard/.local/etc/vim/bundle/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->execute()\n#19 /home/leonard/.local/etc/vim/bundle/phpactor/vendor/symfony/console/Application.php(1024): Symfony\\Component\\Console\\Command\\Command->run()\n#20 /home/leonard/.local/etc/vim/bundle/phpactor/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()\n#21 /home/leonard/.local/etc/vim/bundle/phpactor/lib/Application.php(48): Symfony\\Component\\Console\\Application->doRun()\n#22 /home/leonard/.local/etc/vim/bundle/phpactor/vendor/symfony/console/Application.php(171): Phpactor\\Application->doRun()\n#23 /home/leonard/.local/etc/vim/bundle/phpactor/bin/phpactor(45): Symfony\\Component\\Console\\Application->run()\n#24 {main}"}} []
```

On my machine, it happened after resinstalling all my plugins.

**Comment by dantleech** [comment]
Are you using the latest (master) version of Phpactor?

**Comment by CaptainQuirk** [comment]
Last commit is indeed `e4ac4b8c` locally and I rerun composer install just in case this morning but it is up to date !

**Comment by dantleech** [comment]
I think this is rather a recent regression which could be fixed in https://github.com/phpactor/phpactor/pull/1861. I'm going to close this as the code has changed significantly since I raised this issue.
