### ISSUE TITLE
WorseMissingMethodFinder exception

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1268]
I can't find the code that causes it, though.

```
[Error - 8:13:26 AM] Request textDocument/codeAction failed.
  Message: Exception [Error] Call to a member function getElements() on null
  Code: -32603 
#0 /root/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(104): Phpactor\WorseReflection\Core\Inference\FrameBuilder\AssertFrameWalker->walk()
#1 /root/phpactor/worse-reflection/lib/Core/Cache/TtlCache.php(44): Phpactor\WorseReflection\Core\Inference\FrameBuilder->Phpactor\WorseReflection\Core\Inference\{closure}()
#2 /root/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(125): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet()
#3 /root/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(109): Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode()
#4 /root/phpactor/worse-reflection/lib/Core/Cache/TtlCache.php(44): Phpactor\WorseReflection\Core\Inference\FrameBuilder->Phpactor\WorseReflection\Core\Inference\{closure}()
#5 /root/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(125): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet()
#6 /root/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(109): Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode()
#7 /root/phpactor/worse-reflection/lib/Core/Cache/TtlCache.php(44): Phpactor\WorseReflection\Core\Inference\FrameBuilder->Phpactor\WorseReflection\Core\Inference\{closure}()
#8 /root/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(125): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet()
#9 /root/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(109): Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode()
#10 /root/phpactor/worse-reflection/lib/Core/Cache/TtlCache.php(44): Phpactor\WorseReflection\Core\Inference\FrameBuilder->Phpactor\WorseReflection\Core\Inference\{closure}()
#11 /root/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(125): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet()
#12 /root/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(109): Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode()
#13 /root/phpactor/worse-reflection/lib/Core/Cache/TtlCache.php(44): Phpactor\WorseReflection\Core\Inference\FrameBuilder->Phpactor\WorseReflection\Core\Inference\{closure}()
#14 /root/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(125): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet()
#15 /root/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(109): Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode()
#16 /root/phpactor/worse-reflection/lib/Core/Cache/TtlCache.php(44): Phpactor\WorseReflection\Core\Inference\FrameBuilder->Phpactor\WorseReflection\Core\Inference\{closure}()
#17 /root/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(125): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet()
#18 /root/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(73): Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode()
#19 /root/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflector/TolerantSourceCodeReflector.php(63): Phpactor\WorseReflection\Core\Inference\FrameBuilder->build()
#20 /root/phpactor/worse-reflection/lib/Core/Reflector/CompositeReflector.php(89): Phpactor\WorseReflection\Bridge\TolerantParser\Reflector\TolerantSourceCodeReflector->reflectOffset()
#21 /root/phpactor/code-transform/lib/Adapter/WorseReflection/Helper/WorseMissingMethodFinder.php(45): Phpactor\WorseReflection\Core\Reflector\CompositeReflector->reflectOffset()
#22 /root/phpactor/language-server-phpactor-extensions/lib/LanguageServerCodeTransform/CodeAction/GenerateMethodProvider.php(88): Phpactor\CodeTransform\Adapter\WorseReflection\Helper\WorseMissingMethodFinder->find()
#23 /root/phpactor/language-server-phpactor-extensions/lib/LanguageServerCodeTransform/CodeAction/GenerateMethodProvider.php(58): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\GenerateMethodProvider->getDiagnostics()
#24 /root/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(90): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\GenerateMethodProvider->Phpactor\Extension\LanguageServerCodeTransform\CodeAction\{closure}()
#25 /root/phpactor/language-server-phpactor-extensions/lib/LanguageServerCodeTransform/CodeAction/GenerateMethodProvider.php(80): Amp\call()
#26 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/CodeAction/AggregateCodeActionProvider.php(30): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\GenerateMethodProvider->provideActionsFor()
#27 [internal function]: Phpactor\LanguageServer\Core\CodeAction\AggregateCodeActionProvider->Phpactor\LanguageServer\Core\CodeAction\{closure}()
#28 /root/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#29 /root/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#30 /root/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve()
#31 /root/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#32 /root/phpactor/phpactor/vendor/amphp/amp/lib/Delayed.php(26): Amp\Delayed->resolve()
#33 /root/phpactor/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(142): Amp\Delayed->Amp\{closure}()
#34 /root/phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#35 /root/phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#36 /root/phpactor/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#37 /root/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(113): Amp\Loop::run()
#38 /root/phpactor/phpactor/vendor/phpactor/language-server-extension/lib/LanguageServer/Command/StartCommand.php(59): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#39 /root/phpactor/phpactor/vendor/symfony/console/Command/Command.php(256): Phpactor\Extension\LanguageServer\Command\StartCommand->execute()
#40 /root/phpactor/phpactor/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#41 /root/phpactor/phpactor/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#42 /root/phpactor/phpactor/lib/Application.php(54): Symfony\Component\Console\Application->doRun()
#43 /root/phpactor/phpactor/vendor/symfony/console/Application.php(166): Phpactor\Application->doRun()
#44 /root/phpactor/phpactor/bin/phpactor(42): Symfony\Component\Console\Application->run()
#45 {main}
```

**Comment by dantleech** [comment]
This looks like the only candidate: https://github.com/phpactor/worse-reflection/blob/159d404f2745ae62fe7be575c3c286243d8d07c3/lib/Core/Inference/FrameBuilder/AssertFrameWalker.php#L28

Need to check if the node is NULL before calling `getElements`
