### ISSUE TITLE
Fatal exception when creating a new class in a non-composer mapped directory

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1280]
```
[Error  - 13:13:45] Request workspace/executeCommand failed.
  Message: Exception [RuntimeException] There are no class name candidates
  Code: -32603 
#0 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerCodeTransform/LspCommand/CreateClassCommand.php(67): Phpactor\ClassFileConverter\Domain\ClassNameCandidates->best()
#1 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Command/CommandDispatcher.php(51): Phpactor\Extension\LanguageServerCodeTransform\LspCommand\CreateClassCommand->__invoke()
#2 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Handler/Workspace/CommandHandler.php(40): Phpactor\LanguageServer\Core\Command\CommandDispatcher->dispatch()
#3 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(86): Phpactor\LanguageServer\Handler\Workspace\CommandHandler->executeCommand()
#4 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#5 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#6 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#7 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(102): Amp\call()
#8 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch()
```

Should return an error to the client instead.

**Comment by mamazu** [comment]
Should be fixed. At least the server didn't crash and produce a log entry.

**Comment by mamazu** [comment]
![image](https://github.com/phpactor/phpactor/assets/14860264/e09a9761-731b-4dce-b661-08e51733e0ba)
