### ISSUE TITLE
error executing language-server

### ISSUE THREAD

**Issue by TimB87** [phpactor/phpactor#1315]
Hi!
I am trying to use phpactor together with nvim (native lspconfig) but it seems like I fail to run `phpactor language-server`.

```
$ phpactor language-server -vvv
Starting language server, use -vvv for verbose output
PHP Warning:  Use of undefined constant SIGINT - assumed 'SIGINT' (this will throw an Error in a future version of PHP) in /usr/share/php/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php on line 101
Warning: Use of undefined constant SIGINT - assumed 'SIGINT' (this will throw an Error in a future version of PHP) in /usr/share/php/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php on line 101
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Amp\Loop::onSignal() must be of the type int, string given, called in /usr/share/php/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php on line 104 and defined in /usr/share/php/phpactor/vendor/amphp/amp/lib/Loop.php:241
Stack trace:
#0 /usr/share/php/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(104): Amp\Loop::onSignal()
#1 /usr/share/php/phpactor/vendor/phpactor/language-server-extension/lib/LanguageServer/Command/StartCommand.php(59): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#2 /usr/share/php/phpactor/vendor/symfony/console/Command/Command.php(299): Phpactor\Extension\LanguageServer\Command\StartCommand->execute()
#3 /usr/share/php/phpactor/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run()
#4 /usr/share/php/phpactor/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand()
#5 /usr/share/php/phpactor/lib/Applica in /usr/share/php/phpactor/vendor/amphp/amp/lib/Loop.php on line 241
Fatal error: Uncaught TypeError: Argument 1 passed to Amp\Loop::onSignal() must be of the type int, string given, called in /usr/share/php/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php on line 104 and defined in /usr/share/php/phpactor/vendor/amphp/amp/lib/Loop.php:241
Stack trace:
#0 /usr/share/php/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(104): Amp\Loop::onSignal()
#1 /usr/share/php/phpactor/vendor/phpactor/language-server-extension/lib/LanguageServer/Command/StartCommand.php(59): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#2 /usr/share/php/phpactor/vendor/symfony/console/Command/Command.php(299): Phpactor\Extension\LanguageServer\Command\StartCommand->execute()
#3 /usr/share/php/phpactor/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run()
#4 /usr/share/php/phpactor/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand()
#5 /usr/share/php/phpactor/lib/Applica in /usr/share/php/phpactor/vendor/amphp/amp/lib/Loop.php on line 241
```

System Information as follows:

```
OS: CRUX 3.6.1
php: 7.4.18
composer: version 2.1.5 2021-07-23 10:35:47
```

This happens if i use the latest tagged archive 0.17.1 and also with current master.

I wrote a quick port to install phpactor:
```
# Description: PHP completion, refactoring, introspection tool and language server
# URL: https://github.com/phpactor/phpactor
# Maintainer:
# Depends on: composer

name=phpactor
version=0.17.1
release=1
source=(https://github.com/phpactor/phpactor/archive/$version/$name-$version.tar.gz)

build() {
  cd $name-$version
  #git clone https://github.com/phpactor/phpactor.git $name
  #cd $name

  composer install --no-interaction --no-dev --no-progress --prefer-dist

  mkdir -p $PKG/usr/share/php/$name
  cp -dr --no-preserve=ownership . $PKG/usr/share/php/$name
  mkdir -p $PKG/usr/bin
  ln -s /usr/share/php/phpactor/bin/phpactor $PKG/usr/bin/phpactor
}
```

Many thanks in advance, any hints would be appreciated :-)

Edit: missed maybe the most important command here :)
```
$ phpactor status
Version: "1194ce1 (3 weeks ago) Proofread-lsp-docs-1312
Filesystems: simple, composer
Working directory: /var/www/htdocs

Config files (missing is not bad):

  ✘ /home/tim/.config/phpactor/phpactor.json
  ✘ /home/tim/.config/phpactor/phpactor.yml
  ✘ /var/www/htdocs/.phpactor.json
  ✔ /var/www/htdocs/.phpactor.yml

Diagnostics:

  ✔ Composer detected - Phpactor could work faster without an index
  ✔ XDebug is disabled. XDebug has a negative effect on performance.
  ✘ Git not detected. Some operations which would have been better scoped to your project repository will now include vendor paths.
```

**Comment by dantleech** [comment]
You need the `pnctl` extension, f.e. `apt-get install php-pnctl`

This is a bug, we should either require that extension in `composer.json` or not call these things if the extension is not loaded.

**Comment by TimB87** [comment]
Indeed, I recompiled my php port wit the following configure-option `--enable-pnctl` and it started working! 👍 Thanks!

**Comment by renatosuero** [comment]
hey @TimB87  can you help me?
 I have the SIGINT error like you had, I tried to switch the versions but I still have the issue. I've tested different tag/branch but I still have the same error

```

phpactor (6d400b8) ✗ phpactor language-server -vvv
Starting language server, use -vvv for verbose output
Warning: Use of undefined constant SIGINT - assumed 'SIGINT' (this will throw an Error in a future version of PHP) in /Users/renatosuero/.local/share/nvim/site/pack/packer/start/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php on line 101
Fatal error: Uncaught TypeError: Argument 1 passed to Amp\Loop::onSignal() must be of the type int, string given, called in /Users/renatosuero/.local/share/nvim/site/pack/packer/start/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php on line 104 and defined in /Users/renatosuero/.local/share/nvim/site/pack/packer/start/phpactor/vendor/amphp/amp/lib/Loop.php:241
Stack trace:
#0 /Users/renatosuero/.local/share/nvim/site/pack/packer/start/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(104): Amp\Loop::onSignal('SIGINT', Object(Closure))
#1 /Users/renatosuero/.local/share/nvim/site/pack/packer/start/phpactor/vendor/phpactor/language-server-extension/lib/LanguageServer/Command/StartCommand.php(59%

**Comment by TimB87** [comment]
@renatosuero Hey, I am not sure how I can help, @dantleech gave the perfect fix for me. My php was not compiled with pnctl, I recompiled it with (I THINK) `--enable-pnctl`, I can check for that tomorrow though

**Comment by renatosuero** [comment]
I see, I though it fixed the git issue you had

**Comment by TimB87** [comment]
It did fix the issue.
If you are seeing the same, chances are good (I really am no expert _at all_) that you need to provide pnctl along with php. This depends on which distro you are using here. I compiled php myself, so i added above flag to the configure script.
If  you are using a dabian based distro, the command dantleech posted should work fine.
I have no real clue about other distros, but for reference, I do happen to have a fork of CRUXs official php port over [here](https://github.com/TimB87/crux-ports/blob/master/php/Pkgfile) It's not edited for this particular bug we talk about here (yet) but you would add `--enable-pnctl` around lines 44 to 47 to get what you want.

**Comment by renatosuero** [comment]
I'm using osx, I'll check how to install it and see if it solve my issue. thanks :) 
I'll come back to say if it is solved

**Comment by renatosuero** [comment]
I was using php native on osx, I've installed a new one using brew and it is working :)
