### ISSUE TITLE
[Error] Call to a member function getNameParts() on string

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1326]
```
  Message: Exception [Error] Call to a member function getNameParts() on string
  Code: -32603 
#0 /home/daniel/www/phpactor/phpactor/vendor/phpactor/code-transform/lib/Adapter/WorseReflection/Helper/WorseUnresolvableClassNameFinder.php(71): Phpactor\CodeTransform\Adapter\WorseReflection\Helper\WorseUnresolvableClassNameFinder->appendUnresolvedName()
#1 /home/daniel/www/phpactor/phpactor/vendor/phpactor/code-transform/lib/Adapter/WorseReflection/Helper/WorseUnresolvableClassNameFinder.php(50): Phpactor\CodeTransform\Adapter\WorseReflection\Helper\WorseUnresolvableClassNameFinder->filterResolvedNames()

```

**Comment by BladeMF** [comment]
That's the cause - #1286 .

**Comment by dantleech** [comment]
Thanks for the tip, fixed in https://github.com/phpactor/code-transform/commit/f461294d4d7e69ca93367ea0893082068532d950
