### ISSUE TITLE
Can I disable exceptions in the output of the language server

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1363]
They are driving me nuts. VS Code keeps notifying me about every single one of them.

**Comment by dantleech** [comment]
For example?

**Comment by BladeMF** [comment]
There are quite a few of them. This is the most recent one of them:
```
[Error - 11:41:11 AM] Request textDocument/codeAction failed.
  Message: Exception [DTL\Invoke\Exception\InvalidParameterType] Argument "character" has type "int" but was passed "double" for "Phpactor\LanguageServerProtocol\Position#__construct"
  Code: -32603 
#0 /root/.shared_extensions/phpactor/phpactor/vendor/dantleech/invoke/src/Invoke.php(120): DTL\Invoke\Internal\ArgumentAssert::types(Object(DTL\Invoke\Internal\ResolvedArguments), Object(DTL\Invoke\Internal\Parameters))
#1 /root/.shared_extensions/phpactor/phpactor/vendor/dantleech/invoke/src/Invoke.php(79): DTL\Invoke\Invoke->instantiate(Object(ReflectionClass), '__construct', Array, Object(Closure))
#2 /root/.shared_extensions/phpactor/phpactor/vendor/dantleech/invoke/src/Invoke.php(43): DTL\Invoke\Invoke->doInstantiate('Phpactor\\Langua...', Array)
#3 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server-protocol/src/Position.php(104): DTL\Invoke\Invoke::new('Phpactor\\Langua...', Array)
#4 [internal function]: Phpactor\LanguageServerProtocol\Position::fromArray(Array, true)
#5 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server-protocol/src/Range.php(112): call_user_func_array('Phpactor\\Langua...', Array)
#6 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server-protocol/src/Range.php(96): Phpactor\LanguageServerProtocol\Range::invokeFromNames(Array, Array, true)
#7 [internal function]: Phpactor\LanguageServerProtocol\Range::fromArray(Array, true)
#8 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server-protocol/src/Diagnostic.php(157): call_user_func_array('Phpactor\\Langua...', Array)
#9 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server-protocol/src/Diagnostic.php(141): Phpactor\LanguageServerProtocol\Diagnostic::invokeFromNames(Array, Array, true)
#10 [internal function]: Phpactor\LanguageServerProtocol\Diagnostic::fromArray(Array, true)
#11 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server-protocol/src/CodeActionContext.php(110): call_user_func_array('Phpactor\\Langua...', Array)
#12 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server-protocol/src/CodeActionContext.php(88): Phpactor\LanguageServerProtocol\CodeActionContext::invokeFromNames(Array, Array, true)
#13 [internal function]: Phpactor\LanguageServerProtocol\CodeActionContext::Phpactor\LanguageServerProtocol\{closure}(Array)
#14 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server-protocol/src/CodeActionContext.php(83): array_map(Object(Closure), Array)
#15 [internal function]: Phpactor\LanguageServerProtocol\CodeActionContext::fromArray(Array, true)
#16 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server-protocol/src/CodeActionParams.php(135): call_user_func_array('Phpactor\\Langua...', Array)
#17 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server-protocol/src/CodeActionParams.php(119): Phpactor\LanguageServerProtocol\CodeActionParams::invokeFromNames(Array, Array, true)
#18 [internal function]: Phpactor\LanguageServerProtocol\CodeActionParams::fromArray(Array, true)
#19 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/ArgumentResolver/LanguageSeverProtocolParamsResolver.php(68): ReflectionMethod->invoke(NULL, Array, true)
#20 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/ArgumentResolver/LanguageSeverProtocolParamsResolver.php(42): Phpactor\LanguageServer\Core\Dispatcher\ArgumentResolver\LanguageSeverProtocolParamsResolver->doResolveArguments('Phpactor\\Langua...', 'params', Array)
#21 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/ArgumentResolver/ChainArgumentResolver.php(28): Phpactor\LanguageServer\Core\Dispatcher\ArgumentResolver\LanguageSeverProtocolParamsResolver->resolveArguments(Object(Phpactor\LanguageServer\Handler\TextDocument\CodeActionHandler), 'codeAction', Array)
#22 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(83): Phpactor\LanguageServer\Core\Dispatcher\ArgumentResolver\ChainArgumentResolver->resolveArguments(Object(Phpactor\LanguageServer\Handler\TextDocument\CodeActionHandler), 'codeAction', Array)
#23 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#24 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#25 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#26 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(102): Amp\call(Object(Closure))
#27 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#28 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\HandlerMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#29 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(35): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#30 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#31 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(37): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#32 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#33 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#34 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#35 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#36 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#37 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(39): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#38 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#39 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#40 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#41 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(64): Amp\call(Object(Closure))
#42 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#43 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#44 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(223): Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher->dispatch(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#45 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#46 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#47 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#48 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(121): Amp\call(Object(Closure))
#49 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(240): Amp\asyncCall(Object(Closure))
#50 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(214): Phpactor\LanguageServer\Core\Server\LanguageServer->dispatchRequest(Object(Phpactor\LanguageServer\Core\Server\Transmitter\ConnectionMessageTransmitter), Object(Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher), Object(Phpactor\LanguageServer\Core\Server\StreamProvider\Connection), Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#51 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#52 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#53 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#54 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve(Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#55 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, 'Content-Length:...')
#56 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve('Content-Length:...')
#57 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve('Content-Length:...')
#58 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(321): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('a', Resource id #1, NULL)
#59 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams(Array, Array, -0.001)
#60 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch(true)
#61 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#62 /root/.shared_extensions/phpactor/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#63 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(113): Amp\Loop::run(Object(Closure))
#64 /root/.shared_extensions/phpactor/phpactor/vendor/phpactor/language-server-extension/lib/LanguageServer/Command/StartCommand.php(59): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#65 /root/.shared_extensions/phpactor/phpactor/vendor/symfony/console/Command/Command.php(299): Phpactor\Extension\LanguageServer\Command\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#66 /root/.shared_extensions/phpactor/phpactor/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#67 /root/.shared_extensions/phpactor/phpactor/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand(Object(Phpactor\Extension\LanguageServer\Command\StartCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#68 /root/.shared_extensions/phpactor/phpactor/lib/Application.php(54): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#69 /root/.shared_extensions/phpactor/phpactor/vendor/symfony/console/Application.php(167): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#70 /root/.shared_extensions/phpactor/phpactor/bin/phpactor(42): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#71 {main}
```

My point is, I know we need to fix them, but until we do, I would _really_ like to disable outputing them.

**Comment by dantleech** [comment]
This should be client side really. It _is_ an error, the client would be expecting a response and we wouldn't provide one, so it would error anyway.

In CoC you have the option to not pop-up the error window on every error. But all you can do by turning "off" errors on server side is to start getting errors on the client side instead,

**Comment by dantleech** [comment]
If all the errors are as above I recommend us to fix that

**Comment by BladeMF** [comment]
I am inclined to agree, but still had to check.
