### ISSUE TITLE
[WR] Symbol Factory regression

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#146]
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Phpactor\WorseReflection\Core\Reflection\Inference\SymbolFa
ctory::name() must be an instance of Microsoft\PhpParser\Token, instance of Microsoft\PhpParser\Node\Expression\Variable given, called in /home/daniel/www/phpactor/phpactor/v
endor/phpactor/worse-reflection/lib/Core/Reflection/Inference/SymbolFactory.php on line 18 in /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Ref
lection/Inference/SymbolFactory.php:56
Stack trace:
#0 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflection/Inference/SymbolFactory.php(18): Phpactor\WorseReflection\Core\Reflection\Inference
\SymbolFactory->name(Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression), Object(Microsoft\PhpParser\Node\Expression\Variable))
#1 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflection/Inference/SymbolFactory.php(36): Phpactor\WorseReflection\Core in /home/daniel/www/
phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflection/Inference/SymbolFactory.php on line 56
```

**Comment by dantleech** [comment]
Temporary fix implemented, review.

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/worse-reflection/commit/62c14f8413be825dac87b2b957638d4ba621f3e6
