### ISSUE TITLE
[WR] Out of bounds offset bug

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#148]
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Phpactor\WorseReflection\Core\Reflection\Inference\FrameBui
lder::buildFromNode() must be an instance of Microsoft\PhpParser\Node, null given, called in /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/Refle
ction/Inference/FrameBuilder.php on line 49 in /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflection/Inference/FrameBuilder.php:52
Stack trace:
#0 /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflection/Inference/FrameBuilder.php(49): Phpactor\WorseReflection\Core\Reflection\Inference\F
rameBuilder->buildFromNode(NULL)
#1 /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Reflector.php(93): Phpactor\WorseReflection\Core\Reflection\Inference\FrameBuilder->buildForNode(Obj
ect(Microsoft\PhpParser\Node\SourceFileNode))
#2 /home/daniel/.vim/bundle/phpactor/lib/Application/FileInfoAtOffset.php(45): Phpactor\Wo in /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/Refl
```

**Comment by dantleech** [comment]
Hmm. this really shouldn't happen

```
        $scopeNode = $node->getFirstAncestor(FunctionLike::class, SourceFileNode::class);
```

`SourceFileNode` should alays be returned, unless there is no PHP tag perhaps.

**Comment by dantleech** [comment]
Closing until reproduced.

**Comment by dantleech** [comment]
This can be reproduced when an out-of-bounds offset is given, or theoretically if the given node IS the SourceFileNode (or a FunctionLike node).

**Comment by dantleech** [comment]
Assuming fixed, havn't seen it in months.
