### ISSUE TITLE
Error on hover in LSP

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1728]
I am getting this:

```
[Error - 5:32:14 AM] Request textDocument/hover failed.
  Message: Exception [Twig\Error\RuntimeError] Neither the property "inferredTypes" nor one of the methods "inferredTypes()", "getinferredTypes()"/"isinferredTypes()"/"hasinferredTypes()" or "__call()" exist and have public access in class "Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionMethod". at /root/.personal/MarsIPM-Dev/.phpactor/templates/markdown/Phpactor/WorseReflection/Core/Reflection/ReflectionMethod.twig#17
  Code: -32603 
#0 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Environment.php(418) : eval()'d code(88): twig_get_attribute(Object(Twig\Environment), Object(Twig\Source), Object(Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionMethod), 'inferredTypes', Array, 'any', false, false, false, 17)
#1 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(405): __TwigTemplate_ce71e633423bd53901be6e329db4be6d->doDisplay(Array, Array)
#2 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#3 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#4 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#5 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#6 /root/.shared_extensions/phpactor2/vendor/dantleech/object-renderer/lib/Adapter/Twig/TwigObjectRenderer.php(39): Twig\Environment->render('Phpactor/WorseR...', Array)
#7 /root/.shared_extensions/phpactor2/vendor/dantleech/object-renderer/lib/Adapter/Twig/Extension/ObjectRendererExtension.php(29): Phpactor\ObjectRenderer\Adapter\Twig\TwigObjectRenderer->render(Object(Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionMethod))
#8 [internal function]: Phpactor\ObjectRenderer\Adapter\Twig\Extension\ObjectRendererExtension->Phpactor\ObjectRenderer\Adapter\Twig\Extension\{closure}(Object(Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionMethod))
#9 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Environment.php(418) : eval()'d code(96): call_user_func_array(Object(Closure), Array)
#10 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(405): __TwigTemplate_5ba8544fcc0cda777ab6ad2e4fefde0c->doDisplay(Array, Array)
#11 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#13 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#14 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#15 /root/.shared_extensions/phpactor2/vendor/dantleech/object-renderer/lib/Adapter/Twig/TwigObjectRenderer.php(39): Twig\Environment->render('Phpactor/WorseR...', Array)
#16 /root/.shared_extensions/phpactor2/vendor/dantleech/object-renderer/lib/Adapter/Twig/Extension/ObjectRendererExtension.php(29): Phpactor\ObjectRenderer\Adapter\Twig\TwigObjectRenderer->render(Object(Phpactor\WorseReflection\Core\Virtual\VirtualReflectionClassDecorator))
#17 [internal function]: Phpactor\ObjectRenderer\Adapter\Twig\Extension\ObjectRendererExtension->Phpactor\ObjectRenderer\Adapter\Twig\Extension\{closure}(Object(Phpactor\WorseReflection\Core\Virtual\VirtualReflectionClassDecorator))
#18 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Environment.php(418) : eval()'d code(132): call_user_func_array(Object(Closure), Array)
#19 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(405): __TwigTemplate_9798439c15a517e9014bb0b8bf91bd4b->doDisplay(Array, Array)
#20 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#22 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#23 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#24 /root/.shared_extensions/phpactor2/vendor/dantleech/object-renderer/lib/Adapter/Twig/TwigObjectRenderer.php(39): Twig\Environment->render('Phpactor/Extens...', Array)
#25 /root/.shared_extensions/phpactor2/vendor/dantleech/object-renderer/lib/Model/ObjectRenderer/TolerantObjectRenderer.php(31): Phpactor\ObjectRenderer\Adapter\Twig\TwigObjectRenderer->render(Object(Phpactor\Extension\LanguageServerHover\Renderer\HoverInformation))
#26 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerHover/Handler/HoverHandler.php(199): Phpactor\ObjectRenderer\Model\ObjectRenderer\TolerantObjectRenderer->render(Object(Phpactor\Extension\LanguageServerHover\Renderer\HoverInformation))
#27 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerHover/Handler/HoverHandler.php(125): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->renderClass(Object(Phpactor\WorseReflection\Core\Type\ReflectedClassType))
#28 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerHover/Handler/HoverHandler.php(110): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->renderSymbolContext(Object(Phpactor\WorseReflection\Core\Inference\NodeContext))
#29 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerHover/Handler/HoverHandler.php(100): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->infoFromSymbolContext(Object(Phpactor\WorseReflection\Core\Inference\NodeContext))
#30 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerHover/Handler/HoverHandler.php(74): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->infoFromReflecionOffset(Object(Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionOffset))
#31 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(90): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->Phpactor\Extension\LanguageServerHover\Handler\{closure}()
#32 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerHover/Handler/HoverHandler.php(88): Amp\call(Object(Closure))
#33 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(86): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->hover(Object(Phpactor\LanguageServerProtocol\TextDocumentIdentifier), Object(Phpactor\LanguageServerProtocol\Position), Object(Amp\CancellationToken@anonymous))
#34 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#35 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#36 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#37 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(102): Amp\call(Object(Closure))
#38 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#39 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\HandlerMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#40 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(35): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#41 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#42 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(37): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#43 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#44 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#45 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#46 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ShutdownMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#47 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ShutdownMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#48 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#49 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#50 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(39): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#51 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#52 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#53 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#54 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(64): Amp\call(Object(Closure))
#55 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#56 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#57 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(221): Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher->dispatch(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#58 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#59 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#60 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#61 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(121): Amp\call(Object(Closure))
#62 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(238): Amp\asyncCall(Object(Closure))
#63 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(212): Phpactor\LanguageServer\Core\Server\LanguageServer->dispatchRequest(Object(Phpactor\LanguageServer\Core\Server\Transmitter\ConnectionMessageTransmitter), Object(Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher), Object(Phpactor\LanguageServer\Core\Server\StreamProvider\Connection), Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#64 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#65 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#66 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#67 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve(Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#68 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, 'Content-Length:...')
#69 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve('Content-Length:...')
#70 /root/.shared_extensions/phpactor2/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve('Content-Length:...')
#71 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('a', Resource id #1, NULL)
#72 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams(Array, Array, 0.001)
#73 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch(true)
#74 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#75 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#76 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(112): Amp\Loop::run(Object(Closure))
#77 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServer/Command/StartCommand.php(54): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#78 /root/.shared_extensions/phpactor2/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\LanguageServer\Command\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#79 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(1015): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#80 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Phpactor\Extension\LanguageServer\Command\StartCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#81 /root/.shared_extensions/phpactor2/lib/Application.php(48): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#82 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#83 /root/.shared_extensions/phpactor2/bin/phpactor(47): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#84 {main}
```

**Comment by BladeMF** [comment]
Sorry, that's actually my bad. I have custom templates, sorry.
