### ISSUE TITLE
Hovering over `$this->prophesize()` produces error

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1732]
I don't think it's related to traits in general, tried to reproduce it with a trait and it didn't occur. But I've tried several `$this->prophesize()` methods and they all trigger the error:
```
[Error - 10:54:37 AM] Request textDocument/hover failed.
  Message: Exception [Twig\Error\RuntimeError] Neither the property "parent" nor one of the methods "parent()", "getparent()"/"isparent()"/"hasparent()" or "__call()" exist and have public access in class "Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionTrait". at /root/.shared_extensions/phpactor2/templates/help/markdown/Phpactor/WorseReflection/Core/Reflection/ReflectionMethod.twig#5
  Code: -32603 
#0 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Environment.php(418) : eval()'d code(50): twig_get_attribute(Object(Twig\Environment), Object(Twig\Source), Object(Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionTrait), 'parent', Array, 'any', false, false, false, 5)
#1 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(405): __TwigTemplate_834b4b6859dc9ad05ddc653b5547f313->doDisplay(Array, Array)
#2 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#3 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#4 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#5 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#6 /root/.shared_extensions/phpactor2/vendor/dantleech/object-renderer/lib/Adapter/Twig/TwigObjectRenderer.php(39): Twig\Environment->render('Phpactor/WorseR...', Array)
#7 /root/.shared_extensions/phpactor2/vendor/dantleech/object-renderer/lib/Adapter/Twig/Extension/ObjectRendererExtension.php(29): Phpactor\ObjectRenderer\Adapter\Twig\TwigObjectRenderer->render(Object(Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionMethod))
#8 [internal function]: Phpactor\ObjectRenderer\Adapter\Twig\Extension\ObjectRendererExtension->Phpactor\ObjectRenderer\Adapter\Twig\Extension\{closure}(Object(Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionMethod))
#9 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Environment.php(418) : eval()'d code(56): call_user_func_array(Object(Closure), Array)
#10 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(405): __TwigTemplate_a80297b0e766d468300b135dbc5400a0->doDisplay(Array, Array)
#11 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#13 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#14 /root/.shared_extensions/phpactor2/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#15 /root/.shared_extensions/phpactor2/vendor/dantleech/object-renderer/lib/Adapter/Twig/TwigObjectRenderer.php(39): Twig\Environment->render('Phpactor/Extens...', Array)
#16 /root/.shared_extensions/phpactor2/vendor/dantleech/object-renderer/lib/Model/ObjectRenderer/TolerantObjectRenderer.php(31): Phpactor\ObjectRenderer\Adapter\Twig\TwigObjectRenderer->render(Object(Phpactor\Extension\LanguageServerHover\Renderer\HoverInformation))
#17 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerHover/Handler/HoverHandler.php(168): Phpactor\ObjectRenderer\Model\ObjectRenderer\TolerantObjectRenderer->render(Object(Phpactor\Extension\LanguageServerHover\Renderer\HoverInformation))
#18 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerHover/Handler/HoverHandler.php(123): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->renderMember(Object(Phpactor\WorseReflection\Core\Inference\NodeContext))
#19 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerHover/Handler/HoverHandler.php(110): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->renderSymbolContext(Object(Phpactor\WorseReflection\Core\Inference\NodeContext))
#20 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerHover/Handler/HoverHandler.php(100): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->infoFromSymbolContext(Object(Phpactor\WorseReflection\Core\Inference\NodeContext))
#21 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerHover/Handler/HoverHandler.php(74): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->infoFromReflecionOffset(Object(Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionOffset))
#22 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(90): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->Phpactor\Extension\LanguageServerHover\Handler\{closure}()
#23 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerHover/Handler/HoverHandler.php(88): Amp\call(Object(Closure))
#24 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(86): Phpactor\Extension\LanguageServerHover\Handler\HoverHandler->hover(Object(Phpactor\LanguageServerProtocol\TextDocumentIdentifier), Object(Phpactor\LanguageServerProtocol\Position), Object(Amp\CancellationToken@anonymous))
#25 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#26 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#27 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#28 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(102): Amp\call(Object(Closure))
#29 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#30 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\HandlerMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#31 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(35): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#32 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#33 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(37): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#34 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#35 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#36 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#37 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ShutdownMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#38 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ShutdownMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#39 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#40 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#41 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(39): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#42 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#43 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#44 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#45 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(64): Amp\call(Object(Closure))
#46 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#47 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#48 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(221): Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher->dispatch(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#49 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#50 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#51 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#52 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(121): Amp\call(Object(Closure))
#53 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(238): Amp\asyncCall(Object(Closure))
#54 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(212): Phpactor\LanguageServer\Core\Server\LanguageServer->dispatchRequest(Object(Phpactor\LanguageServer\Core\Server\Transmitter\ConnectionMessageTransmitter), Object(Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher), Object(Phpactor\LanguageServer\Core\Server\StreamProvider\Connection), Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#55 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#56 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#57 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#58 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve(Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#59 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, 'Content-Length:...')
#60 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve('Content-Length:...')
#61 /root/.shared_extensions/phpactor2/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve('Content-Length:...')
#62 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('a', Resource id #1, NULL)
#63 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams(Array, Array, 0.1)
#64 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch(true)
#65 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#66 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#67 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(112): Amp\Loop::run(Object(Closure))
#68 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServer/Command/StartCommand.php(54): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#69 /root/.shared_extensions/phpactor2/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\LanguageServer\Command\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#70 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(1015): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#71 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Phpactor\Extension\LanguageServer\Command\StartCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#72 /root/.shared_extensions/phpactor2/lib/Application.php(48): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#73 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#74 /root/.shared_extensions/phpactor2/bin/phpactor(47): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#75 {main}

```

**Comment by dantleech** [comment]
should be fixed in #1740
