### ISSUE TITLE
Exception when selected commented out code

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1778]
When selecting commented out code an error is produced. In my case the code was:
```php
// if (count($values) == 0) {
```
The exception is:
```
  Message: Exception [AssertionError] assert($startNode instanceof Node) at /root/.shared_extensions/phpactor2/lib/CodeTransform/Adapter/WorseReflection/Refactor/WorseExtractMethod.php#102
  Code: -32603 
#0 /root/.shared_extensions/phpactor2/lib/CodeTransform/Adapter/WorseReflection/Refactor/WorseExtractMethod.php(102): assert(false, 'assert($startNo...')
#1 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerCodeTransform/CodeAction/ExtractMethodProvider.php(43): Phpactor\CodeTransform\Adapter\WorseReflection\Refactor\WorseExtractMethod->canExtractMethod(Object(Phpactor\CodeTransform\Domain\SourceCode), 9380, 9409)
#2 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(90): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\ExtractMethodProvider->Phpactor\Extension\LanguageServerCodeTransform\CodeAction\{closure}()
#3 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerCodeTransform/CodeAction/ExtractMethodProvider.php(64): Amp\call(Object(Closure))
#4 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/CodeAction/AggregateCodeActionProvider.php(32): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\ExtractMethodProvider->provideActionsFor(Object(Phpactor\LanguageServerProtocol\TextDocumentItem), Object(Phpactor\LanguageServerProtocol\Range), Object(Amp\CancellationToken@anonymous))
#5 [internal function]: Phpactor\LanguageServer\Core\CodeAction\AggregateCodeActionProvider->Phpactor\LanguageServer\Core\CodeAction\{closure}()
#6 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(NULL)
#7 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, NULL)
#8 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Delayed.php(26): Amp\Delayed->resolve(NULL)
#9 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/NativeDriver.php(142): Amp\Delayed->Amp\{closure}('drwm', NULL)
#10 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch(true)
#11 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#12 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#13 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(112): Amp\Loop::run(Object(Closure))
#14 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServer/Command/StartCommand.php(54): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#15 /root/.shared_extensions/phpactor2/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\LanguageServer\Command\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Phpactor\Extension\LanguageServer\Command\StartCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /root/.shared_extensions/phpactor2/lib/Application.php(48): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /root/.shared_extensions/phpactor2/bin/phpactor(47): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main}
```

**Comment by dantleech** [comment]
looks like `assert($noe instanceof Node` woul dbe better as `if (!$node instanceof Node) { continue; }` or whatever
