### ISSUE TITLE
Renaming a class to Use make LSP crash

### ISSUE THREAD

**Issue by innocenzi** [phpactor/phpactor#1789]
https://share.cleanshot.com/NZSuAB

In a fresh Laravel project, I wanted to try out the refactor tools, so I renamed the `App\Models\User` class to `Use` and the LSP crashed and the output window opened up.

I'm not sure what causes the crash since renaming the class to something else does not trigger the error.

```
[Error - 10:18:22 AM] Request textDocument/codeAction failed.
  Message: Exception [Error] Call to a member function getValues() on null at /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/WorseReflection/Core/Reflection/Collection/ReflectionTraitCollection.php#27
  Code: -32603 
#0 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/WorseReflection/Bridge/TolerantParser/Reflection/ReflectionClass.php(263): Phpactor\WorseReflection\Core\Reflection\Collection\ReflectionTraitCollection::fromClassDeclaration(Object(Phpactor\WorseReflection\Core\ServiceLocator), Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#1 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/WorseReflection/Bridge/TolerantParser/Reflection/ReflectionClass.php(205): Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass->traits()
#2 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/WorseReflection/Core/Virtual/VirtualReflectionClassDecorator.php(80): Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass->methods(Object(Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass))
#3 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/CodeTransform/Adapter/WorseReflection/Transformer/CompleteConstructor.php(126): Phpactor\WorseReflection\Core\Virtual\VirtualReflectionClassDecorator->methods()
#4 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/CodeTransform/Adapter/WorseReflection/Transformer/CompleteConstructor.php(84): Phpactor\CodeTransform\Adapter\WorseReflection\Transformer\CompleteConstructor->candidateClasses(Object(Phpactor\CodeTransform\Domain\SourceCode))
#5 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/Extension/LanguageServerCodeTransform/CodeAction/TransformerCodeActionPovider.php(95): Phpactor\CodeTransform\Adapter\WorseReflection\Transformer\CompleteConstructor->diagnostics(Object(Phpactor\CodeTransform\Domain\SourceCode))
#6 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/Extension/LanguageServerCodeTransform/CodeAction/TransformerCodeActionPovider.php(54): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\TransformerCodeActionPovider->getDiagnostics(Object(Phpactor\LanguageServerProtocol\TextDocumentItem))
#7 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/functions.php(90): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\TransformerCodeActionPovider->Phpactor\Extension\LanguageServerCodeTransform\CodeAction\{closure}()
#8 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/Extension/LanguageServerCodeTransform/CodeAction/TransformerCodeActionPovider.php(74): Amp\call(Object(Closure))
#9 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/phpactor/language-server/lib/Core/CodeAction/AggregateCodeActionProvider.php(32): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\TransformerCodeActionPovider->provideActionsFor(Object(Phpactor\LanguageServerProtocol\TextDocumentItem), Object(Phpactor\LanguageServerProtocol\Range), Object(Amp\CancellationToken@anonymous))
#10 [internal function]: Phpactor\LanguageServer\Core\CodeAction\AggregateCodeActionProvider->Phpactor\LanguageServer\Core\CodeAction\{closure}()
#11 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(NULL)
#12 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, NULL)
#13 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/Delayed.php(26): Amp\Delayed->resolve(NULL)
#14 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(142): Amp\Delayed->Amp\{closure}('fnf', NULL)
#15 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch(true)
#16 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#17 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#18 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(112): Amp\Loop::run(Object(Closure))
#19 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/Extension/LanguageServer/Command/StartCommand.php(54): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#20 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\LanguageServer\Command\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Phpactor\Extension\LanguageServer\Command\StartCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/Application.php(48): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/bin/phpactor(47): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 {main}
[Error - 10:18:23 AM] Request textDocument/codeAction failed.
  Message: Exception [Error] Call to a member function getValues() on null at /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/WorseReflection/Core/Reflection/Collection/ReflectionTraitCollection.php#27
  Code: -32603 
#0 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/WorseReflection/Bridge/TolerantParser/Reflection/ReflectionClass.php(263): Phpactor\WorseReflection\Core\Reflection\Collection\ReflectionTraitCollection::fromClassDeclaration(Object(Phpactor\WorseReflection\Core\ServiceLocator), Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#1 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/WorseReflection/Bridge/TolerantParser/Reflection/ReflectionClass.php(205): Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass->traits()
#2 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/WorseReflection/Core/Virtual/VirtualReflectionClassDecorator.php(80): Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass->methods(Object(Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass))
#3 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/CodeTransform/Adapter/WorseReflection/Transformer/CompleteConstructor.php(126): Phpactor\WorseReflection\Core\Virtual\VirtualReflectionClassDecorator->methods()
#4 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/CodeTransform/Adapter/WorseReflection/Transformer/CompleteConstructor.php(84): Phpactor\CodeTransform\Adapter\WorseReflection\Transformer\CompleteConstructor->candidateClasses(Object(Phpactor\CodeTransform\Domain\SourceCode))
#5 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/Extension/LanguageServerCodeTransform/CodeAction/TransformerCodeActionPovider.php(95): Phpactor\CodeTransform\Adapter\WorseReflection\Transformer\CompleteConstructor->diagnostics(Object(Phpactor\CodeTransform\Domain\SourceCode))
#6 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/Extension/LanguageServerCodeTransform/CodeAction/TransformerCodeActionPovider.php(54): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\TransformerCodeActionPovider->getDiagnostics(Object(Phpactor\LanguageServerProtocol\TextDocumentItem))
#7 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/functions.php(90): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\TransformerCodeActionPovider->Phpactor\Extension\LanguageServerCodeTransform\CodeAction\{closure}()
#8 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/Extension/LanguageServerCodeTransform/CodeAction/TransformerCodeActionPovider.php(74): Amp\call(Object(Closure))
#9 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/phpactor/language-server/lib/Core/CodeAction/AggregateCodeActionProvider.php(32): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\TransformerCodeActionPovider->provideActionsFor(Object(Phpactor\LanguageServerProtocol\TextDocumentItem), Object(Phpactor\LanguageServerProtocol\Range), Object(Amp\CancellationToken@anonymous))
#10 [internal function]: Phpactor\LanguageServer\Core\CodeAction\AggregateCodeActionProvider->Phpactor\LanguageServer\Core\CodeAction\{closure}()
#11 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(NULL)
#12 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, NULL)
#13 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/Delayed.php(26): Amp\Delayed->resolve(NULL)
#14 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(142): Amp\Delayed->Amp\{closure}('fnw', NULL)
#15 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch(true)
#16 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#17 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#18 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(112): Amp\Loop::run(Object(Closure))
#19 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/Extension/LanguageServer/Command/StartCommand.php(54): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#20 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\LanguageServer\Command\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Phpactor\Extension\LanguageServer\Command\StartCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/Application.php(48): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/bin/phpactor(47): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 {main}
```

**Comment by dantleech** [comment]
`use` is a reserved word, so you can't name a class "use":

![image](https://user-images.githubusercontent.com/530801/179390714-812c5ee2-cd36-4887-913c-9f8bfe242812.png)


this is a bug in Phpactor though we should check to see if `traitNameList` is NULL here:

https://github.com/phpactor/phpactor/blob/4c590941966874026abc6b33db72f488b7386875/lib/WorseReflection/Core/Reflection/Collection/ReflectionTraitCollection.php#L29
