### ISSUE TITLE
Error when typing

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1812]
On this line:
```php
[
     ".class" => $isComplete ? "section complete" :<>
]
```
the following error is produced:
```
[Error - 9:25:28 AM] Request textDocument/codeAction failed.
  Message: Exception [TypeError] Illegal offset type at /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/Resolver/ArrayCreationExpressionResolver.php#38
  Code: -32603 
#0 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(113): Phpactor\WorseReflection\Core\Inference\Resolver\ArrayCreationExpressionResolver->resolve(Object(Phpactor\WorseReflection\Core\Inference\NodeContextResolver), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArrayCreationExpression))
#1 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(101): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArrayCreationExpression))
#2 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Cache/StaticCache.php(23): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->Phpactor\WorseReflection\Core\Inference\{closure}()
#3 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(105): Phpactor\WorseReflection\Core\Cache\StaticCache->getOrSet('sc:527656:32-15...', Object(Closure))
#4 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(59): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNodeWithCache(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArrayCreationExpression))
#5 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/Resolver/ArrayCreationExpressionResolver.php(35): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArrayCreationExpression))
#6 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(113): Phpactor\WorseReflection\Core\Inference\Resolver\ArrayCreationExpressionResolver->resolve(Object(Phpactor\WorseReflection\Core\Inference\NodeContextResolver), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArrayCreationExpression))
#7 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(101): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArrayCreationExpression))
#8 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Cache/StaticCache.php(23): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->Phpactor\WorseReflection\Core\Inference\{closure}()
#9 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(105): Phpactor\WorseReflection\Core\Cache\StaticCache->getOrSet('sc:216953:30-15...', Object(Closure))
#10 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(59): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNodeWithCache(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArrayCreationExpression))
#11 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/Resolver/TernaryExpressionResolver.php(28): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArrayCreationExpression))
#12 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(113): Phpactor\WorseReflection\Core\Inference\Resolver\TernaryExpressionResolver->resolve(Object(Phpactor\WorseReflection\Core\Inference\NodeContextResolver), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\TernaryExpression))
#13 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(101): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\TernaryExpression))
#14 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Cache/StaticCache.php(23): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->Phpactor\WorseReflection\Core\Inference\{closure}()
#15 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(105): Phpactor\WorseReflection\Core\Cache\StaticCache->getOrSet('sc:460138:29-15...', Object(Closure))
#16 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(59): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNodeWithCache(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\TernaryExpression))
#17 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/Resolver/ArgumentExpressionResolver.php(17): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\TernaryExpression))
#18 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(113): Phpactor\WorseReflection\Core\Inference\Resolver\ArgumentExpressionResolver->resolve(Object(Phpactor\WorseReflection\Core\Inference\NodeContextResolver), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArgumentExpression))
#19 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(101): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArgumentExpression))
#20 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Cache/StaticCache.php(23): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->Phpactor\WorseReflection\Core\Inference\{closure}()
#21 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(105): Phpactor\WorseReflection\Core\Cache\StaticCache->getOrSet('sc:208255:29-15...', Object(Closure))
#22 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(59): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNodeWithCache(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArgumentExpression))
#23 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FunctionArguments.php(57): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArgumentExpression))
#24 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FunctionStub/ArrayMergeStub.php(24): Phpactor\WorseReflection\Core\Inference\FunctionArguments->getIterator()
#25 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/Resolver/QualifiedNameResolver.php(69): Phpactor\WorseReflection\Core\Inference\FunctionStub\ArrayMergeStub->resolve(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Phpactor\WorseReflection\Core\Inference\NodeContext), Object(Phpactor\WorseReflection\Core\Inference\FunctionArguments))
#26 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(113): Phpactor\WorseReflection\Core\Inference\Resolver\QualifiedNameResolver->resolve(Object(Phpactor\WorseReflection\Core\Inference\NodeContextResolver), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\QualifiedName))
#27 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(101): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\QualifiedName))
#28 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Cache/StaticCache.php(23): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->Phpactor\WorseReflection\Core\Inference\{closure}()
#29 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(105): Phpactor\WorseReflection\Core\Cache\StaticCache->getOrSet('sc:613710:27-15...', Object(Closure))
#30 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(59): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNodeWithCache(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\QualifiedName))
#31 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/Resolver/CallExpressionResolver.php(29): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\QualifiedName))
#32 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(113): Phpactor\WorseReflection\Core\Inference\Resolver\CallExpressionResolver->resolve(Object(Phpactor\WorseReflection\Core\Inference\NodeContextResolver), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\CallExpression))
#33 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(101): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\CallExpression))
#34 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Cache/StaticCache.php(23): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->Phpactor\WorseReflection\Core\Inference\{closure}()
#35 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(105): Phpactor\WorseReflection\Core\Cache\StaticCache->getOrSet('sc:25197:27-15-...', Object(Closure))
#36 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(59): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNodeWithCache(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\CallExpression))
#37 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(79): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\CallExpression))
#38 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/Walker/PassThroughWalker.php(42): Phpactor\WorseReflection\Core\Inference\FrameResolver->resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\CallExpression))
#39 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(107): Phpactor\WorseReflection\Core\Inference\Walker\PassThroughWalker->enter(Object(Phpactor\WorseReflection\Core\Inference\FrameResolver), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\CallExpression))
#40 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\Expression\CallExpression), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#41 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\Expression\ArgumentExpression), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#42 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\DelimitedList\ArgumentExpressionList), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#43 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\Expression\CallExpression), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#44 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#45 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\Statement\CompoundStatementNode), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#46 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\MethodDeclaration), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#47 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\ClassMembersNode), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#48 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#49 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(71): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Microsoft\PhpParser\Node\SourceFileNode))
#50 /root/.shared_extensions/phpactor2/lib/WorseReflection/Bridge/TolerantParser/Reflector/TolerantSourceCodeReflector.php(70): Phpactor\WorseReflection\Core\Inference\FrameResolver->build(Object(Microsoft\PhpParser\Node\SourceFileNode))
#51 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Cache/TtlCache.php(50): Phpactor\WorseReflection\Bridge\TolerantParser\Reflector\TolerantSourceCodeReflector->Phpactor\WorseReflection\Bridge\TolerantParser\Reflector\{closure}()
#52 /root/.shared_extensions/phpactor2/lib/WorseReflection/Bridge/TolerantParser/Reflector/TolerantSourceCodeReflector.php(72): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet('diagnoistics__<...', Object(Closure))
#53 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Reflector/CompositeReflector.php(106): Phpactor\WorseReflection\Bridge\TolerantParser\Reflector\TolerantSourceCodeReflector->diagnostics(Object(Phpactor\WorseReflection\Core\SourceCode))
#54 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerCodeTransform/Model/NameImport/CandidateFinder.php(32): Phpactor\WorseReflection\Core\Reflector\CompositeReflector->diagnostics('<?php\n\ndeclare(...')
#55 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerCodeTransform/Model/NameImport/CandidateFinder.php(46): Phpactor\Extension\LanguageServerCodeTransform\Model\NameImport\CandidateFinder->unresolved(Object(Phpactor\LanguageServerProtocol\TextDocumentItem))
#56 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerCodeTransform/CodeAction/ImportNameProvider.php(39): Phpactor\Extension\LanguageServerCodeTransform\Model\NameImport\CandidateFinder->importCandidates(Object(Phpactor\LanguageServerProtocol\TextDocumentItem))
#57 [internal function]: Phpactor\Extension\LanguageServerCodeTransform\CodeAction\ImportNameProvider->Phpactor\Extension\LanguageServerCodeTransform\CodeAction\{closure}()
#58 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#59 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#60 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerCodeTransform/CodeAction/ImportNameProvider.php(49): Amp\call(Object(Closure))
#61 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/CodeAction/AggregateCodeActionProvider.php(32): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\ImportNameProvider->provideActionsFor(Object(Phpactor\LanguageServerProtocol\TextDocumentItem), Object(Phpactor\LanguageServerProtocol\Range), Object(Amp\CancellationToken@anonymous))
#62 [internal function]: Phpactor\LanguageServer\Core\CodeAction\AggregateCodeActionProvider->Phpactor\LanguageServer\Core\CodeAction\{closure}()
#63 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#64 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#65 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/CodeAction/AggregateCodeActionProvider.php(40): Amp\call(Object(Closure))
#66 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Handler/TextDocument/CodeActionHandler.php(60): Phpactor\LanguageServer\Core\CodeAction\AggregateCodeActionProvider->provideActionsFor(Object(Phpactor\LanguageServerProtocol\TextDocumentItem), Object(Phpactor\LanguageServerProtocol\Range), Object(Amp\CancellationToken@anonymous))
#67 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(90): Phpactor\LanguageServer\Handler\TextDocument\CodeActionHandler->Phpactor\LanguageServer\Handler\TextDocument\{closure}()
#68 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Handler/TextDocument/CodeActionHandler.php(61): Amp\call(Object(Closure))
#69 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(86): Phpactor\LanguageServer\Handler\TextDocument\CodeActionHandler->codeAction(Object(Phpactor\LanguageServerProtocol\CodeActionParams), Object(Amp\CancellationToken@anonymous))
#70 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#71 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#72 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#73 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(102): Amp\call(Object(Closure))
#74 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#75 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\HandlerMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#76 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(35): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#77 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#78 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(37): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#79 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#80 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#81 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#82 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ShutdownMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#83 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ShutdownMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#84 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#85 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#86 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(40): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#87 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#88 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#89 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#90 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(78): Amp\call(Object(Closure))
#91 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#92 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#93 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(221): Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher->dispatch(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#94 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#95 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#96 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#97 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(121): Amp\call(Object(Closure))
#98 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(238): Amp\asyncCall(Object(Closure))
#99 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(212): Phpactor\LanguageServer\Core\Server\LanguageServer->dispatchRequest(Object(Phpactor\LanguageServer\Core\Server\Transmitter\ConnectionMessageTransmitter), Object(Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher), Object(Phpactor\LanguageServer\Core\Server\StreamProvider\Connection), Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#100 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#101 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#102 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#103 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve(Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#104 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, 'Content-Length:...')
#105 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve('Content-Length:...')
#106 /root/.shared_extensions/phpactor2/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve('Content-Length:...')
#107 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('a', Resource id #1, NULL)
#108 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams(Array, Array, 0.1)
#109 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch(true)
#110 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#111 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#112 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(112): Amp\Loop::run(Object(Closure))
#113 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServer/Command/StartCommand.php(54): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#114 /root/.shared_extensions/phpactor2/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\LanguageServer\Command\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#115 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#116 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Phpactor\Extension\LanguageServer\Command\StartCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#117 /root/.shared_extensions/phpactor2/lib/Application.php(48): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#118 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#119 /root/.shared_extensions/phpactor2/bin/phpactor(45): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#120 {main}
```

**Comment by dantleech** [comment]
https://github.com/phpactor/phpactor/pull/1813
