### ISSUE TITLE
Special characters cause an exception

### ISSUE THREAD

**Issue by axelrindle** [phpactor/phpactor#1910]
### Description

Inserting characters like `Ä`, `Ö`, `Ü` or `ß` outside of a string causes an exception.

### Possible relations

#1264

### Stacktrace

<details>
<summary>Click to reveal</summary>

```
[Error - 16:19:41] Request textDocument/completion failed.
  Message: Exception [RuntimeException] preg_replace could not parse string (size 694): Malformed UTF-8 characters, possibly incorrectly encoded at {...}/vendor/phpactor/phpactor/lib/Completion/Core/Util/OffsetHelper.php#15
  Code: -32603 
#0 {...}/vendor/phpactor/phpactor/lib/Completion/Bridge/TolerantParser/WorseReflection/DoctrineAnnotationCompletor.php(92): Phpactor\Completion\Core\Util\OffsetHelper::lastNonWhitespaceCharacterOffset()
#1 {...}/vendor/phpactor/phpactor/lib/Completion/Bridge/TolerantParser/WorseReflection/DoctrineAnnotationCompletor.php(40): Phpactor\Completion\Bridge\TolerantParser\WorseReflection\DoctrineAnnotationCompletor->truncateSource()
#2 {...}/vendor/phpactor/phpactor/lib/Completion/Core/ChainCompletor.php(31): Phpactor\Completion\Bridge\TolerantParser\WorseReflection\DoctrineAnnotationCompletor->complete()
#3 {...}/vendor/phpactor/phpactor/lib/Completion/Core/Completor/DedupeCompletor.php(27): Phpactor\Completion\Core\ChainCompletor->complete()
#4 {...}/vendor/phpactor/phpactor/lib/Completion/Core/Completor/LabelFormattingCompletor.php(30): Phpactor\Completion\Core\Completor\DedupeCompletor->complete()
#5 {...}/vendor/phpactor/phpactor/lib/Completion/Core/Completor/DocumentingCompletor.php(26): Phpactor\Completion\Core\Completor\LabelFormattingCompletor->complete()
#6 {...}/vendor/phpactor/phpactor/lib/Extension/LanguageServerCompletion/Handler/CompletionHandler.php(99): Phpactor\Completion\Core\Completor\DocumentingCompletor->complete()
#7 [internal function]: Phpactor\Extension\LanguageServerCompletion\Handler\CompletionHandler->Phpactor\Extension\LanguageServerCompletion\Handler\{closure}()
#8 {...}/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#9 {...}/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#10 {...}/vendor/phpactor/phpactor/lib/Extension/LanguageServerCompletion/Handler/CompletionHandler.php(147): Amp\call()
#11 {...}/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(86): Phpactor\Extension\LanguageServerCompletion\Handler\CompletionHandler->completion()
#12 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#13 {...}/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#14 {...}/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#15 {...}/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(102): Amp\call()
#16 {...}/vendor/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch()
#17 {...}/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\HandlerMiddleware->process()
#18 {...}/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(35): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#19 {...}/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process()
#20 {...}/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(37): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#21 {...}/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process()
#22 {...}/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#23 {...}/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process()
#24 {...}/vendor/phpactor/language-server/lib/Middleware/ShutdownMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#25 {...}/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ShutdownMiddleware->process()
#26 {...}/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#27 {...}/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process()
#28 {...}/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(40): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#29 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#30 {...}/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#31 {...}/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#32 {...}/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(78): Amp\call()
#33 {...}/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process()
#34 {...}/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#35 {...}/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(221): Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher->dispatch()
#36 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#37 {...}/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#38 {...}/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#39 {...}/vendor/amphp/amp/lib/functions.php(121): Amp\call()
#40 {...}/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(238): Amp\asyncCall()
#41 {...}/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(212): Phpactor\LanguageServer\Core\Server\LanguageServer->dispatchRequest()
#42 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#43 {...}/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#44 {...}/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#45 {...}/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve()
#46 {...}/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#47 {...}/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#48 {...}/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve()
#49 {...}/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#50 {...}/vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams()
#51 {...}/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#52 {...}/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#53 {...}/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#54 {...}/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(112): Amp\Loop::run()
#55 {...}/vendor/phpactor/phpactor/lib/Extension/LanguageServer/Command/StartCommand.php(54): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#56 {...}/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\LanguageServer\Command\StartCommand->execute()
#57 {...}/vendor/symfony/console/Application.php(1028): Symfony\Component\Console\Command\Command->run()
#58 {...}/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#59 {...}/vendor/phpactor/phpactor/lib/Application.php(48): Symfony\Component\Console\Application->doRun()
#60 {...}/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun()
#61 {...}/vendor/phpactor/phpactor/bin/phpactor(45): Symfony\Component\Console\Application->run()
#62 {...}/vendor/bin/phpactor(120): include('...')
#63 {main}
```

</details>

**Comment by dantleech** [comment]
duplicate of: https://github.com/phpactor/phpactor/issues/1601

**Comment by axelrindle** [comment]
Closing this as a duplicate.
