### ISSUE TITLE
Uncaught Amp\\Process\\StatusError: Process is not running

### ISSUE THREAD

**Issue by frankwecode** [phpactor/phpactor#2269]
Im running phpactor in neovim and it ever so often crashes out of nowhere. My log file reports this:
```
[error][2023-05-25 11:14:26] .../vim/lsp/rpc.lua:734
"rpc" "/users/frankfriberg/.local/share/nvim/mason/bin/phpactor" "stderr"
"php fatal error: uncaught amp\\process\\statuserror: process is not running. in /users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/process/lib/process.php:138
stack trace:
#0 /users/frankfriberg/.local/share/nvim/mason/packages/phpactor/lib/extension/languageserver/diagnosticprovider/outsourceddiagnosticsprovider.php(46): amp\\process\\process->kill()
#1 [internal function]: phpactor\\extension\\languageserver\\diagnosticprovider\\outsourceddiagnosticsprovider->phpactor\\extension\\languageserver\\diagnosticprovider\\{closure}()
#2 /users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/coroutine.php(118): generator->send(null)
#3 /users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/internal/placeholder.php(149): amp\\coroutine->amp\\{closure}(null, null)
#4 /users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/delayed.php(26): amp\\delayed->resolve(null)
#5 /users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/loop/nativedriver.php(142): amp\\delayed->amp\\{closure}('bvq', null)
#6 /users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/loop/driver.php(138): amp\\loop\\nativedriver->dispatch(false)
#7 /users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/loop/driver.php(72): amp\\loop\\driver->tick()
#8 /users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/loop.php(95): amp\\loop\\driver->run()
#9 /users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/core/server/languageserver.php(110): amp\\loop::run(object(closure))
#10 /users/frankfriberg/.local/share/nvim/mason/packages/phpactor/lib/extension/languageserver/command/startcommand.php(50): phpactor\\languageserver\\core\\server\\languageserver->run()
#11 /users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/command/command.php(298): phpactor\\extension\\languageserver\\command\\startcommand->execute(object(symfony\\component\\console\\input\\argvinput), object(symfony\\component\\console\\output\\consoleoutput))
#12 /users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/application.php(1040): symfony\\component\\console\\command\\command->run(object(symfony\\component\\console\\input\\argvinput), object(symfony\\component\\console\\output\\consoleoutput))
#13 /users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/application.php(301): symfony\\component\\console\\application->d
```
Mason is just my language server manager that downloads and updates language servers automatically, its running ```phpactor 2023.04.10```

**Comment by dantleech** [comment]
can you try `master`? I think this may have been fixed.

**Comment by frankwecode** [comment]
@dantleech havn't had a crash since updating, thanks!

Just a side question though, is this related to PHPactor or neovim?
```
[ERROR][2023-06-01 08:51:06] .../vim/lsp/rpc.lua:734
"rpc" "/Users/frankfriberg/.local/share/nvim/mason/bin/phpactor" "stderr"
"PHP Warning:  Undefined array key 11 in /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/lib/Extension/LanguageServerCompletion/Handler/CompletionHandler.php on line 139
Warning: Undefined array key 11 in /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/lib/Extension/LanguageServerCompletion/Handler/CompletionHandler.php on line 139"
```
I get these a bunch with different array key references.

**Comment by frankwecode** [comment]
@dantleech It crashed again today
```
[ERROR][2023-06-02 12:20:49]
.../vim/lsp/rpc.lua:734
"rpc"
"/Users/frankfriberg/.local/share/nvim/mason/bin/phpactor"
"stderr"
"PHP Fatal error:  Uncaught Amp\\Process\\StatusError: Process is not running. in /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/process/lib/Process.php:138\n
Stack trace:\n
#0 /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/lib/Extension/LanguageServer/DiagnosticProvider/OutsourcedDiagnosticsProvider.php(46): Amp\\Process\\Process->kill()\n
#1 [internal function]: Phpactor\\Extension\\LanguageServer\\DiagnosticProvider\\OutsourcedDiagnosticsProvider->Phpactor\\Extension\\LanguageServer\\DiagnosticProvider\\{closure}()\n
#2 /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(NULL)\n
#3 /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\\Coroutine->Amp\\{closure}(NULL, NULL)\n
#4 /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Delayed.php(26): Amp\\Delayed->resolve(NULL)\n
#5 /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(142): Amp\\Delayed->Amp\\{closure}('ckhk', NULL)\n
#6 /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\\Loop\\NativeDriver->dispatch(true)\n
#7 /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\\Loop\\Driver->tick()\n
#8 /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\\Loop\\Driver->run()\n
#9 /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(110): Amp\\Loop::run(Object(Closure))\n
#10 /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/lib/Extension/LanguageServer/Command/StartCommand.php(50): Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->run()\n
#11 /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\\Extension\\LanguageServer\\Command\\StartCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n
#12 /Users/frankfriberg/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput
```

**Comment by frankwecode** [comment]
@dantleech sorry my bad, the version reverted in an update somehow 😓 
Thank you for your help, and thank you for your contribution! 🎉

**Comment by Geraint** [comment]
@dantleech I've been getting what appears to be the error, also in Neovim, for a few months.

```
PHP Fatal error:  Uncaught Amp\\Process\\StatusError: Process is not running. in /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/process/lib/Process.php:155
Stack trace:
#0 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/amp-fswatch/src/Watcher/Watchman/WatchmanWatcher.php(137): Amp\\Process\\Process->signal()
#1 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/amp-fswatch/src/Watcher/BufferedWatcher/BufferedWatcherProcess.php(59): Phpactor\\AmpFsWatch\\Watcher\\Watchman\\WatchmanWatcher->stop()
#2 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/amp-fswatch/src/Watcher/PatternMatching/PatternWatcherProcess.php(44): Phpactor\\AmpFsWatch\\Watcher\\BufferedWatcher\\BufferedWatcherProcess->stop()
#3 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/lib/Extension/LanguageServerIndexer/Handler/IndexerHandler.php(162): Phpactor\\AmpFsWatch\\Watcher\\PatternMatching\\PatternWatcherProcess->stop()
#4 [internal function]: Phpactor\\Extension\\LanguageServerIndexer\\Handler\\IndexerHandler->Phpactor\\Extension\\LanguageServerIndexer\\Handler\\{closure}()
#5 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#6 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\\Coroutine->Amp\\{closure}()
#7 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Delayed.php(26): Amp\\Delayed->resolve()
#8 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(142): Amp\\Delayed->Amp\\{closure}()
#9 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\\Loop\\NativeDriver->dispatch()
#10 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\\Loop\\Driver->tick()
#11 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\\Loop\\Driver->run()
#12 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(113): Amp\\Loop::run()
#13 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/lib/Extension/LanguageServer/Command/StartCommand.php(50): Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->run()
#14 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\\Extension\\LanguageServer\\Command\\StartCommand->execute()
#15 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()
#16 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#17 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/lib/Application.php(48): Symfony\\Component\\Console\\Application->doRun()
#18 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Application.php(171): Phpactor\\Application->doRun()
#19 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/bin/phpactor(46): Symfony\\Component\\Console\\Application->run()
#20 {main}
thrown in /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/process/lib/Process.php on line 155
```

If I pin the version of PHPActor to Release 2023.04.10, then everything works OK.

Any subsequent Release, and I get frequent Fatal Errors like the one above.

I had been waiting to see if the latest release, 2023.08.06, would fix it, but sadly it has not.

I'm running in PHP 8.1 in WSL.

**Comment by dantleech** [comment]
Hm, it's coming from the watchman integration. Similar but different can you create a new issue?  As a workaround you can disable it or install inotify-tools if on Linux.

**Comment by Geraint** [comment]
> Hm, it's coming from the watchman integration. Similar but different can you create a new issue? As a workaround you can disable it or install inotify-tools if on Linux.

@dantleech Thanks for getting back to me.

I did already try inotify-tools a while back and got what appeared to be the same error, but I will try again.

I'll wait until I've got some stack traces for intofiy before I make a new issue.

**Comment by dantleech** [comment]
feel free to create a new issue and append to it regardless - the issue with Watchman is clear enough

**Comment by Geraint** [comment]
I have created #2336.
