### ISSUE TITLE
Watchman; Uncaught Amp\\Process\\StatusError: Process is not running

### ISSUE THREAD

**Issue by Geraint** [phpactor/phpactor#2336]
As discussed in #2269, I'm getting a similar error:

```
PHP Fatal error:  Uncaught Amp\\Process\\StatusError: Process is not running. in /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/process/lib/Process.php:155
Stack trace:
#0 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/amp-fswatch/src/Watcher/Watchman/WatchmanWatcher.php(137): Amp\\Process\\Process->signal()
#1 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/amp-fswatch/src/Watcher/BufferedWatcher/BufferedWatcherProcess.php(59): Phpactor\\AmpFsWatch\\Watcher\\Watchman\\WatchmanWatcher->stop()
#2 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/amp-fswatch/src/Watcher/PatternMatching/PatternWatcherProcess.php(44): Phpactor\\AmpFsWatch\\Watcher\\BufferedWatcher\\BufferedWatcherProcess->stop()
#3 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/lib/Extension/LanguageServerIndexer/Handler/IndexerHandler.php(162): Phpactor\\AmpFsWatch\\Watcher\\PatternMatching\\PatternWatcherProcess->stop()
#4 [internal function]: Phpactor\\Extension\\LanguageServerIndexer\\Handler\\IndexerHandler->Phpactor\\Extension\\LanguageServerIndexer\\Handler\\{closure}()
#5 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#6 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\\Coroutine->Amp\\{closure}()
#7 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Delayed.php(26): Amp\\Delayed->resolve()
#8 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(142): Amp\\Delayed->Amp\\{closure}()
#9 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\\Loop\\NativeDriver->dispatch()
#10 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\\Loop\\Driver->tick()
#11 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\\Loop\\Driver->run()
#12 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(113): Amp\\Loop::run()
#13 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/lib/Extension/LanguageServer/Command/StartCommand.php(50): Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->run()
#14 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\\Extension\\LanguageServer\\Command\\StartCommand->execute()
#15 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()
#16 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#17 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/lib/Application.php(48): Symfony\\Component\\Console\\Application->doRun()
#18 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Application.php(171): Phpactor\\Application->doRun()
#19 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/bin/phpactor(46): Symfony\\Component\\Console\\Application->run()
#20 {main}
thrown in /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/process/lib/Process.php on line 155
```

If I pin the version of PHPActor to `2023.04.10`, the problem stops happening.

If I use a subsequent release, including `2023.08.06`, I get frequent crashes.

I'm running PHPActor in Neovim on WSL (Ubuntu 22.04) on Windows 10.  I'm using PHP version 8.1.21.

**Comment by dantleech** [comment]
hey, can you confirm if that has been fixed now? closing this issue optimistically...

**Comment by Geraint** [comment]
> hey, can you confirm if that has been fixed now? closing this issue optimistically...

Thanks for this.

I've updated to this version.  I'll keep an eye on it and let you know if I get any crashes.

**Comment by Geraint** [comment]
@dantleech Just had another crash, I'm afraid:

```
[ERROR][2023-08-15 14:57:38] .../vim/lsp/rpc.lua:734    "rpc"   "/home/geraint/.local/share/nvim/mason/bin/phpactor"    "stderr"        'PHP Fatal error:  Uncaught Error: Class "Amp\\Failure" not found in /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php:177
Stack trace:
#0 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Coroutine.php(137): Amp\\Coroutine->fail()
#1 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\\Coroutine->Amp\\{closure}()
#2 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Coroutine.php(123): Amp\\Coroutine->resolve()
#3 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\\Coroutine->Amp\\{closure}()
#4 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Deferred.php(53): Amp\\Promise@anonymous->resolve()
#5 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Server/ResponseWatcher/DeferredResponseWatcher.php(21): Amp\\Deferred->resolve()
#6 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(31): Phpactor\\LanguageServer\\Core\\Server\\ResponseWatcher\\DeferredResponseWatcher->handle()
#7 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\\LanguageServer\\Middleware\\ResponseHandlingMiddleware->process()
#8 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(30): Phpactor\\LanguageServer\\Core\\Middleware\\RequestHandler->handle()
#9 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\\LanguageServer\\Middleware\\MethodAliasMiddleware->process()
#10 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\\LanguageServer\\Core\\Middleware\\RequestHandler->handle()
#11 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\\LanguageServer\\Middleware\\CancellationMiddleware->process()
#12 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Middleware/ShutdownMiddleware.php(68): Phpactor\\LanguageServer\\Core\\Middleware\\RequestHandler->handle()
#13 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\\LanguageServer\\Middleware\\ShutdownMiddleware->process()
#14 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(52): Phpactor\\LanguageServer\\Core\\Middleware\\RequestHandler->handle()
#15 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\\LanguageServer\\Middleware\\InitializeMiddleware->process()
#16 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(34): Phpactor\\LanguageServer\\Core\\Middleware\\RequestHandler->handle()
#17 [internal function]: Phpactor\\LanguageServer\\Middleware\\ErrorHandlingMiddleware->Phpactor\\LanguageServer\\Middleware\\{closure}()
#18 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#19 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\\Coroutine->__construct()
#20 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(73): Amp\\call()
#21 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\\LanguageServer\\Middleware\\ErrorHandlingMiddleware->process()
#22 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\\LanguageServer\\Core\\Middleware\\RequestHandler->handle()
#23 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(223): Phpactor\\LanguageServer\\Core\\Dispatcher\\Dispatcher\\MiddlewareDispatcher->dispatch()
#24 [internal function]: Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->Phpactor\\LanguageServer\\Core\\Server\\{closure}()
#25 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#26 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\\Coroutine->__construct()
#27 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/functions.php(121): Amp\\call()
#28 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(240): Amp\\asyncCall()
#29 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(214): Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->dispatchRequest()
#30 [internal function]: Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->Phpactor\\LanguageServer\\Core\\Server\\{closure}()
#31 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#32 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\\Coroutine->Amp\\{closure}()
#33 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Coroutine.php(123): Amp\\Coroutine->resolve()
#34 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\\Coroutine->Amp\\{closure}()
#35 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Deferred.php(53): Amp\\Promise@anonymous->resolve()
#36 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\\Deferred->resolve()
#37 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\\ByteStream\\ResourceInputStream::Amp\\ByteStream\\{closure}()
#38 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\\Loop\\NativeDriver->selectStreams()
#39 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\\Loop\\NativeDriver->dispatch()
#40 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\\Loop\\Driver->tick()
#41 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\\Loop\\Driver->run()
#42 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(113): Amp\\Loop::run()
#43 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/lib/Extension/LanguageServer/Command/StartCommand.php(50): Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->run()
#44 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\\Extension\\LanguageServer\\Command\\StartCommand->execute()
#45 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()
#46 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#47 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/lib/Application.php(48): Symfony\\Component\\Console\\Application->doRun()
#48 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Application.php(171): Phpactor\\Application->doRun()
#49 /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/bin/phpactor(46): Symfony\\Component\\Console\\Application->run()
#50 {main}
thrown in /home/geraint/dot-files/nvim/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php on line 177
```

I double checked I was using the right version:

```
$ ~/dot-files/nvim/.local/share/nvim/mason/packages/phpactor $ cat composer.json | grep amp-fswatch
        "phpactor/amp-fswatch": "^0.3.0",
```
