### ISSUE TITLE
Exception [DivisionByZeroError] Division by zero at lib/WorseReflection/Core/Type/NumericType.php#36

### ISSUE THREAD

**Issue by leo-unglaub** [phpactor/phpactor#2355]
Hey,
recently i get some crashes with the following error message:

```
Exception [DivisionByZeroError] Division by zero at /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Type/NumericType.php#36
```

I am on the latest version from git (8b05f7adc93f4f08095aed7a31255e28620e99a0) on a normal Debian Desktop using PHP 8.2. The editor used is VS Code with your Addon installed.

Here is the full stacktrace:
```
[Error - 19:31:07] Request textDocument/codeAction failed.
  Message: Exception [DivisionByZeroError] Division by zero at /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Type/NumericType.php#36
  Code: -32603 
#0 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/Resolver/BinaryExpressionResolver.php(155): Phpactor\WorseReflection\Core\Type\NumericType->divide()
#1 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/Resolver/BinaryExpressionResolver.php(58): Phpactor\WorseReflection\Core\Inference\Resolver\BinaryExpressionResolver->walkBinaryExpression()
#2 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/NodeContextResolver.php(94): Phpactor\WorseReflection\Core\Inference\Resolver\BinaryExpressionResolver->resolve()
#3 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/NodeContextResolver.php(82): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNode()
#4 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Cache/StaticCache.php(23): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->Phpactor\WorseReflection\Core\Inference\{closure}()
#5 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/NodeContextResolver.php(74): Phpactor\WorseReflection\Core\Cache\StaticCache->getOrSet()
#6 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/NodeContextResolver.php(40): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNodeWithCache()
#7 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/FrameResolver.php(81): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->resolveNode()
#8 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/Walker/PassThroughWalker.php(46): Phpactor\WorseReflection\Core\Inference\FrameResolver->resolveNode()
#9 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/FrameResolver.php(141): Phpactor\WorseReflection\Core\Inference\Walker\PassThroughWalker->enter()
#10 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/FrameResolver.php(147): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode()
#11 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/FrameResolver.php(147): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode()
#12 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/FrameResolver.php(147): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode()
#13 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/FrameResolver.php(147): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode()
#14 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/FrameResolver.php(147): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode()
#15 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Core/Inference/FrameResolver.php(147): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode()
#16 /home/leo/code/github.com/phpactor/phpactor/lib/WorseReflection/Bridge/TolerantParser/Reflector/TolerantSourceCodeReflector.php(74): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode()
#17 [internal function]: Phpactor\WorseReflection\Bridge\TolerantParser\Reflector\TolerantSourceCodeReflector->Phpactor\WorseReflection\Bridge\TolerantParser\Reflector\{closure}()
#18 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#19 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#20 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Delayed.php(26): Amp\Delayed->resolve()
#21 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(142): Amp\Delayed->Amp\{closure}()
#22 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#23 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#24 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#25 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(111): Amp\Loop::run()
#26 /home/leo/code/github.com/phpactor/phpactor/lib/Extension/LanguageServer/Command/StartCommand.php(50): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#27 /home/leo/code/github.com/phpactor/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\LanguageServer\Command\StartCommand->execute()
#28 /home/leo/code/github.com/phpactor/phpactor/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#29 /home/leo/code/github.com/phpactor/phpactor/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#30 /home/leo/code/github.com/phpactor/phpactor/lib/Application.php(48): Symfony\Component\Console\Application->doRun()
#31 /home/leo/code/github.com/phpactor/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun()
#32 /home/leo/code/github.com/phpactor/phpactor/bin/phpactor(46): Symfony\Component\Console\Application->run()
#33 {main}
```

Thanks and greetings
Leo

**Comment by dantleech** [comment]
Looks like we need to handle division by zero here: https://github.com/phpactor/phpactor/blob/b5cdcff00d51542ec3788fb74dfb52abc9037551/lib/WorseReflection/Core/Type/NumericType.php#L36

probably by returning NAN

**Comment by dantleech** [comment]
https://github.com/phpactor/phpactor/pull/2356
