### ISSUE TITLE
LSP integration throws TypeError with LoggerInterface

### ISSUE THREAD

**Issue by binarious** [phpactor/phpactor#2376]
The LSP integration doesn't work for me anymore in neovim.

- Version: 2023.08.06-1@2f0909c94967fc711ccf43451974e8a51d084a13
- Integration: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#phpactor
- PHP 8.2.10
- System: Arch Linux (Kernel 6.5.3)

Error in logs:
```
Fatal error: Uncaught TypeError: Phpactor\\LanguageServer\\Core\\Diagnostics\\DiagnosticsEngine::__construct(): Argument #2 ($logger) must be of type Psr\\Log\\LoggerInterface, array given, called in /home/myuser/.config/composer/vendor/phpactor/phpactor/lib/Extension/LanguageServer/LanguageServerExtension.php on line 507 and defined in /home/myuser/.config/composer/vendor/phpactor/language-server/lib/Core/Diagnostics/DiagnosticsEngine.php:48
Stack trace:
#0 /home/myuser/.config/composer/vendor/phpactor/phpactor/lib/Extension/LanguageServer/LanguageServerExtension.php(507): Phpactor\\LanguageServer\\Core\\Diagnostics\\DiagnosticsEngine->__construct()
#1 /home/myuser/.config/composer/vendor/phpactor/container/lib/PhpactorContainer.php(83): Phpactor\\Extension\\LanguageServer\\LanguageServerExtension->Phpactor\\Extension\\LanguageServer\\{closure}()
#2 /home/myuser/.config/composer/vendor/phpactor/phpactor/lib/Extension/LanguageServer/LanguageServerExtension.php(487): Phpactor\\Container\\PhpactorContainer->get()
#3 /home/myuser/.config/composer/vendor/phpactor/container/lib/PhpactorContainer.php(83): Phpactor\\Extension\\LanguageServer\\LanguageServerExtension->Phpactor\\Extension\\LanguageServer\\{closure}()
#4 /home/myuser/.config/composer/vendor/phpactor/phpactor/lib/Extension/LanguageServer/LanguageServerExtension.php(334): Phpactor\\Container\\PhpactorContainer->get()
#5 /home/myuser/.config/composer/vendor/phpactor/container/lib/PhpactorContainer.php(83): Phpactor\\Extension\\LanguageServer\\LanguageServerExtension->Phpactor\\Extension\\LanguageServer\\{closure}()
#6 /home/myuser/.config/composer/vendor/phpactor/phpactor/lib/Extension/LanguageServer/LanguageServerExtension.php(327): Phpactor\\Container\\PhpactorContainer->get()
#7 /home/myuser/.config/composer/vendor/phpactor/container/lib/PhpactorContainer.php(83): Phpactor\\Extension\\LanguageServer\\LanguageServerExtension->Phpactor\\Extension\\LanguageServer\\{closure}()
#8 /home/myuser/.config/composer/vendor/phpactor/phpactor/lib/Extension/LanguageServer/LanguageServerExtension.php(265): Phpactor\\Container\\PhpactorContainer->get()
#9 /home/myuser/.config/composer/vendor/phpactor/container/lib/PhpactorContainer.php(83): Phpactor\\Extension\\LanguageServer\\LanguageServerExtension->Phpactor\\Extension\\LanguageServer\\{closure}()
#10 /home/myuser/.config/composer/vendor/phpactor/phpactor/lib/Extension/LanguageServer/LanguageServerExtension.php(418): Phpactor\\Container\\PhpactorContainer->get()
#11 /home/myuser/.config/composer/vendor/phpactor/container/lib/PhpactorContainer.php(83): Phpactor\\Extension\\LanguageServer\\LanguageServerExtension->Phpactor\\Extension\\LanguageServer\\{closure}()
#12 /home/myuser/.config/composer/vendor/phpactor/phpactor/lib/Extension/LanguageServer/LanguageServerExtension.php(375): Phpactor\\Container\\PhpactorContainer->get()
#13 /home/myuser/.config/composer/vendor/phpactor/container/lib/PhpactorContainer.php(83): Phpactor\\Extension\\LanguageServer\\LanguageServerExtension->Phpactor\\Extension\\LanguageServer\\{closure}()
#14 /home/myuser/.config/composer/vendor/phpactor/phpactor/lib/Extension/LanguageServer/Dispatcher/PhpactorDispatcherFactory.php(35): Phpactor\\Container\\PhpactorContainer->get()
#15 /home/myuser/.config/composer/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(208): Phpactor\\Extension\\LanguageServer\\Dispatcher\\PhpactorDispatcherFactory->create()
#16 [internal function]: Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->Phpactor\\LanguageServer\\Core\\Server\\{closure}()
#17 /home/myuser/.config/composer/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#18 /home/myuser/.config/composer/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\\Coroutine->Amp\\{closure}()
#19 /home/myuser/.config/composer/vendor/amphp/amp/lib/Coroutine.php(123): Amp\\Coroutine->resolve()
#20 /home/myuser/.config/composer/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\\Coroutine->Amp\\{closure}()
#21 /home/myuser/.config/composer/vendor/amphp/amp/lib/Deferred.php(53): Amp\\Promise@anonymous->resolve()
#22 /home/myuser/.config/composer/vendor/amphp/byte-stream/lib/ResourceInputStream.php(109): Amp\\Deferred->resolve()
#23 /home/myuser/.config/composer/vendor/amphp/amp/lib/Loop/Driver.php(119): Amp\\ByteStream\\ResourceInputStream::Amp\\ByteStream\\{closure}()
#24 /home/myuser/.config/composer/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\\Loop\\Driver->tick()
#25 /home/myuser/.config/composer/vendor/amphp/amp/lib/Loop.php(95): Amp\\Loop\\Driver->run()
#26 /home/myuser/.config/composer/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(111): Amp\\Loop::run()
#27 /home/myuser/.config/composer/vendor/phpactor/phpactor/lib/Extension/LanguageServer/Command/StartCommand.php(50): Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->run()
#28 /home/myuser/.config/composer/vendor/symfony/console/Command/Command.php(298): Phpactor\\Extension\\LanguageServer\\Command\\StartCommand->execute()
#29 /home/myuser/.config/composer/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()
#30 /home/myuser/.config/composer/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#31 /home/myuser/.config/composer/vendor/phpactor/phpactor/lib/Application.php(48): Symfony\\Component\\Console\\Application->doRun()
#32 /home/myuser/.config/composer/vendor/symfony/console/Application.php(171): Phpactor\\Application->doRun()
#33 /home/myuser/.config/composer/vendor/phpactor/phpactor/bin/phpactor(46): Symfony\\Component\\Console\\Application->run()
#34 /home/myuser/.config/composer/vendor/bin/phpactor(119): include('...')
#35 {main}
  thrown in /home/myuser/.config/composer/vendor/phpactor/language-server/lib/Core/Diagnostics/DiagnosticsEngine.php on line 48
```

**Comment by dantleech** [comment]
composer install?

**Comment by binarious** [comment]
All is installed. Otherwise it wouldn't be able to find and reject types in `vendor/phpactor/phpactor/lib/Extension/LanguageServer/LanguageServerExtension.php` etc.

**Comment by dantleech** [comment]
I mean, this error is expected ifbyou've done a ”git pull" without a composer install

**Comment by binarious** [comment]
I fear I can't follow you. I haven't done a `git pull`. I've just installed `phpactor` globally via `composer` and used the resulting `vendor/bin/phpactor` which lead to the above error, but you've already fixed the error in https://github.com/phpactor/language-server/commit/4898945e315d9894d3495736d93793670ec0980e, I guess.

**Comment by binarious** [comment]
Ah well, not really, since https://github.com/phpactor/phpactor/blob/2023.08.06/lib/Extension/LanguageServer/LanguageServerExtension.php#L507 still passes `providers` as the 2nd parameter, but https://github.com/phpactor/language-server/blob/6.1.1/lib/Core/Diagnostics/DiagnosticsEngine.php#L48 expects the logger.

**Comment by dantleech** [comment]
If you're using `vendor/bin/phpactor` I think you may have installed it "incorrectly" but I think I've acidentally introduced a B/C break in the language-server dependency.

Basically Phpactor should be installed either via. the [PHAR](https://github.com/phpactor/phpactor/releases) or the `git clone` method you linked to. Installing via. `composer [global] require` is not supported.

**Comment by binarious** [comment]
Thanks for the hint. Didn't know that. Though not really the underlying problem of this bug and it could be a separate issue, but I would prefer the installation via composer. Why would I manually download a PHAR or pull from a git repository everytime the app gets updated when we have automatic dependency management via composer? It worked for quite some time with composer and in this case there seems to be a bug.

**Comment by dantleech** [comment]
Yes, its a "bug" in as much as I broke B/C in a library and ti would be fixed on the next release.

Composer install isn't supported because:

- It doesn't scale: If your chosen installation method is `composer global require` then Phpactor will conflict with another library sooner or later. All projects/libraries installed via. this method will conflict with each other at some point, it's a broken installation method.
- We only test with Phpactor with the shipped `.lock` file.

Saying that I understand that the update path is not so clear. Ideally the language server clients should take care of managing the installation of new versions.

**Comment by dantleech** [comment]
Anyway, I've tagged a new release so closing this for now, it should "work" again :wink:
