### ISSUE TITLE
Unknown text document

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#2498]
I keep getting this error despite the fact that the file exists and is not new (I don't know if the indexing is somehow corrupt):
```
[Error - 9:55:40 AM] Request textDocument/codeAction failed.
  Message: Exception [Phpactor\LanguageServer\Core\Workspace\Exception\UnknownDocument] Unknown text document "file:///var/www/ct/app/tests/Utils/ORMHelperTrait.php" at /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Core/Workspace/Workspace.php#45
  Code: -32603 
#0 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Handler/TextDocument/CodeActionHandler.php(54): Phpactor\LanguageServer\Core\Workspace\Workspace->get('file:///var/www...')
#1 [internal function]: Phpactor\LanguageServer\Handler\TextDocument\CodeActionHandler->Phpactor\LanguageServer\Handler\TextDocument\{closure}()
#2 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#3 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#4 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#5 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#6 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#7 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Core/Server/ResponseWatcher/DeferredResponseWatcher.php(21): Amp\Deferred->resolve(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#8 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(31): Phpactor\LanguageServer\Core\Server\ResponseWatcher\DeferredResponseWatcher->handle(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#9 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#10 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(30): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#11 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#12 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#13 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#14 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Middleware/ShutdownMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#15 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ShutdownMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#16 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(52): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#17 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#18 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(34): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#19 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#20 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#21 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#22 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(32): Amp\call(Object(Closure))
#23 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#24 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#25 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(223): Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher->dispatch(Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#26 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#27 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#28 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#29 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/functions.php(121): Amp\call(Object(Closure))
#30 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(221): Amp\asyncCall(Object(Closure))
#31 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(214): Phpactor\LanguageServer\Core\Server\LanguageServer->dispatchRequest(Object(Phpactor\LanguageServer\Core\Server\Transmitter\ConnectionMessageTransmitter), Object(Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher), Object(Phpactor\LanguageServer\Core\Server\StreamProvider\Connection), Object(Phpactor\LanguageServer\Core\Rpc\ResponseMessage))
#32 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#33 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#34 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#35 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve(Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#36 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, 'rpc":"2.0","id"...')
#37 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve('rpc":"2.0","id"...')
#38 /root/.shared_extensions/phpactor3/vendor/amphp/byte-stream/lib/ResourceInputStream.php(109): Amp\Deferred->resolve('rpc":"2.0","id"...')
#39 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Loop/Driver.php(119): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('fplr', 'rpc":"2.0","id"...')
#40 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#41 /root/.shared_extensions/phpactor3/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#42 /root/.shared_extensions/phpactor3/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(111): Amp\Loop::run(Object(Closure))
#43 /root/.shared_extensions/phpactor3/lib/Extension/LanguageServer/Command/StartCommand.php(50): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#44 /root/.shared_extensions/phpactor3/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\LanguageServer\Command\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /root/.shared_extensions/phpactor3/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /root/.shared_extensions/phpactor3/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Phpactor\Extension\LanguageServer\Command\StartCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 /root/.shared_extensions/phpactor3/lib/Application.php(48): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#48 /root/.shared_extensions/phpactor3/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 /root/.shared_extensions/phpactor3/bin/phpactor(46): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#50 {main}
```

**Comment by dantleech** [comment]
this doesn't mean the file doesn't exist, but that Ppactor has not been told about it via. the `DidOpen` notification.

**Comment by BladeMF** [comment]
Haven't had that error in a while, so I suppose it was fixed somewhere along the way.
