### ISSUE TITLE
Errors during renaming

### ISSUE THREAD

**Issue by leo-unglaub** [phpactor/phpactor#2518]
Hey,
since a few days i get a lot of errors while renaming some classes. I am on the latest version from git (HEAD) and i am using VS Code as an editor.

```
[Error - 15:14:00] Request textDocument/codeAction failed.
  Message: Exception [Phpactor\LanguageServer\Core\Workspace\Exception\UnknownDocument] Unknown text document "file:///home/leo/code/website-laravel/app/Models/User.php" at /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Workspace/Workspace.php#45
  Code: -32603
```

Here is the full stacktrace. I also tried deleting everything in `~/.cache/phpactor` and reindexing the project, still the same error.
Greetings
Leo

```
[Error - 15:14:00] Request textDocument/codeAction failed.
  Message: Exception [Phpactor\LanguageServer\Core\Workspace\Exception\UnknownDocument] Unknown text document "file:///home/leo/code/website-laravel/app/Models/User.php" at /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Workspace/Workspace.php#45
  Code: -32603 
#0 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Handler/TextDocument/CodeActionHandler.php(54): Phpactor\LanguageServer\Core\Workspace\Workspace->get()
#1 [internal function]: Phpactor\LanguageServer\Handler\TextDocument\CodeActionHandler->Phpactor\LanguageServer\Handler\TextDocument\{closure}()
#2 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#3 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#4 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve()
#5 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#6 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#7 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/ResponseWatcher/DeferredResponseWatcher.php(21): Amp\Deferred->resolve()
#8 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(31): Phpactor\LanguageServer\Core\Server\ResponseWatcher\DeferredResponseWatcher->handle()
#9 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process()
#10 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(30): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#11 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process()
#12 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#13 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process()
#14 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ShutdownMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#15 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ShutdownMiddleware->process()
#16 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(52): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#17 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process()
#18 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(34): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#19 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#20 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#21 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#22 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(32): Amp\call()
#23 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process()
#24 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#25 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(223): Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher->dispatch()
#26 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#27 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#28 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#29 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(121): Amp\call()
#30 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(221): Amp\asyncCall()
#31 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(214): Phpactor\LanguageServer\Core\Server\LanguageServer->dispatchRequest()
#32 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#33 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#34 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#35 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve()
#36 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#37 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#38 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/byte-stream/lib/ResourceInputStream.php(109): Amp\Deferred->resolve()
#39 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(119): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#40 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#41 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#42 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(111): Amp\Loop::run()
#43 /home/leo/code/github.com/phpactor/phpactor/lib/Extension/LanguageServer/Command/StartCommand.php(50): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#44 /home/leo/code/github.com/phpactor/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\LanguageServer\Command\StartCommand->execute()
#45 /home/leo/code/github.com/phpactor/phpactor/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#46 /home/leo/code/github.com/phpactor/phpactor/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#47 /home/leo/code/github.com/phpactor/phpactor/lib/Application.php(48): Symfony\Component\Console\Application->doRun()
#48 /home/leo/code/github.com/phpactor/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun()
#49 /home/leo/code/github.com/phpactor/phpactor/bin/phpactor(46): Symfony\Component\Console\Application->run()
#50 {main}
```

**Comment by przepompownia** [comment]
I haven't looked closely yet - I am also familiar with this or a similar error, but I get it only between subsequent renaming actions. In most of my cases reindexing allows me to rename file again without error.

**Comment by dantleech** [comment]
yes probably an issue with stale index, which should be a hot topic as it's something I run into multiple times a day :) i'll try and investigate.

**Comment by przepompownia** [comment]
@dantleech is it possible that the index will then become stale due to lack of notification from the client for both the old and new (renamed) files? (renamed) files?

**Comment by dantleech** [comment]
yes that is possible. Phpactor will use a number of strategies to detect file changes, CoC will actually send the notifications to Phpactor via. LSP notifications, if that's not possible it will try inotify-watch and watchman, falling back to `find` at regular intervals. On top of that, just to be safe Phpactor will rescan the project for changed files and index them every 5 minutes.

**Comment by przepompownia** [comment]
I still haven't answered myself which LSP notification about deleted file should be enough  to detect the deletion on Phpactor side (or how to verify if any watcher implementation reported such event).

**Comment by dantleech** [comment]
Hopefully fixed in #2518 re-open if not.

**Comment by leo-unglaub** [comment]
So far it works perfectly. I took a huge codebase and renamed as much as i could find in as little time as possible. No errors, it worked perfect so far :)

Big thanks for tracking this down!

**Comment by leo-unglaub** [comment]
Damn, i was to fast. I managed to trigger an error during renaming again. I used an Enum with 30+ cases in it and renamed them, the first 20 or so worked fine, but then i got an error:

```
[Error - 05:27:47] Request textDocument/rename failed.
  Message: Exception [Error] Call to a member function getTraceAsString() on null at /home/leo/code/github.com/phpactor/phpactor/lib/Extension/LanguageServerRename/Handler/RenameHandler.php#81
  Code: -32603 
#0 [internal function]: Phpactor\Extension\LanguageServerRename\Handler\RenameHandler->Phpactor\Extension\LanguageServerRename\Handler\{closure}()
#1 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#2 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#3 /home/leo/code/github.com/phpactor/phpactor/lib/Extension/LanguageServerRename/Handler/RenameHandler.php(57): Amp\call()
#4 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(86): Phpactor\Extension\LanguageServerRename\Handler\RenameHandler->rename()
#5 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#6 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#7 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#8 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(72): Amp\call()
#9 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch()
#10 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\HandlerMiddleware->process()
#11 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(35): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#12 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process()
#13 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(37): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#14 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process()
#15 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#16 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process()
#17 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ShutdownMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#18 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ShutdownMiddleware->process()
#19 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(56): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#20 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process()
#21 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(34): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#22 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#23 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#24 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#25 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(32): Amp\call()
#26 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process()
#27 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#28 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(223): Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher->dispatch()
#29 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#30 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#31 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#32 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(121): Amp\call()
#33 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(221): Amp\asyncCall()
#34 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(214): Phpactor\LanguageServer\Core\Server\LanguageServer->dispatchRequest()
#35 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#36 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#37 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#38 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve()
#39 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#40 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#41 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve()
#42 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#43 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(124): Amp\Loop\NativeDriver->selectStreams()
#44 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#45 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#46 /home/leo/code/github.com/phpactor/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#47 /home/leo/code/github.com/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(111): Amp\Loop::run()
#48 /home/leo/code/github.com/phpactor/phpactor/lib/Extension/LanguageServer/Command/StartCommand.php(50): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#49 /home/leo/code/github.com/phpactor/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\LanguageServer\Command\StartCommand->execute()
#50 /home/leo/code/github.com/phpactor/phpactor/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#51 /home/leo/code/github.com/phpactor/phpactor/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#52 /home/leo/code/github.com/phpactor/phpactor/lib/Application.php(48): Symfony\Component\Console\Application->doRun()
#53 /home/leo/code/github.com/phpactor/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun()
#54 /home/leo/code/github.com/phpactor/phpactor/bin/phpactor(46): Symfony\Component\Console\Application->run()
#55 {main}
```

I am on f4a79b038563a3c925c5a9a80c7c8a20f05ca775.

**Comment by dantleech** [comment]
I mean it is a different error...

**Comment by dantleech** [comment]
it was _trying_ to show an error, but the error handling was broken -  I've updated master and it should at least show the error in the IDE now.

**Comment by przepompownia** [comment]
By coincidence, I encountered the same place in #2531 both in RenameHandler and FileRenameHandler. 

https://github.com/phpactor/phpactor/pull/2531/files#diff-ae4533ad2220106dce4b7d9a7651096361723c94c0e58b2d0c29027eb20c2386R81

**Comment by leo-unglaub** [comment]
I managed to get the full error message:

```
Could not find corresponding reference to member name "DatabaseUserUpdated" in document "file:///<home>/website/app/Models/TaskTypes.php" at offset 576
```

I also tried to run phpactor with xdebug attached to it so i could give you better debugging information. But the problem is that for me xdebug does not trigger on PHP AMP forced processed. For some reason its only active on the main thread and then gets disabled. And i cannot enable it globally, because then i get a lot of errors from the code i am working in not beeing found.

**Comment by przepompownia** [comment]
Searching by the message string takes me here: https://github.com/phpactor/phpactor/blob/3f0d15d2fdc07b6e3efa8e834088ecd03123ca03/lib/Rename/Adapter/ReferenceFinder/AbstractReferenceRenamer.php#L77-L90

**Comment by przepompownia** [comment]
@leo-unglaub please check it again after merging #2627. Did this class member have any attribute (possibly in references)?

**Comment by przepompownia** [comment]
Feedback also very appreciated, thank you too.

**Comment by leo-unglaub** [comment]
Seams fixed to me. Unable to reproduce this. Thanks everyone!
