### ISSUE TITLE
Exception in specific files

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#2528]
```
[Error - 12:04:07 PM] Request textDocument/codeAction failed.
  Message: Exception [Error] Call to undefined method Phpactor\WorseReflection\Core\Type\EnumBackedCaseType::members() at /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/Resolver/MemberAccess/NodeContextFromMemberAccess.php#160
  Code: -32603 
#0 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/Resolver/MemberAccess/NodeContextFromMemberAccess.php(103): Phpactor\WorseReflection\Core\Inference\Resolver\MemberAccess\NodeContextFromMemberAccess->resolveContainerMemberType(Object(Phpactor\WorseReflection\Core\Inference\NodeContextResolver), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression), Object(Phpactor\WorseReflection\Core\Type\EnumBackedCaseType), 'property', 'value')
#1 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/Resolver/MemberAccessExpressionResolver.php(28): Phpactor\WorseReflection\Core\Inference\Resolver\MemberAccess\NodeContextFromMemberAccess->infoFromMemberAccess(Object(Phpactor\WorseReflection\Core\Inference\NodeContextResolver), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Phpactor\WorseReflection\Core\Type\EnumBackedCaseType), Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#2 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(112): Phpactor\WorseReflection\Core\Inference\Resolver\MemberAccessExpressionResolver->resolve(Object(Phpactor\WorseReflection\Core\Inference\NodeContextResolver), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#3 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(100): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#4 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Cache/StaticCache.php(23): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->Phpactor\WorseReflection\Core\Inference\{closure}()
#5 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(92): Phpactor\WorseReflection\Core\Cache\StaticCache->getOrSet('sc:3906:6-7-0-1', Object(Closure))
#6 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(58): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNodeWithCache(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#7 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/Resolver/ArrayCreationExpressionResolver.php(37): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#8 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(112): Phpactor\WorseReflection\Core\Inference\Resolver\ArrayCreationExpressionResolver->resolve(Object(Phpactor\WorseReflection\Core\Inference\NodeContextResolver), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArrayCreationExpression))
#9 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(100): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArrayCreationExpression))
#10 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Cache/StaticCache.php(23): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->Phpactor\WorseReflection\Core\Inference\{closure}()
#11 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(92): Phpactor\WorseReflection\Core\Cache\StaticCache->getOrSet('sc:3912:6-7-0-1', Object(Closure))
#12 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(58): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNodeWithCache(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArrayCreationExpression))
#13 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/Resolver/AssignmentExpressionResolver.php(44): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\ArrayCreationExpression))
#14 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(112): Phpactor\WorseReflection\Core\Inference\Resolver\AssignmentExpressionResolver->resolve(Object(Phpactor\WorseReflection\Core\Inference\NodeContextResolver), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression))
#15 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(100): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression))
#16 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Cache/StaticCache.php(23): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->Phpactor\WorseReflection\Core\Inference\{closure}()
#17 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(92): Phpactor\WorseReflection\Core\Cache\StaticCache->getOrSet('sc:3923:6-7-0-1', Object(Closure))
#18 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/NodeContextResolver.php(58): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->doResolveNodeWithCache(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression))
#19 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(79): Phpactor\WorseReflection\Core\Inference\NodeContextResolver->resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression))
#20 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/Walker/PassThroughWalker.php(42): Phpactor\WorseReflection\Core\Inference\FrameResolver->resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression))
#21 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(107): Phpactor\WorseReflection\Core\Inference\Walker\PassThroughWalker->enter(Object(Phpactor\WorseReflection\Core\Inference\FrameResolver), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression))
#22 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#23 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#24 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\Statement\CompoundStatementNode), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#25 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\MethodDeclaration), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#26 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\ClassMembersNode), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#27 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(112): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration), Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Phpactor\WorseReflection\Core\Inference\Frame))
#28 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Inference/FrameResolver.php(71): Phpactor\WorseReflection\Core\Inference\FrameResolver->walkNode(Object(Microsoft\PhpParser\Node\SourceFileNode), Object(Microsoft\PhpParser\Node\SourceFileNode))
#29 /root/.shared_extensions/phpactor2/lib/WorseReflection/Bridge/TolerantParser/Reflector/TolerantSourceCodeReflector.php(71): Phpactor\WorseReflection\Core\Inference\FrameResolver->build(Object(Microsoft\PhpParser\Node\SourceFileNode))
#30 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Cache/TtlCache.php(50): Phpactor\WorseReflection\Bridge\TolerantParser\Reflector\TolerantSourceCodeReflector->Phpactor\WorseReflection\Bridge\TolerantParser\Reflector\{closure}()
#31 /root/.shared_extensions/phpactor2/lib/WorseReflection/Bridge/TolerantParser/Reflector/TolerantSourceCodeReflector.php(66): Phpactor\WorseReflection\Core\Cache\TtlCache->getOrSet('diagnoistics__<...', Object(Closure))
#32 /root/.shared_extensions/phpactor2/lib/WorseReflection/Core/Reflector/CompositeReflector.php(112): Phpactor\WorseReflection\Bridge\TolerantParser\Reflector\TolerantSourceCodeReflector->diagnostics(Object(Phpactor\WorseReflection\Core\SourceCode))
#33 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerCodeTransform/Model/NameImport/CandidateFinder.php(32): Phpactor\WorseReflection\Core\Reflector\CompositeReflector->diagnostics('<?php\n\ndeclare(...')
#34 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerCodeTransform/Model/NameImport/CandidateFinder.php(46): Phpactor\Extension\LanguageServerCodeTransform\Model\NameImport\CandidateFinder->unresolved(Object(Phpactor\LanguageServerProtocol\TextDocumentItem))
#35 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerCodeTransform/CodeAction/ImportNameProvider.php(39): Phpactor\Extension\LanguageServerCodeTransform\Model\NameImport\CandidateFinder->importCandidates(Object(Phpactor\LanguageServerProtocol\TextDocumentItem))
#36 [internal function]: Phpactor\Extension\LanguageServerCodeTransform\CodeAction\ImportNameProvider->Phpactor\Extension\LanguageServerCodeTransform\CodeAction\{closure}()
#37 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#38 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#39 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServerCodeTransform/CodeAction/ImportNameProvider.php(37): Amp\call(Object(Closure))
#40 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/CodeAction/AggregateCodeActionProvider.php(32): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\ImportNameProvider->provideActionsFor(Object(Phpactor\LanguageServerProtocol\TextDocumentItem), Object(Phpactor\LanguageServerProtocol\Range), Object(Amp\CancellationToken@anonymous))
#41 [internal function]: Phpactor\LanguageServer\Core\CodeAction\AggregateCodeActionProvider->Phpactor\LanguageServer\Core\CodeAction\{closure}()
#42 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#43 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#44 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/CodeAction/AggregateCodeActionProvider.php(29): Amp\call(Object(Closure))
#45 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Handler/TextDocument/CodeActionHandler.php(60): Phpactor\LanguageServer\Core\CodeAction\AggregateCodeActionProvider->provideActionsFor(Object(Phpactor\LanguageServerProtocol\TextDocumentItem), Object(Phpactor\LanguageServerProtocol\Range), Object(Amp\CancellationToken@anonymous))
#46 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(90): Phpactor\LanguageServer\Handler\TextDocument\CodeActionHandler->Phpactor\LanguageServer\Handler\TextDocument\{closure}()
#47 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Handler/TextDocument/CodeActionHandler.php(58): Amp\call(Object(Closure))
#48 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(86): Phpactor\LanguageServer\Handler\TextDocument\CodeActionHandler->codeAction(Object(Phpactor\LanguageServerProtocol\CodeActionParams), Object(Amp\CancellationToken@anonymous))
#49 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#50 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#51 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#52 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(72): Amp\call(Object(Closure))
#53 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#54 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\HandlerMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#55 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(35): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#56 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#57 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(37): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#58 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#59 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#60 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#61 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ShutdownMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#62 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ShutdownMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#63 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#64 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#65 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(40): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#66 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#67 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#68 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#69 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(38): Amp\call(Object(Closure))
#70 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#71 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServer/Middleware/ProfilerMiddleware.php(47): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#72 [internal function]: Phpactor\Extension\LanguageServer\Middleware\ProfilerMiddleware->Phpactor\Extension\LanguageServer\Middleware\{closure}()
#73 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#74 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#75 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServer/Middleware/ProfilerMiddleware.php(28): Amp\call(Object(Closure))
#76 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\Extension\LanguageServer\Middleware\ProfilerMiddleware->process(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage), Object(Phpactor\LanguageServer\Core\Middleware\RequestHandler))
#77 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#78 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(221): Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher->dispatch(Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#79 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#80 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#81 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct(Object(Generator))
#82 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/functions.php(121): Amp\call(Object(Closure))
#83 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(219): Amp\asyncCall(Object(Closure))
#84 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(212): Phpactor\LanguageServer\Core\Server\LanguageServer->dispatchRequest(Object(Phpactor\LanguageServer\Core\Server\Transmitter\ConnectionMessageTransmitter), Object(Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher), Object(Phpactor\LanguageServer\Core\Server\StreamProvider\Connection), Object(Phpactor\LanguageServer\Core\Rpc\RequestMessage))
#85 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#86 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#87 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#88 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve(Object(Phpactor\LanguageServer\Core\Rpc\RawMessage))
#89 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, 'Content-Length:...')
#90 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve('Content-Length:...')
#91 /root/.shared_extensions/phpactor2/vendor/amphp/byte-stream/lib/ResourceInputStream.php(109): Amp\Deferred->resolve('Content-Length:...')
#92 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/Driver.php(119): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('jm', 'Content-Length:...')
#93 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#94 /root/.shared_extensions/phpactor2/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#95 /root/.shared_extensions/phpactor2/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(110): Amp\Loop::run(Object(Closure))
#96 /root/.shared_extensions/phpactor2/lib/Extension/LanguageServer/Command/StartCommand.php(54): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#97 /root/.shared_extensions/phpactor2/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\LanguageServer\Command\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#98 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(1028): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#99 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Phpactor\Extension\LanguageServer\Command\StartCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#100 /root/.shared_extensions/phpactor2/lib/Application.php(48): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#101 /root/.shared_extensions/phpactor2/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#102 /root/.shared_extensions/phpactor2/bin/phpactor(45): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#103 {main}
```

**Comment by dantleech** [comment]
that method does exist though: https://github.com/phpactor/phpactor/blob/ee3c73b2ad278027042586c955038f3bab3eb154/lib/WorseReflection/Core/Type/EnumBackedCaseType.php#L39 ?

**Comment by dantleech** [comment]
are you sure you're using the latest `composer install` ?

**Comment by BladeMF** [comment]
Sorry, I somehow missed your answer. I haven't had this for a while. We can close this I think.
