### ISSUE TITLE
[WR] Fatal Error

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#254]
```
Phpactor returned an error: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Phpactor\WorseReflection\Core\I
nference\Symbol::fromTypeNameAndPosition() must be of the type string, null given, called in /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/Infer
ence/SymbolFactory.php on line 56 in /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/Symbol.php:71
Stack trace:
#0 /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolFactory.php(56): Phpactor\WorseReflection\Core\Inference\Symbol::fromTypeNameAn
dPosition(NULL, 'NULL', Object(Phpactor\WorseReflection\Core\Position))
#1 /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolInformationResolver.php(393): Phpactor\WorseReflection\Core\Inference\SymbolFac
tory->information('NULL', 22723, 22727, Array)
#2 /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolInformatio in /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflectio
n/lib/Core/Inference/Symbol.php on line 71
```

**Comment by dantleech** [comment]
Fixed in latest WR
