### ISSUE TITLE
error with composer install in latest commit

### ISSUE THREAD

**Issue by ctf0** [phpactor/phpactor#2556]
`PHP Fatal error:  Uncaught Error: Class "Phpactor\Extension\LanguageServer\LanguageServerExtraExtension" not found in /Users/xxx/phpactor/lib/Extension/Configuration/Model/JsonSchemaBuilder.php:38`

**Comment by dantleech** [comment]
Cannot reproduce this -- can you reproduce this reliably? Can you provide a full stack trace?

**Comment by ctf0** [comment]
i will post the full trace asap.

**Comment by ctf0** [comment]
```
PHP Fatal error:  Uncaught Error: Class "Phpactor\Extension\LanguageServer\LanguageServerExtraExtension" not found in /Users/xxx/phpactor/lib/Extension/Configuration/Model/JsonSchemaBuilder.php:38
Stack trace:
#0 /Users/xxx/phpactor/lib/Extension/Core/Command/ConfigJsonSchemaCommand.php(30): Phpactor\Extension\Configuration\Model\JsonSchemaBuilder->dump()
#1 /Users/xxx/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\Core\Command\ConfigJsonSchemaCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/xxx/phpactor/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/xxx/phpactor/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Phpactor\Extension\Core\Command\ConfigJsonSchemaCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/xxx/phpactor/lib/Application.php(48): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/xxx/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/xxx/phpactor/bin/phpactor(46): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 {main}
  thrown in /Users/xxx/phpactor/lib/Extension/Configuration/Model/JsonSchemaBuilder.php on line 38
Fatal error: Uncaught Error: Class "Phpactor\Extension\LanguageServer\LanguageServerExtraExtension" not found in /Users/xxx/phpactor/lib/Extension/Configuration/Model/JsonSchemaBuilder.php:38
Stack trace:
#0 /Users/xxx/phpactor/lib/Extension/Core/Command/ConfigJsonSchemaCommand.php(30): Phpactor\Extension\Configuration\Model\JsonSchemaBuilder->dump()
#1 /Users/xxx/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\Core\Command\ConfigJsonSchemaCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/xxx/phpactor/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/xxx/phpactor/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Phpactor\Extension\Core\Command\ConfigJsonSchemaCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/xxx/phpactor/lib/Application.php(48): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/xxx/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/xxx/phpactor/bin/phpactor(46): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 {main}
  thrown in /Users/xxx/phpactor/lib/Extension/Configuration/Model/JsonSchemaBuilder.php on line 38
```

**Comment by dantleech** [comment]
That's very confusing as that class does not exist anywhere, as far as I know the extensions list is built in lib/Phpactor.php and it's not there.

**Comment by ctf0** [comment]
i redownloaded the repo and used fresh `composer install`, but getting the same error

**Comment by dantleech** [comment]
i can also clone a fresh repo and `composer install` and it's fine :thinking: 

```
git grep LanguageServerExtraExtension
```
?

clutching at straws: do you have any legacy configuration? e.g. in `~/.config/phpactor/`

does Phpactor otherwise work? e.g. running `./bin/phpactor`

**Comment by ctf0** [comment]
removing the config at `~/.config/phpactor/,` did the trick, sorry for the inconvenience.

**Comment by dantleech** [comment]
No inconvenience! do you know what was in that directory? I'm curious to know what happened here...

**Comment by ctf0** [comment]
the `phpactor.json` config file, i compared it against the one from `config:dump` anad it was missing come keys but nothing serious to trigger the error, sadly i've already deleted the old one once i updated it.

still thank you so much for ur work & help ❤️

**Comment by dantleech** [comment]
Ok, how long ago did you install phpactor initially? Just wondering how often this will happen with the next release 😅

**Comment by ctf0** [comment]
a year ago
