### ISSUE TITLE
Exception when building index

### ISSUE THREAD

**Issue by devnix** [phpactor/phpactor#2617]
I'm getting the following stack trace:

```
 57664/94658 [=================>----------]  60% 17 mins/27 mins 1,227/∞ mbPHP Fatal error:  Uncaught Error: Call to a member function getText() on null in phar:///home/devnix/.local/bin/phpactor/vendor/phpactor/tolerant-php-parser/src/Node.php:564
Stack trace:
#0 phar:///home/devnix/.local/bin/phpactor/vendor/phpactor/tolerant-php-parser/src/Node/QualifiedName.php(110): Microsoft\PhpParser\Node->getImportTablesForCurrentScope()
#1 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Adapter/Tolerant/Indexer/ClassLikeReferenceIndexer.php(58): Microsoft\PhpParser\Node\QualifiedName->getResolvedName()
#2 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(80): Phpactor\Indexer\Adapter\Tolerant\Indexer\ClassLikeReferenceIndexer->index()
#3 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(93): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->indexNode()
#4 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(93): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->indexNode()
#5 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(93): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->indexNode()
#6 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(93): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->indexNode()
#7 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(67): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->indexNode()
#8 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Model/IndexJob.php(28): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->index()
#9 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Extension/Command/IndexBuildCommand.php(85): Phpactor\Indexer\Model\IndexJob->generator()
#10 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Extension/Command/IndexBuildCommand.php(56): Phpactor\Indexer\Extension\Command\IndexBuildCommand->buildIndex()
#11 phar:///home/devnix/.local/bin/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\Indexer\Extension\Command\IndexBuildCommand->execute()
#12 phar:///home/devnix/.local/bin/phpactor/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#13 phar:///home/devnix/.local/bin/phpactor/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#14 phar:///home/devnix/.local/bin/phpactor/lib/Application.php(48): Symfony\Component\Console\Application->doRun()
#15 phar:///home/devnix/.local/bin/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun()
#16 phar:///home/devnix/.local/bin/phpactor/bin/phpactor(45): Symfony\Component\Console\Application->run()
#17 /home/devnix/.local/bin/phpactor(15): require('...')
#18 {main}
  thrown in phar:///home/devnix/.local/bin/phpactor/vendor/phpactor/tolerant-php-parser/src/Node.php on line 564
Fatal error: Uncaught Error: Call to a member function getText() on null in phar:///home/devnix/.local/bin/phpactor/vendor/phpactor/tolerant-php-parser/src/Node.php:564
Stack trace:
#0 phar:///home/devnix/.local/bin/phpactor/vendor/phpactor/tolerant-php-parser/src/Node/QualifiedName.php(110): Microsoft\PhpParser\Node->getImportTablesForCurrentScope()
#1 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Adapter/Tolerant/Indexer/ClassLikeReferenceIndexer.php(58): Microsoft\PhpParser\Node\QualifiedName->getResolvedName()
#2 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(80): Phpactor\Indexer\Adapter\Tolerant\Indexer\ClassLikeReferenceIndexer->index()
#3 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(93): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->indexNode()
#4 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(93): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->indexNode()
#5 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(93): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->indexNode()
#6 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(93): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->indexNode()
#7 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(67): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->indexNode()
#8 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Model/IndexJob.php(28): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->index()
#9 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Extension/Command/IndexBuildCommand.php(85): Phpactor\Indexer\Model\IndexJob->generator()
#10 phar:///home/devnix/.local/bin/phpactor/lib/Indexer/Extension/Command/IndexBuildCommand.php(56): Phpactor\Indexer\Extension\Command\IndexBuildCommand->buildIndex()
#11 phar:///home/devnix/.local/bin/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\Indexer\Extension\Command\IndexBuildCommand->execute()
#12 phar:///home/devnix/.local/bin/phpactor/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#13 phar:///home/devnix/.local/bin/phpactor/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#14 phar:///home/devnix/.local/bin/phpactor/lib/Application.php(48): Symfony\Component\Console\Application->doRun()
#15 phar:///home/devnix/.local/bin/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun()
#16 phar:///home/devnix/.local/bin/phpactor/bin/phpactor(45): Symfony\Component\Console\Application->run()
#17 /home/devnix/.local/bin/phpactor(15): require('...')
#18 {main}
  thrown in phar:///home/devnix/.local/bin/phpactor/vendor/phpactor/tolerant-php-parser/src/Node.php on line 564

```

**Comment by dantleech** [comment]
I cannot see how this can happen, I have added some error handling to catch any Fatal error during indexing and throw an exception with the name of the file that was being processed when the fatal error encountered.

could you pull the latest version and run the `phpactor index:build`?

fwiw it's a problem with the parser when it encounteres a class import `use ...;` although I have no idea what has happened.

**Comment by devnix** [comment]
It failed while scanning a template in the `.idea` folder 😄  It's much friendlier now, thank you! Let's see if we can scan the whole project now 🦾

**Comment by devnix** [comment]
This was the content of the failed file if it helps, however, it's not real PHP anyway. I post it in case it can be helpful!
```php
<?php

#parse("PHP File Header.php")

namespace ${MODULE_NAMESPACE}\Infrastructure\Persistence\Query;

use Doctrine\ORM\EntityManagerInterface;
use \\${MODULE_NAMESPACE}\Domain\Query\\${NAME}Interface;

final class DBAL${NAME} implements ${NAME}Interface
{
    private EntityManagerInterface \$entityManager;

    public function __construct(EntityManagerInterface \$entityManager)
    {
        \$this->entityManager = \$entityManager;
    }

    public function __invoke()
    {
        \$query = \$this->entityManager->getConnection()->createQueryBuilder();
    }
}
```

**Comment by mamazu** [comment]
Is the `.idea` folder in the excludes for the Project? If not that should fix it.

**Comment by devnix** [comment]
@mamazu I did that and solved the issue, maybe I should close the issue. Just posted the snippet that failed in case it could clarify what happened 😄

**Comment by mamazu** [comment]
We might need to expand the exclude section or even have those by default (like .idea and .vscode and whatever sublime uses)
