### ISSUE TITLE
Support Class Move in combination with composer "repositories" of type "path"

### ISSUE THREAD

**Issue by d-s-codappix** [phpactor/phpactor#2727]
Given the following setup within `composer.json` of a project:

```
    "repositories": [
        {
            "type": "path",
            "url": "local_packages/*"
        }
    ],
```

One can provide project specific composer packages within `local_packages`.
We now have packages following that structure and want to use `class:move` feature, which fails with:
```
  [RuntimeException]
  There are no class name candidates
```

The `Phpactor\ClassFileConverter\Adapter\Composer\Psr4NameInflector` will not work as it will receive `/vendor/prefix/name/Classes` instead of the `local_packages/package/Classes` path.

Adding a `realpath()` call seems to help. I'm not sure if that might break other things.

**Comment by dantleech** [comment]
Shouldn't do, feel free to make a PR ideally with a test

**Comment by d-s-codappix** [comment]
I finally managed to also cover my PR with a test case: https://github.com/phpactor/class-to-file/pull/33

**Comment by d-s-codappix** [comment]
Even though https://github.com/phpactor/class-to-file/pull/33 looks good and works for the issue mentioned here, it seems to create at least a new issue, e.g. when doing a class import:

```
Phpactor returned an error: Fatal error: Uncaught TypeError: Phpactor\CodeTransform\Domain\Refactor\ImportClass\NameImport::forClass(): Argument #1 ($name) must be of type string, null given, called in /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/lib/Extension/CodeTransformExtra/Rpc/ImportClassHandler.php on line 94 and defined in /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/lib/CodeTransform/Domain/Refactor/ImportClass/NameImport.php:19
Stack trace:
#0 /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/lib/Extension/CodeTransformExtra/Rpc/ImportClassHandler.php(94): Phpactor\CodeTransform\Domain\Refactor\ImportClass\NameImport::forClass(NULL, NULL)
#1 /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/lib/Extension/Rpc/RequestHandler/RequestHandler.php(27): Phpactor\Extension\CodeTransformExtra\Rpc\ImportClassHandler->handle(Array)
#2 /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/lib/Extension/Rpc/RequestHandler/ExceptionCatchingHandler.php(20): Phpactor\Extension\Rpc\RequestHandler\RequestHandler->handle(Object(Phpactor\Extension\Rpc\Request))
#3 /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/lib/Extension/Rpc/RequestHandler/LoggingHandler.php(27): Phpactor\Extension\Rpc\RequestHandler\ExceptionCatchingHandler->handle(Object(Phpactor\Extension\Rpc\Request))
#4 /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/lib/Extension/Rpc/Command/RpcCommand.php(65): Phpactor\Extension\Rpc\RequestHandler\LoggingHandler->handle(Object(Phpactor\Extension\Rpc\Request))
#5 /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/lib/Extension/Rpc/Command/RpcCommand.php(45): Phpactor\Extension\Rpc\Command\RpcCommand->processRequest(Object(Phpactor\Extension\Rpc\Request))
#6 /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/vendor/symfony/console/Command/Command.php(326): Phpactor\Extension\Rpc\Command\RpcCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/vendor/symfony/console/Application.php(1098): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Phpactor\Extension\Rpc\Command\RpcCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/lib/Application.php(50): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/vendor/symfony/console/Application.php(175): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/bin/phpactor(58): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 {main}
  thrown in /nix/store/w60a9z06mn3k98b4n3qw5mhnpazzwa7a-phpactor-2026.07.22.0/share/php/phpactor/lib/CodeTransform/Domain/Refactor/ImportClass/NameImport.php on line 19
```

I use `:PhpactorImportClass`. It still works without the adjustment made … I'm sorry if I introduced new bugs, feel free to revert the fix, or investigage the consequences.
