### ISSUE TITLE
PHP-CS-Fixer fails to start with non-default bindir

### ISSUE THREAD

**Issue by jtojnar** [phpactor/phpactor#2749]
I am using Phpactor 2024.06.30.0 as LSP in Sublime Text and get an error about PHP-CS-Fixer failing on startup:

```
Exception [Phpactor\Extension\LanguageServerPhpCsFixer\Exception\PhpCsFixerError] php-cs-fixer exited with code '1'; cmd: '/nix/store/9bfaprpy0vid9pc9z2a0jdlzp93vrq97-php-with-extensions-8.2.24/bin/php' '/home/jtojnar/Projects/simplepie/vendor/bin/php-cs-fixer' 'fix' '--diff' '--dry-run' '-'; stderr: ''; stdout: 'Could not open input file: /home/jtojnar/Projects/simplepie/vendor/bin/php-cs-fixer' at /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/lib/Extension/LanguageServerPhpCsFixer/Model/PhpCsFixerProcess.php#57", 'data': "#0 [internal function]: Phpactor\Extension\LanguageServerPhpCsFixer\Model\PhpCsFixerProcess->Phpactor\Extension\LanguageServerPhpCsFixer\Model\{closure}()
#1 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(1)
#2 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/amphp/amp/lib/Internal/ResolutionQueue.php(70): Amp\Coroutine->Amp\{closure}(NULL, 1)
#3 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Internal\ResolutionQueue->__invoke(NULL, 1)
#4 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve(1)
#5 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/amphp/process/lib/Internal/Posix/Runner.php(40): Amp\Deferred->resolve(1)
#6 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\Process\Internal\Posix\Runner::onProcessEndExtraDataPipeReadable('xyw', Resource id #5417, Object(Amp\Process\Internal\Posix\Handle))
#7 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(124): Amp\Loop\
ativeDriver->selectStreams(Array, Array, 0)
#8 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\
ativeDriver->dispatch(true)
#9 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#10 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#11 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(114): Amp\Loop::run(Object(Closure))
#12 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/lib/Extension/LanguageServer/Command/StartCommand.php(50): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#13 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\LanguageServer\Command\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Phpactor\Extension\LanguageServer\Command\StartCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/lib/Application.php(48): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /nix/store/a8vk7c5q8srixv4lc4l79ajy151qmxsc-phpactor-2024.06.30.0/share/php/phpactor/bin/phpactor(46): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 {main}
```

This appears to be caused by the project setting [`bin-dir`](https://getcomposer.org/doc/06-config.md#bin-dir) Composer configuration option so the executable is actually in `bin/php-cs-fixer`, not `vendor/bin/php-cs-fixer`.

https://github.com/simplepie/simplepie/blob/77d89e65a14d6ca9c27ee81a7edf0a1e9ad00a32/composer.json#L63

**Comment by dantleech** [comment]
You can change it with https://phpactor.readthedocs.io/en/master/reference/configuration.html

**Comment by jtojnar** [comment]
Right. Though I would have to do that for every such project and every tool. Would be nice if Phpactor supported detecting the [Composer `bin-dir`](https://getcomposer.org/doc/articles/vendor-binaries.md#can-vendor-binaries-be-installed-somewhere-other-than-vendor-bin-) and used `%bin_dir%/%tool_name%` with `%project_root%/vendor/bin/%tool_name%` only as a fallback.

I could try to implement it if desired.

**Comment by dantleech** [comment]
We could:

- Introduce a `%composer_bin_dir%` parameter

The place to do this is probably the [ComposerInspectorExtension](https://github.com/phpactor/phpactor/blob/gh-2707-fix/lib/Extension/ComposerInspector/ComposerInspectorExtension.php)

and then you can _probably_ register an [Expander](https://github.com/phpactor/phpactor/blob/14dc2896092ef2e40f281a5fa60d812c485032eb/lib/Extension/FilePathResolver/FilePathResolverExtension.php#L128) in the DI container from that extension to expose the resolved bin dir.

**Comment by mamazu** [comment]
@jtojnar Well, now the `%composer-bin-dir%` is implemented so feel free to use this in your config now or make a PR to update the default.
