### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by tehnodev** [phpactor/phpactor#2804]
php 8.3.14 zts on windows 11
phpactor [2024.11.28.1](https://github.com/phpactor/phpactor/releases/tag/2024.11.28.1)
```
phpactor.phar status
```
```
PHP Fatal error:  Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, false given in phar://C:/Users/dev/Downloads/tools/phpactor.phar/.box/src/Terminal.php:60
Stack trace:
#0 phar://C:/Users/dev/Downloads/tools/phpactor.phar/.box/src/Terminal.php(60): trim(false)
#1 phar://C:/Users/dev/Downloads/tools/phpactor.phar/.box/src/Terminal.php(31): HumbugBox436\KevinGH\RequirementChecker\Terminal::initDimensions()
#2 phar://C:/Users/dev/Downloads/tools/phpactor.phar/.box/src/Printer.php(28): HumbugBox436\KevinGH\RequirementChecker\Terminal->getWidth()
#3 phar://C:/Users/dev/Downloads/tools/phpactor.phar/.box/src/Checker.php(17): HumbugBox436\KevinGH\RequirementChecker\Printer->__construct(32, true)
#4 phar://C:/Users/dev/Downloads/tools/phpactor.phar/.box/bin/check-requirements.php(22): HumbugBox436\KevinGH\RequirementChecker\Checker::checkRequirements()
#5 C:\Users\dev\Downloads\tools\phpactor.phar(13): require('phar://C:/Users...')
#6 {main}
  thrown in phar://C:/Users/dev/Downloads/tools/phpactor.phar/.box/src/Terminal.php on line 60
```

**Comment by mamazu** [comment]
That looks like a bug in the symfony terminal component. However what's curious about this is that the error case should have been caught. The line reads:
```php
            if (false !== $ansicon && preg_match('/^(\d+)x(\d+)(?: \((\d+)x(\d+)\))?$/', trim($ansicon), $matches)) {
```
as we can see from the error message $ansicon is false. But this would mean that the first part of the expression should have already stopped the execution.

I don't know enough about windows php but something like this should not execute the function call:
```php
if (false && someFunction()) {}
```

**Comment by saeedvaziry** [comment]
Getting the same error on windows 11 arm

running it with the following command:

```
C:\Users\saeed\.config\herd\bin\php.bat C:\Users\saeed\Desktop\phpactor.phar language-server
```

**Comment by dantleech** [comment]
> Getting the same error on windows 11 arm

You'll need to run Phpactor in WSL or otherwise on Linux. Windows is not currently supported.

**Comment by saeedvaziry** [comment]
Ah, Didn't know that. tnx
