### ISSUE TITLE
Exception on going to definition for `Iterator`

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#322]
1. Open the definition for `Generator`
2. Try and goto the `Iterator` definition from there.

```
Phpactor returned an error: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getText() on null in /home/daniel/.vim/bundle/phpactor/
vendor/phpactor/worse-reflection/lib/Core/Inference/FullyQualifiedNameResolver.php:62
Stack trace:
#0 /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(281): Phpactor\WorseReflection\Core\Inference\FullyQualifiedNameResolver->resolve(Obj
ect(Microsoft\PhpParser\Node\Statement\FunctionDeclaration), 'exists')
#1 /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(81): Phpactor\WorseReflection\Core\Inference\FrameBuilder->injectVariablesFromComment
(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Statement\FunctionDeclaration))
#2 /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(96): Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode(Object(Microsoft\
PhpParser\Node\S in /home/daniel/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FullyQualifiedNameResolver.php on line 62
```

**Comment by dantleech** [comment]
Fixed
