### ISSUE TITLE
[CT/WR] Null path on generate method on current source code

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#336]
Possibly only when generating methods in the same class, and possibly related to the new WR feature which uses the context source code (which has no path).

```
Phpactor returned an error: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Phpactor\Rpc\Response\ReplaceFileSourceResponse::fromPathAndSource() m
ust be of the type string, null given, called in /home/daniel/www/phpactor/phpactor/lib/Rpc/Handler/GenerateMethodHandler.php on line 52 in /home/daniel/www/phpactor/phpactor/lib/Rpc/Response/ReplaceFileSourceResp
onse.php:25
Stack trace:
#0 /home/daniel/www/phpactor/phpactor/lib/Rpc/Handler/GenerateMethodHandler.php(52): Phpactor\Rpc\Response\ReplaceFileSourceResponse::fromPathAndSource(NULL, '<?php\n\nnamespac...')
#1 /home/daniel/www/phpactor/phpactor/lib/Rpc/RequestHandler/RequestHandler.php(39): Phpactor\Rpc\Handler\GenerateMethodHandler->handle(Array)
#2 /home/daniel/www/phpactor/phpactor/lib/Rpc/RequestHandler/ExceptionCatchingHandler.php(25): Phpactor\Rpc\RequestHandler\RequestHandler->handle(Object(Phpactor\Rpc\Request))
#3 /home/daniel/www/phpactor/phpactor/lib/Rpc/RequestHandler/LoggingHandler.php(39): Phpactor\Rpc\RequestHandler\Excep in /home/daniel/www/phpactor/phpactor/lib/Rpc/Response/ReplaceFileSourceResponse.php on line 2
5

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Phpactor\Rpc\Response\ReplaceFileSourceResponse::fromPathAndSource() must be of the type string, null g
iven, called in /home/daniel/www/phpactor/phpactor/lib/Rpc/Handler/GenerateMethodHandler.php on line 52 in /home/daniel/www/phpactor/phpactor/lib/Rpc/Response/ReplaceFileSourceResponse.php:25
Stack trace:
#0 /home/daniel/www/phpactor/phpactor/lib/Rpc/Handler/GenerateMethodHandler.php(52): Phpactor\Rpc\Response\ReplaceFileSourceResponse::fromPathAndSource(NULL, '<?php\n\nnamespac...')
#1 /home/daniel/www/phpactor/phpactor/lib/Rpc/RequestHandler/RequestHandler.php(39): Phpactor\Rpc\Handler\GenerateMethodHandler->handle(Array)
#2 /home/daniel/www/phpactor/phpactor/lib/Rpc/RequestHandler/ExceptionCatchingHandler.php(25): Phpactor\Rpc\RequestHandler\RequestHandler->handle(Object(Phpactor\Rpc\Request))
#3 /home/daniel/www/phpactor/phpactor/lib/Rpc/RequestHandler/LoggingHandler.php(39): Phpactor\Rpc\RequestHandler\Excep in /home/daniel/www/phpactor/phpactor/lib/Rpc/Response/ReplaceFileSourceResponse.php on line 2
5
```

**Comment by dantleech** [comment]
Fuxed
