### ISSUE TITLE
Go to definition error "Phpactor returned an error: PHP Fatal error"

### ISSUE THREAD

**Issue by lukepass** [phpactor/phpactor#398]
Hello,
since few updates every time i select "Go to definition" option an error occurs:

```
Phpactor returned an error: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Phpactor\WorseReflection\Core\SourceCode::fromP
athAndString() must be of the type string, null given, called in /home/luca/.dotfiles/.vim/bundle/phpactor/lib/Rpc/Handler/GotoDefinitionHandler.php on line 55 in /home/luca/.dotfiles/.vim/b
undle/phpactor/vendor/phpactor/worse-reflection/lib/Core/SourceCode.php:61
Stack trace:
#0 /home/luca/.dotfiles/.vim/bundle/phpactor/lib/Rpc/Handler/GotoDefinitionHandler.php(55): Phpactor\WorseReflection\Core\SourceCode::fromPathAndString(NULL, '<?php\n\nnamespac...')
#1 /home/luca/.dotfiles/.vim/bundle/phpactor/lib/Rpc/RequestHandler/RequestHandler.php(39): Phpactor\Rpc\Handler\GotoDefinitionHandler->handle(Array)
#2 /home/luca/.dotfiles/.vim/bundle/phpactor/lib/Rpc/RequestHandler/ExceptionCatchingHandler.php(25): Phpactor\Rpc\RequestHandler\RequestHandler->handle(Object(Phpactor\Rpc\Request))
#3 /home/luca/.dotfiles/.vim/bundle/phpactor/lib/Rpc/RequestHandler/LoggingHandler.php( in /home/luca/.dotfiles/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/SourceCode.php
on line 61
```

How can I get rid of it? It happens with every class and every file.

Thanks.

**Comment by dantleech** [comment]
That shouldn't be happening: works for me both on `master` and `develop` and in both VIM and Nvim.

You can debug by adding:

```
rpc.store_replay: true`
```

in `.phpactor.yml`.

Reproduce the error then run:

```
$ phpactor rpc --replay --verbose
```

and post the results back here.

It would seem that perhaps the VIM plugin isn't sending the path to the handler, f.e. here: https://github.com/phpactor/phpactor/blob/develop/plugin/phpactor.vim#L123

**Comment by lukepass** [comment]
How can I make your steps with VIM?

This is my VIM version:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 14 2018 14:26:24)
Included patches: 1-1605
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    +tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua               +ruby              +X11
+dialog_con_gui    +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             +xim
+digraphs          +modify_fname      +smartindent       +xpm
+dnd               +mouse             +startuptime       +xsmp_interact
-ebcdic            +mouseshape        +statusline        +xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm
```

Do I have to "compile" something after phpactor update or I just need to pull new changes?

Thanks.

**Comment by dantleech** [comment]
But it may also be worth checking you are using the latest version of the VIM plugin, as the `path` parameter in question was added on `2018-03-31`

**Comment by lukepass** [comment]
Yes, I updated it few days ago and it's the last version. This is the requested output:

```
[2018-04-11T14:44:34.689050+02:00] phpactor.DEBUG: REQUEST {"action":"context_menu","parameters":{"source":"<?php\n\nuse Symfony\\Component\\HttpKernel\\Kernel;\nuse Symfony\\Component\\Config\\Loader\\LoaderInterface;\n\nclass AppKernel extends Kernel\n{\n    public function registerBundles()\n    {\n        $bundles = array(\n            new Symfony\\Bundle\\FrameworkBundle\\FrameworkBundle(),\n            new Symfony\\Bundle\\SecurityBundle\\SecurityBundle(),\n            new Symfony\\Bundle\\TwigBundle\\TwigBundle(),\n            new Symfony\\Bundle\\MonologBundle\\MonologBundle(),\n            new Symfony\\Bundle\\SwiftmailerBundle\\SwiftmailerBundle(),\n            new Doctrine\\Bundle\\DoctrineBundle\\DoctrineBundle(),\n            new Sensio\\Bundle\\FrameworkExtraBundle\\SensioFrameworkExtraBundle(),\n\n            // Sonata Admin requirements\n            new Sonata\\DoctrineORMAdminBundle\\SonataDoctrineORMAdminBundle(),\n            new Sonata\\CoreBundle\\SonataCoreBundle(),\n            new Sonata\\BlockBundle\\SonataBlockBundle(),\n            new Knp\\Bundle\\MenuBundle\\KnpMenuBundle(),\n\n            // Sonata Admin\n            new Sonata\\AdminBundle\\SonataAdminBundle(),\n\n            // Sonata Media\n            new Sonata\\MediaBundle\\SonataMediaBundle(),\n            new Sonata\\EasyExtendsBundle\\SonataEasyExtendsBundle(),\n\n            // Sonata Media requirements\n            new JMS\\SerializerBundle\\JMSSerializerBundle(),\n\n            // Sonata Media entities\n            new Application\\Sonata\\MediaBundle\\ApplicationSonataMediaBundle(),\n\n            // Sonata User\n            new FOS\\UserBundle\\FOSUserBundle(),\n            new Sonata\\UserBundle\\SonataUserBundle('FOSUserBundle'),\n\n            // Sonata User entities\n            new Application\\Sonata\\UserBundle\\ApplicationSonataUserBundle(),\n\n            // Doctrine Extensions\n            new Stof\\DoctrineExtensionsBundle\\StofDoctrineExtensionsBundle(),\n\n            // Sonata Translation\n            new Sonata\\TranslationBundle\\SonataTranslationBundle(),\n\n            // Video\n            new Dubture\\FFmpegBundle\\DubtureFFmpegBundle(),\n\n            // Facebook Login\n            new Http\\HttplugBundle\\HttplugBundle(), // If you require the php-http/httplug-bundle package.\n            new HWI\\Bundle\\OAuthBundle\\HWIOAuthBundle(),\n\n            // FOS REST\n            new FOS\\RestBundle\\FOSRestBundle(),\n\n            // Slugify\n            new Cocur\\Slugify\\Bridge\\Symfony\\CocurSlugifyBundle(),\n\n            // CORS\n            new Nelmio\\CorsBundle\\NelmioCorsBundle(),\n\n            // this should be the last bundle\n            new AppBundle\\AppBundle(),\n        );\n\n        if (in_array($this->getEnvironment(), array('dev', 'test'), true)) {\n            $bundles[] = new Symfony\\Bundle\\DebugBundle\\DebugBundle();\n            $bundles[] = new Symfony\\Bundle\\WebProfilerBundle\\WebProfilerBundle();\n            $bundles[] = new Sensio\\Bundle\\DistributionBundle\\SensioDistributionBundle();\n            $bundles[] = new Sensio\\Bundle\\GeneratorBundle\\SensioGeneratorBundle();\n            $bundles[] = new Doctrine\\Bundle\\FixturesBundle\\DoctrineFixturesBundle();\n        }\n\n        return $bundles;\n    }\n\n    public function registerContainerConfiguration(LoaderInterface $loader)\n    {\n        $loader->load($this->getRootDir().'/config/config_'.$this->getEnvironment().'.yml');\n    }\n}","action":"goto_definition","offset":1653,"current_path":"/home/luca/Sites/portale_bnp/app/AppKernel.php"}} []
[2018-04-11T14:44:34.694568+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Statement\ClassDeclaration [] []
[2018-04-11T14:44:34.695608+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ArrayCreationExpression [] []
[2018-04-11T14:44:34.695643+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.695693+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.695764+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.695788+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.695844+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.695863+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.695913+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.695930+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.695978+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.695995+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.696053+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.696070+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.696137+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.696165+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.696250+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.696267+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.696313+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.696329+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.696375+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.696402+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.696456+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.696473+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.696552+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.696578+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.696623+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.696651+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.696738+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.696764+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.696830+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.696847+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.696891+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.696908+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.696953+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.696969+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.697035+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.697052+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.697097+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.697116+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.697164+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.697180+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.697225+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.697241+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.697285+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.697302+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.697347+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.697362+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.697407+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.697423+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.697468+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.697484+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.697606+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.697625+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.697672+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.697689+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.697733+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ObjectCreationExpression [] []
[2018-04-11T14:44:34.697750+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.698354+02:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\QualifiedName [] []
[2018-04-11T14:44:34.698433+02:00] phpactor.DEBUG: REQUEST {"action":"goto_definition","parameters":{"offset":1653,"source":"<?php\n\nuse Symfony\\Component\\HttpKernel\\Kernel;\nuse Symfony\\Component\\Config\\Loader\\LoaderInterface;\n\nclass AppKernel extends Kernel\n{\n    public function registerBundles()\n    {\n        $bundles = array(\n            new Symfony\\Bundle\\FrameworkBundle\\FrameworkBundle(),\n            new Symfony\\Bundle\\SecurityBundle\\SecurityBundle(),\n            new Symfony\\Bundle\\TwigBundle\\TwigBundle(),\n            new Symfony\\Bundle\\MonologBundle\\MonologBundle(),\n            new Symfony\\Bundle\\SwiftmailerBundle\\SwiftmailerBundle(),\n            new Doctrine\\Bundle\\DoctrineBundle\\DoctrineBundle(),\n            new Sensio\\Bundle\\FrameworkExtraBundle\\SensioFrameworkExtraBundle(),\n\n            // Sonata Admin requirements\n            new Sonata\\DoctrineORMAdminBundle\\SonataDoctrineORMAdminBundle(),\n            new Sonata\\CoreBundle\\SonataCoreBundle(),\n            new Sonata\\BlockBundle\\SonataBlockBundle(),\n            new Knp\\Bundle\\MenuBundle\\KnpMenuBundle(),\n\n            // Sonata Admin\n            new Sonata\\AdminBundle\\SonataAdminBundle(),\n\n            // Sonata Media\n            new Sonata\\MediaBundle\\SonataMediaBundle(),\n            new Sonata\\EasyExtendsBundle\\SonataEasyExtendsBundle(),\n\n            // Sonata Media requirements\n            new JMS\\SerializerBundle\\JMSSerializerBundle(),\n\n            // Sonata Media entities\n            new Application\\Sonata\\MediaBundle\\ApplicationSonataMediaBundle(),\n\n            // Sonata User\n            new FOS\\UserBundle\\FOSUserBundle(),\n            new Sonata\\UserBundle\\SonataUserBundle('FOSUserBundle'),\n\n            // Sonata User entities\n            new Application\\Sonata\\UserBundle\\ApplicationSonataUserBundle(),\n\n            // Doctrine Extensions\n            new Stof\\DoctrineExtensionsBundle\\StofDoctrineExtensionsBundle(),\n\n            // Sonata Translation\n            new Sonata\\TranslationBundle\\SonataTranslationBundle(),\n\n            // Video\n            new Dubture\\FFmpegBundle\\DubtureFFmpegBundle(),\n\n            // Facebook Login\n            new Http\\HttplugBundle\\HttplugBundle(), // If you require the php-http/httplug-bundle package.\n            new HWI\\Bundle\\OAuthBundle\\HWIOAuthBundle(),\n\n            // FOS REST\n            new FOS\\RestBundle\\FOSRestBundle(),\n\n            // Slugify\n            new Cocur\\Slugify\\Bridge\\Symfony\\CocurSlugifyBundle(),\n\n            // CORS\n            new Nelmio\\CorsBundle\\NelmioCorsBundle(),\n\n            // this should be the last bundle\n            new AppBundle\\AppBundle(),\n        );\n\n        if (in_array($this->getEnvironment(), array('dev', 'test'), true)) {\n            $bundles[] = new Symfony\\Bundle\\DebugBundle\\DebugBundle();\n            $bundles[] = new Symfony\\Bundle\\WebProfilerBundle\\WebProfilerBundle();\n            $bundles[] = new Sensio\\Bundle\\DistributionBundle\\SensioDistributionBundle();\n            $bundles[] = new Sensio\\Bundle\\GeneratorBundle\\SensioGeneratorBundle();\n            $bundles[] = new Doctrine\\Bundle\\FixturesBundle\\DoctrineFixturesBundle();\n        }\n\n        return $bundles;\n    }\n\n    public function registerContainerConfiguration(LoaderInterface $loader)\n    {\n        $loader->load($this->getRootDir().'/config/config_'.$this->getEnvironment().'.yml');\n    }\n}"}} []
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Phpactor\WorseReflection\Core\SourceCode::fromPathAndString() must be of the type string, null given, called in /home/luca/.dotfiles/.vim/bundle/phpactor/lib/Rpc/Handler/GotoDefinitionHandler.php on line 55 in /home/luca/.dotfiles/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/SourceCode.php:61
Stack trace:
#0 /home/luca/.dotfiles/.vim/bundle/phpactor/lib/Rpc/Handler/GotoDefinitionHandler.php(55): Phpactor\WorseReflection\Core\SourceCode::fromPathAndString(NULL, '<?php\n\nuse Symf...')
#1 /home/luca/.dotfiles/.vim/bundle/phpactor/lib/Rpc/RequestHandler/RequestHandler.php(39): Phpactor\Rpc\Handler\GotoDefinitionHandler->handle(Array)
#2 /home/luca/.dotfiles/.vim/bundle/phpactor/lib/Rpc/RequestHandler/ExceptionCatchingHandler.php(25): Phpactor\Rpc\RequestHandler\RequestHandler->handle(Object(Phpactor\Rpc\Request))
#3 /home/luca/.dotfiles/.vim/bundle/phpactor/lib/Rpc/RequestHandler/LoggingHandler.php( in /home/luca/.dotfiles/.vim/bundle/phpactor/vendor/phpactor/worse-reflection/lib/Core/SourceCode.php on line 61
```

**Comment by dantleech** [comment]
This is because you invoked it from the context menu (I invoke it with the shortcut). This is indeed an issue, will fix asap.

**Comment by lukepass** [comment]
It's working fine now!

**Comment by lukepass** [comment]
Hello, I have an error again with the same functionality:

```
Phpactor returned an error: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "XdebugHandler" from namespace "Composer\XdebugHandle
r".
Did you forget a "use" statement for another namespace? in /home/luca/.dotfiles/.vim/bundle/phpactor/lib/Phpactor.php:38
Stack trace:
#0 /home/luca/.dotfiles/.vim/bundle/phpactor/lib/Application.php(92): Phpactor\Phpactor::boot(Object(Symfony\Component\Console\Input\ArgvInput))
#1 /home/luca/.dotfiles/.vim/bundle/phpactor/lib/Application.php(28): Phpactor\Application->initialize(Object(Symfony\Component\Console\Input\ArgvInput))
#2 /home/luca/.dotfiles/.vim/bundle/phpactor/vendor/symfony/console/Application.php(130): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Compon
ent\Console\Output\ConsoleOutput))
#3 /home/luca/.dotfiles/.vim/bundle/phpactor/bin/phpactor(43): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\
Output\ConsoleOutput))
#4 {m in /home/luca/.dotfiles/.vim/bundle/phpactor/lib/Phpactor.php on line 38
```

**Comment by dantleech** [comment]
Looks like you need to run a `composer install` in your `phpactor` diretory.

How do you update Phpactor?

**Comment by lukepass** [comment]
Yes, that solved it!
I updated the plugin with `git submodule foreach git pull origin master` on my main bundle folder.

Thanks.

**Comment by dantleech** [comment]
ah ok, in order to have some stability you should ensure that `composer install` is executed after each update (or alternatively you can use `call phpactor#Update()` to update Phpactor which will take care of that).
