### ISSUE TITLE
XdebugHandler fatal error

### ISSUE THREAD

**Issue by fenetikm** [phpactor/phpactor#470]
I am currently getting the following when trying to complete:

```
Error detected while processing function phpactor#Complete[28]..phpactor#rpc:
line    7:
E5677: Error writing input to shell-command: EPIPE
Press ENTER or type command to continue
Phpactor returned an error: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "XdebugHandler" from namespace "Composer\XdebugHandler".
Did you forget a "use" statement for another namespace? in /Users/mjw/.config/nvim/plugged/phpactor/lib/Phpactor.php:38
Stack trace:
#0 /Users/mjw/.config/nvim/plugged/phpactor/lib/Application.php(97): Phpactor\Phpactor::boot(Object(Symfony\Component\Console\Input\ArgvInput), '/Users/mjw/.con...')
#1 /Users/mjw/.config/nvim/plugged/phpactor/lib/Application.php(34): Phpactor\Application->initialize(Object(Symfony\Component\Console\Input\ArgvInput))
#2 /Users/mjw/.config/nvim/plugged/phpactor/vendor/symfony/console/Application.php(130): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/mjw/.config/nvim/plugged/phpactor/bin/phpactor(43): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Cons in /Users/mjw/.config/nvim/plugged/phpactor/lib/Phpactor.php on line 38

Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "XdebugHandler" from namespace "Composer\XdebugHandler".
Did you forget a "use" statement for another namespace? in /Users/mjw/.config/nvim/plugged/phpactor/lib/Phpactor.php:38
Stack trace:
#0 /Users/mjw/.config/nvim/plugged/phpactor/lib/Application.php(97): Phpactor\Phpactor::boot(Object(Symfony\Component\Console\Input\ArgvInput), '/Users/mjw/.con...')
#1 /Users/mjw/.config/nvim/plugged/phpactor/lib/Application.php(34): Phpactor\Application->initialize(Object(Symfony\Component\Console\Input\ArgvInput))
#2 /Users/mjw/.config/nvim/plugged/phpactor/vendor/symfony/console/Application.php(130): Phpactor\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/mjw/.config/nvim/plugged/phpactor/bin/phpactor(43): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Cons in /Users/mjw/.config/nvim/plugged/phpactor/lib/Phpactor.php on line 38
Press ENTER or type command to continue
Error detected while processing function phpactor#Complete:
line   34:
E714: List required
```

This is on the latest version.

**Comment by dantleech** [comment]
That's a new PHP dependency - you will need to do a composer install in the plugin (or just :call phpactor#Update() )?

**Comment by fenetikm** [comment]
I did the `:call` thing but got the above. Composer install seems to have fixed it though 👍
