### ISSUE TITLE
RegexIterator::__construct(): Compilation failed

### ISSUE THREAD

**Issue by kermorgant** [phpactor/phpactor#543]
I got this error during auto-import of a completed class name with emacs.

![image](https://user-images.githubusercontent.com/10561580/43626941-cd742d4a-96fc-11e8-8488-fd80e33973e9.png)

Input givent to phpactor

```json
{
  "action": "import_class",
  "parameters": {
    "source": "<?php\n\nnamespace App\\Infrastructure\\Delivery\\Api\\Doctrine;\n\nuse ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Extension\\QueryCollectionExtensionInterface;\nuse ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Extension\\QueryItemExtensionInterface;\nuse ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Util\\QueryNameGeneratorInterface;\nuse Doctrine\\ORM\\QueryBuilder;\nuse Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface;\nuse Symfony\\Component\\Security\\Core\\Authorization\\AuthorizationCheckerInterface;\n\nfinal class CurrentUserExtension implements QueryCollectionExtensionInterface, QueryItemExtensionInterface\n{\n    private $tokenStorage;\n    private $authorizationChecker;\n\n    public function __construct(TokenStorageInterface $tokenStorage, AuthorizationCheckerInterface $checker)\n    {\n        $this->tokenStorage = $tokenStorage;\n        $this->authorizationChecker = $checker;\n    }\n\n    /**\n     * {@inheritdoc}\n     */\n    public function applyToCollection(\n        QueryBuilder $queryBuilder,\n        QueryNameGeneratorInterface $queryNameGenerator,\n        string $resourceClass,\n        string $operationName = null\n    ) {\n        $this->addWhere($queryBuilder, $resourceClass);\n    }\n\n    /**\n     * {@inheritdoc}\n     */\n    public function applyToItem(\n        QueryBuilder $queryBuilder,\n        QueryNameGeneratorInterface $queryNameGenerator,\n        string $resourceClass,\n        array $identifiers,\n        string $operationName = null,\n        array $context = []\n    ) {\n        $this->addWhere($queryBuilder, $resourceClass);\n    }\n\n    /**\n     *\n     * @param QueryBuilder $queryBuilder\n     * @param string       $resourceClass\n     */\n    private function addWhere(QueryBuilder $queryBuilder, string $resourceClass)\n    {\n        $user = $this->tokenStorage->getToken()->getUser();\n\n        if ($user instanceof User && Offer::class === $resourceClass && !$this->authorizationChecker->isGranted('ROLE_ADMIN')) {\n            $rootAlias = $queryBuilder->getRootAliases()[0];\n            $queryBuilder->andWhere(sprintf('%s.user = :current_user', $rootAlias));\n            $queryBuilder->setParameter('current_user', $user->getId());\n        }\n    }\n}\n",
    "offset": 1843,
    "path": "/home/mikael/workspace/simple-channels/simple-channels/api/src/Infrastructure/Delivery/Api/Doctrine/CurrentUserExtension.php",
    "name": "App\\Domain\\Model\\User\\User"
  }
}
```
output 

```json
{
  "action": "error",
  "parameters": {
    "message": "RegexIterator::__construct(): Compilation failed: PCRE does not support \\L, \\l, \\N{name}, \\U, or \\u at offset 18",
    "details": "0: RegexIterator::__construct(): Compilation failed: PCRE does not support \\L, \\l, \\N{name}, \\U, or \\u at offset 18\n#0 /home/mikael/src/phpactor/vendor/phpactor/source-code-filesystem/lib/Domain/FileList.php(73): RegexIterator->__construct(Object(Phpactor\\Filesystem\\Iterator\\AppendIterator), '{/App\\\\Domain\\\\Mo...')\n#1 /home/mikael/src/phpactor/lib/Extension/SourceCodeFilesystem/SourceCodeFilestem/Application/ClassSearch.php(41): Phpactor\\Filesystem\\Domain\\FileList->named('App\\\\Domain\\\\Mode...')\n#2 /home/mikael/src/phpactor/lib/Extension/CodeTransform/Rpc/ImportClassHandler.php(144): Phpactor\\Extension\\SourceCodeFilesystem\\SourceCodeFilestem\\Application\\ClassSearch->classSearch('composer', 'App\\\\Domain\\\\Mode...')\n#3 /home/mikael/src/phpactor/lib/Extension/CodeTransform/Rpc/ImportClassHandler.php(75): Phpactor\\Extension\\CodeTransform\\Rpc\\ImportClassHandler->suggestions('App\\\\Domain\\\\Mode...')\n#4 /home/mikael/src/phpactor/lib/Extension/Rpc/RequestHandler/RequestHandler.php(33): Phpactor\\Extension\\CodeTransform\\Rpc\\ImportClassHandler->handle(Array)\n#5 /home/mikael/src/phpactor/lib/Extension/Rpc/RequestHandler/ExceptionCatchingHandler.php(25): Phpactor\\Extension\\Rpc\\RequestHandler\\RequestHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#6 /home/mikael/src/phpactor/lib/Extension/Rpc/RequestHandler/LoggingHandler.php(39): Phpactor\\Extension\\Rpc\\RequestHandler\\ExceptionCatchingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#7 /home/mikael/src/phpactor/lib/Extension/Rpc/Command/RpcCommand.php(80): Phpactor\\Extension\\Rpc\\RequestHandler\\LoggingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#8 /home/mikael/src/phpactor/lib/Extension/Rpc/Command/RpcCommand.php(63): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->processRequest(Object(Phpactor\\Extension\\Rpc\\Request))\n#9 /home/mikael/src/phpactor/vendor/symfony/console/Command/Command.php(264): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 /home/mikael/src/phpactor/vendor/symfony/console/Application.php(874): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 /home/mikael/src/phpactor/vendor/symfony/console/Application.php(228): Symfony\\Component\\Console\\Application->doRunCommand(Object(Phpactor\\Extension\\Rpc\\Command\\RpcCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 /home/mikael/src/phpactor/lib/Application.php(48): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 /home/mikael/src/phpactor/vendor/symfony/console/Application.php(130): Phpactor\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 /home/mikael/src/phpactor/bin/phpactor(43): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 {main}"
  }
}
```

```
Phpactor: Info
----
Version: bc4ba6e (il y a 11 heures) Completion-Fixed-class-member-container-resolution-accuracy-542
Diagnostics
-----------
[✔] Composer detected - faster class location and more features!
[✔] XDebug is disabled. XDebug has a negative effect on performance.
[✘] Git not detected. Some operations which would have been better scoped to your project repository will now include vendor paths.
```

**Comment by dantleech** [comment]
Fixed, but note that this will not work for your use case -- class search does not work by FQN, only short name (it's currently filebased).

**Comment by kermorgant** [comment]
Thanks ! works fine now (I'm not using class search here)
