### ISSUE TITLE
attempt at writing file in vendor fails because of permission issue

### ISSUE THREAD

**Issue by kermorgant** [phpactor/phpactor#598]
I just tried the replace reference action on a class like the one below, and got an error message saying

``
edebug-signal: Warning: file_put_contents(/path/api/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php): failed to open stream: Permission denied
``

As I'm using docker when doing composer install for my project, the vendor files are write protected and phpactor can't change them, thus the issue.

Here's what I had from phpactor's output 

```
    "message": "Warning: file_put_contents(/path/api/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php): failed to open stream: Permission denied",
    "details": "0: Warning: file_put_contents(/path/api/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php): failed to open stream: Permission denied\n#0 /src/phpactor.el/vendor/phpactor/phpactor/lib/Extension/ClassMover/Application/ClassMemberReferences.php(77): Phpactor\\Extension\\ClassMover\\Application\\ClassMemberReferences->referencesInFile(Object(Phpactor\\Filesystem\\Adapter\\Simple\\SimpleFilesystem), Object(Phpactor\\Filesystem\\Domain\\FilePath), 'App\\\\Infrastruct...', 'createProductAt...', 'method', 'createProductAt...', false)\n#1 /src/phpactor.el/vendor/phpactor/phpactor/lib/Extension/ClassMover/Rpc/ReferencesHandler.php(249): Phpactor\\Extension\\ClassMover\\Application\\ClassMemberReferences->findOrReplaceReferences('git', 'App\\\\Infrastruct...', 'createProductAt...', 'method', 'createProductAt...')\n#2 /src/phpactor.el/vendor/phpactor/phpactor/lib/Extension/ClassMover/Rpc/ReferencesHandler.php(277): Phpactor\\Extension\\ClassMover\\Rpc\\ReferencesHandler->memberReferences('git', Object(Phpactor\\WorseReflection\\Core\\Inference\\SymbolContext), 'method', '<?php\\n\\nnamespac...', 'createProductAt...')\n#3 /src/phpactor.el/vendor/phpactor/phpactor/lib/Extension/ClassMover/Rpc/ReferencesHandler.php(185): Phpactor\\Extension\\ClassMover\\Rpc\\ReferencesHandler->performFindOrReplaceReferences(Object(Phpactor\\WorseReflection\\Core\\Inference\\SymbolContext), 'git', '<?php\\n\\nnamespac...', 'createProductAt...')\n#4 /src/phpactor.el/vendor/phpactor/phpactor/lib/Extension/ClassMover/Rpc/ReferencesHandler.php(144): Phpactor\\Extension\\ClassMover\\Rpc\\ReferencesHandler->replaceReferences(Object(Phpactor\\WorseReflection\\Core\\Inference\\SymbolContext), 'git', 'createProductAt...', '/wo...', '<?php\\n\\nnamespac...')\n#5 /src/phpactor.el/vendor/phpactor/phpactor/lib/Extension/Rpc/RequestHandler/RequestHandler.php(33): Phpactor\\Extension\\ClassMover\\Rpc\\ReferencesHandler->handle(Array)\n#6 /src/phpactor.el/vendor/phpactor/phpactor/lib/Extension/Rpc/RequestHandler/ExceptionCatchingHandler.php(25): Phpactor\\Extension\\Rpc\\RequestHandler\\RequestHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#7 /src/phpactor.el/vendor/phpactor/phpactor/lib/Extension/Rpc/RequestHandler/LoggingHandler.php(39): Phpactor\\Extension\\Rpc\\RequestHandler\\ExceptionCatchingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#8 /src/phpactor.el/vendor/phpactor/phpactor/lib/Extension/Rpc/Command/RpcCommand.php(82): Phpactor\\Extension\\Rpc\\RequestHandler\\LoggingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#9 /src/phpactor.el/vendor/phpactor/phpactor/lib/Extension/Rpc/Command/RpcCommand.php(64): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->processRequest(Object(Phpactor\\Extension\\Rpc\\Request))\n#10 /src/phpactor.el/vendor/symfony/console/Command/Command.php(251): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 /src/phpactor.el/vendor/symfony/console/Application.php(946): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 /src/phpactor.el/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Phpactor\\Extension\\Rpc\\Command\\RpcCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 /src/phpactor.el/vendor/phpactor/phpactor/lib/Application.php(48): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 /src/phpactor.el/vendor/symfony/console/Application.php(148): Phpactor\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 /src/phpactor.el/vendor/phpactor/phpactor/bin/phpactor(43): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 {main}"
  }
```

**Comment by kermorgant** [comment]
Hmm, it doesn't look like that.

The class in which I tried to rename a method looks like this 


```php
<?php

namespace App\Fixtures\Product\Products;

use Doctrine\Common\Persistence\ObjectManager;

abstract class AbstractProductFixture extends Fixture
{
    protected function createProduct(string $code, User $creator): Product
    {
        //code
    }
}
```

Probably because this error halts the entire operation, the references are not updated

**Comment by dantleech** [comment]
probably shouldn't be trying to update Doctrine Fixtures Bundle?

It should run with `filesystem: git`, so surprised it is updating a vendor file?

**Comment by kermorgant** [comment]
agreed, vendors should not be changed.

but here, git is not detected because the php folder is a under a subfolder of the one holding .git.

**Comment by kermorgant** [comment]
I changed the working-directory configuration so that .git would be detected (adding ``autoload:`` configuration in phpactor.yml) but the issue remains

**Comment by kermorgant** [comment]
Hmm, this is old stuff. Better to close it and reopen if needed

**Comment by dantleech** [comment]
Pretty sure this is still an issue, but always happy for issues to be closed :see_no_evil:
