### ISSUE TITLE
[LSP / SignatureHelper] Wrong return hint ReflectionInterface ?

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#752]
As discussed on slack, I tried through Coc.vim to send a request `:call CocRequest('phpactor', 'textDocument/signatureHelp', {"textDocument":{"uri":"file:///home/talus/dev/foodcheri/back/api/app/src/Kitchen/DataProvider/ProductPublicationCollectionProvider.php"},"position":{"character":47,"line":60}})`

And I stumbled upon a type error from PHP. Here are the logs ;

```
[2019-04-03 15:32:52] phpactor.INFO: REQUEST {"jsonrpc":"2.0","id":37,"method":"textDocument/signatureHelp","params":{"textDocument":{"uri":"file:///home/talus/dev/foodcheri/back/api/app/src/Kitchen/DataProvider/ProductPublicationCollectionProvider.php"},"position":{"character":47,"line":60}}} []
[2019-04-03 15:32:54] phpactor.ERROR: Return value of Phpactor\WorseReflection\Core\Reflector\ClassReflector\MemonizedReflector::reflectClass() must implement interface Phpactor\WorseReflection\Core\Reflection\ReflectionClass, instance of Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionInterface returned {"class":"TypeError","trace":"#0 /home/talus/.config/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CompositeReflector.php(48): Phpactor\\WorseReflection\\Core\\Reflector\\ClassReflector\\MemonizedReflector->reflectClass(Object(Phpactor\\WorseReflection\\Core\\ClassName))\n#1 /home/talus/.config/nvim/plugged/phpactor/vendor/phpactor/completion/lib/Bridge/TolerantParser/WorseReflection/WorseSignatureHelper.php(110): Phpactor\\WorseReflection\\Core\\Reflector\\CompositeReflector->reflectClass(Object(Phpactor\\WorseReflection\\Core\\ClassName))\n#2 /home/talus/.config/nvim/plugged/phpactor/vendor/phpactor/completion/lib/Core/ChainSignatureHelper.php(36): Phpactor\\Completion\\Bridge\\TolerantParser\\WorseReflection\\WorseSignatureHelper->signatureHelp(Object(Phpactor\\TextDocument\\StandardTextDocument), Object(Phpactor\\TextDocument\\ByteOffset))\n#3 /home/talus/.config/nvim/plugged/phpactor/extensions/phpactor/language-server-completion-extension/lib/Handler/SignatureHelpHandler.php(59): Phpactor\\Completion\\Core\\ChainSignatureHelper->signatureHelp(Object(Phpactor\\TextDocument\\StandardTextDocument), Object(Phpactor\\TextDocument\\ByteOffset))\n#4 /home/talus/.config/nvim/plugged/phpactor/extensions/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MethodDispatcher.php(54): Phpactor\\Extension\\LanguageServerCompletion\\Handler\\SignatureHelpHandler->signatureHelp(Object(LanguageServerProtocol\\TextDocumentItem), Object(LanguageServerProtocol\\Position))\n#5 /home/talus/.config/nvim/plugged/phpactor/extensions/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/ErrorCatchingDispatcher.php(37): Phpactor\\LanguageServer\\Core\\Dispatcher\\Dispatcher\\MethodDispatcher->dispatch(Object(Phpactor\\LanguageServer\\Core\\Handler\\Handlers), Object(Phpactor\\LanguageServer\\Core\\Rpc\\RequestMessage))\n#6 /home/talus/.config/nvim/plugged/phpactor/extensions/phpactor/language-server/lib/Core/Server/ApplicationContainer.php(56): Phpactor\\LanguageServer\\Core\\Dispatcher\\Dispatcher\\ErrorCatchingDispatcher->dispatch(Object(Phpactor\\LanguageServer\\Core\\Handler\\Handlers), Object(Phpactor\\LanguageServer\\Core\\Rpc\\RequestMessage))\n#7 /home/talus/.config/nvim/plugged/phpactor/extensions/phpactor/language-server/lib/Core/Server/LanguageServer.php(231): Phpactor\\LanguageServer\\Core\\Server\\ApplicationContainer->dispatch(Object(Phpactor\\LanguageServer\\Core\\Rpc\\RequestMessage))\n#8 /home/talus/.config/nvim/plugged/phpactor/extensions/phpactor/language-server/lib/Core/Server/Parser/LanguageServerProtocolParser.php(69): Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->Phpactor\\LanguageServer\\Core\\Server\\{closure}(Object(Phpactor\\LanguageServer\\Core\\Rpc\\Request))\n#9 /home/talus/.config/nvim/plugged/phpactor/extensions/phpactor/language-server/lib/Core/Server/LanguageServer.php(243): Phpactor\\LanguageServer\\Core\\Server\\Parser\\LanguageServerProtocolParser->feed('Content-Length:...')\n#10 /home/talus/.config/nvim/plugged/phpactor/extensions/phpactor/language-server/lib/Core/Server/LanguageServer.php(195): Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->handle(Object(Phpactor\\LanguageServer\\Core\\Server\\StreamProvider\\Connection))\n#11 [internal function]: Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->Phpactor\\LanguageServer\\Core\\Server\\{closure}()\n#12 /home/talus/.config/nvim/plugged/phpactor/extensions/amphp/amp/lib/Coroutine.php(76): Generator->send('Content-Length:...')\n#13 /home/talus/.config/nvim/plugged/phpactor/extensions/amphp/amp/lib/Internal/Placeholder.php(130): Amp\\Coroutine->Amp\\{closure}(NULL, 'Content-Length:...')\n#14 /home/talus/.config/nvim/plugged/phpactor/extensions/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve('Content-Length:...')\n#15 /home/talus/.config/nvim/plugged/phpactor/extensions/amphp/byte-stream/lib/ResourceInputStream.php(99): Amp\\Deferred->resolve('Content-Length:...')\n#16 /home/talus/.config/nvim/plugged/phpactor/extensions/amphp/amp/lib/Loop/NativeDriver.php(206): Amp\\ByteStream\\ResourceInputStream::Amp\\ByteStream\\{closure}('a', Resource id #1, NULL)\n#17 /home/talus/.config/nvim/plugged/phpactor/extensions/amphp/amp/lib/Loop/NativeDriver.php(97): Amp\\Loop\\NativeDriver->selectStreams(Array, Array, -0.001)\n#18 /home/talus/.config/nvim/plugged/phpactor/extensions/amphp/amp/lib/Loop/Driver.php(134): Amp\\Loop\\NativeDriver->dispatch(true)\n#19 /home/talus/.config/nvim/plugged/phpactor/extensions/amphp/amp/lib/Loop/Driver.php(72): Amp\\Loop\\Driver->tick()\n#20 /home/talus/.config/nvim/plugged/phpactor/extensions/amphp/amp/lib/Loop.php(84): Amp\\Loop\\Driver->run()\n#21 /home/talus/.config/nvim/plugged/phpactor/extensions/phpactor/language-server/lib/Core/Server/LanguageServer.php(166): Amp\\Loop::run(Object(Closure))\n#22 /home/talus/.config/nvim/plugged/phpactor/extensions/phpactor/language-server/lib/Core/Server/LanguageServer.php(115): Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->doStart()\n#23 /home/talus/.config/nvim/plugged/phpactor/extensions/phpactor/language-server-extension/lib/Command/StartCommand.php(52): Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->start()\n#24 /home/talus/.config/nvim/plugged/phpactor/vendor/symfony/console/Command/Command.php(255): Phpactor\\Extension\\LanguageServer\\Command\\StartCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#25 /home/talus/.config/nvim/plugged/phpactor/vendor/symfony/console/Application.php(908): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#26 /home/talus/.config/nvim/plugged/phpactor/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Phpactor\\Extension\\LanguageServer\\Command\\StartCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#27 /home/talus/.config/nvim/plugged/phpactor/lib/Application.php(50): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#28 /home/talus/.config/nvim/plugged/phpactor/vendor/symfony/console/Application.php(145): Phpactor\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#29 /home/talus/.config/nvim/plugged/phpactor/bin/phpactor(41): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#30 {main}"} []
```

I'm pretty sure I'm up to date (from develop), same for extensions (freshly installed yesterday from `phpactor extensions:install` after a call to `update`) and I wanted to check how I could ask the signature help from coc. I may have messed up the arguments (as I saw it should be almost the same as the goto definition one ?).

**Comment by dantleech** [comment]
Problem seems to be here:

https://github.com/phpactor/completion/blob/master/lib/Bridge/TolerantParser/WorseReflection/WorseSignatureHelper.php#L110

It calls `reflectClass` which expects the instance to be a class, but it got an interface instead. I think we could use `reflectClassLike` instead - we only check methods and these are common to all.
