### ISSUE TITLE
Error going to a definition

### ISSUE THREAD

**Issue by FatBoyXPC** [phpactor/phpactor#754]
I've had trouble going to some definitions before, and I was finally able to make another one happen!

Given this class:

```php
<?php

namespace A3\Helpers\Editors;

use A3\AWS\SNS\Message;
use A3\Models\Clients\Client;
use A3\Models\People\Tag;
use A3\Models\Product\Product;
use A3\Helpers\Editor;
use A3\System\Communication\FirebaseConfiguration;
use A3\System\Database;
use A3\System\Factories\Communication\Twilio_Client;

class Push extends Editor
{
```

I put the cursor on `Editor` on the line defining the class, and I get this error:

```json
{"version":"1.0.0","action":"error","parameters":{"message":"Do not know how to goto definition of symbol type \"<unknown>\", Word \"A3\\Helpers\\Editors\\private\" could not be resolved to a class","details":"0: Do not know how to goto definition of symbol type \"<unknown>\", Word \"A3\\Helpers\\Editors\\private\" could not be resolved to a class\n#0 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/phpactor\/reference-finder-rpc-extension\/lib\/Handler\/GotoDefinitionHandler.php(55): Phpactor\\ReferenceFinder\\ChainDefinitionLocationProvider->locateDefinition(Object(Phpactor\\TextDocument\\StandardTextDocument), Object(Phpactor\\TextDocument\\ByteOffset))\n#1 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/RequestHandler\/RequestHandler.php(33): Phpactor\\Extension\\ReferenceFinderRpc\\Handler\\GotoDefinitionHandler->handle(Array)\n#2 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/RequestHandler\/ExceptionCatchingHandler.php(25): Phpactor\\Extension\\Rpc\\RequestHandler\\RequestHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#3 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/RequestHandler\/LoggingHandler.php(39): Phpactor\\Extension\\Rpc\\RequestHandler\\ExceptionCatchingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#4 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/Command\/RpcCommand.php(86): Phpactor\\Extension\\Rpc\\RequestHandler\\LoggingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#5 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/Command\/RpcCommand.php(68): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->processRequest(Object(Phpactor\\Extension\\Rpc\\Request))\n#6 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/symfony\/console\/Command\/Command.php(255): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#7 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/symfony\/console\/Application.php(901): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/symfony\/console\/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Phpactor\\Extension\\Rpc\\Command\\RpcCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/lib\/Application.php(50): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/symfony\/console\/Application.php(145): Phpactor\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/bin\/phpactor(41): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 {main}"}}
```

Yes, the `Editor` class exists in the expected class and namespace.

**Comment by dantleech** [comment]
> Word \"A3\\Helpers\\Editors\\private\" could not be resolved to a clas

Any idea where this `private` comes from? @Taluu you get this also?

Sounds like the offset is incorrect. Would you be able to provide the full `phpactor rpc --replay --verbose` for this?

**Comment by Taluu** [comment]
I had this, but I can't remember when, as I'm now using the language server...

I'll try to check whenever I reactivate the rpc completion.

**Comment by elythyr** [comment]
@FatBoyXPC can you reproduce it if you delete the body of the `Push` class ?
Is there anything `private` there ?
Can you reproduce it with a simpler example that we could all reproduce ?

I tried to create a new project with the same hierarchy but I don't have any issue.

**Comment by FatBoyXPC** [comment]
Here are the current class contents:

```php
<?php

namespace A3\Helpers\Editors;

class Push extends Editor
{
}
```

I'm still putting the cursor on `Editor` and doing Go To Definition. Here's the output of `phpactor rpc --replay --verbose`:

```sh
➜  phpactor git:(develop) ✗ bin/phpactor rpc --replay --verbose 
[2019-06-30 20:24:39] phpactor.DEBUG: Resolved path "%cache%/replay.json" to "/home/james/.cache/phpactor/replay.json" [] []
[2019-06-30 20:24:39] phpactor.DEBUG: REQUEST {"action":"goto_definition","parameters":{"language":"php","source":"<?php\n\nnamespace A3\\Helpers\\Editors;\n\nclass Push extends Editor\n{\n}","offset":67,"target":"focused_window","path":"/home/james/dev/aware3/web/classes/A3/Helpers/Editors/Push.php"}} []
[2019-06-30 20:24:39] phpactor.DEBUG: Resolved path "%application_root%/vendor/jetbrains/phpstorm-stubs" to "/home/james/dotfiles/vim/plugged/phpactor/vendor/jetbrains/phpstorm-stubs" [] []
[2019-06-30 20:24:39] phpactor.DEBUG: Resolved path "%cache%/worse-reflection" to "/home/james/.cache/phpactor/worse-reflection" [] []
[2019-06-30 20:24:39] phpactor.DEBUG: Resolved path "%project_root%/vendor/autoload.php" to "/home/james/dotfiles/vim/plugged/phpactor/vendor/autoload.php" [] []
[2019-06-30 20:24:39] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\ClassMembersNode [] []
[2019-06-30 20:24:39] phpactor.INFO: Could not locate definition ""Do not know how to goto definition of symbol type "<unknown>"" [] []
PHP Notice:  Uninitialized string offset: 67 in /home/james/dotfiles/vim/plugged/phpactor/vendor/phpactor/worse-reference-finders/lib/WorsePlainTextClassDefinitionLocator.php on line 77
PHP Notice:  Uninitialized string offset: 68 in /home/james/dotfiles/vim/plugged/phpactor/vendor/phpactor/worse-reference-finders/lib/WorsePlainTextClassDefinitionLocator.php on line 89
[2019-06-30 20:24:39] phpactor.INFO: Could not locate definition ""Word "A3\Helpers\Editors\}" could not be resolved to a class" [] []
[2019-06-30 20:24:39] phpactor.ERROR: RESPONSE {"action":"error","parameters":{"message":"Do not know how to goto definition of symbol type \"<unknown>\", Word \"A3\\Helpers\\Editors\\}\" could not be resolved to a class","details":"0: Do not know how to goto definition of symbol type \"<unknown>\", Word \"A3\\Helpers\\Editors\\}\" could not be resolved to a class\n#0 /home/james/dotfiles/vim/plugged/phpactor/vendor/phpactor/reference-finder-rpc-extension/lib/Handler/GotoDefinitionHandler.php(57): Phpactor\\ReferenceFinder\\ChainDefinitionLocationProvider->locateDefinition(Object(Phpactor\\TextDocument\\StandardTextDocument), Object(Phpactor\\TextDocument\\ByteOffset))\n#1 /home/james/dotfiles/vim/plugged/phpactor/vendor/phpactor/rpc-extension/lib/RequestHandler/RequestHandler.php(33): Phpactor\\Extension\\ReferenceFinderRpc\\Handler\\GotoDefinitionHandler->handle(Array)\n#2 /home/james/dotfiles/vim/plugged/phpactor/vendor/phpactor/rpc-extension/lib/RequestHandler/ExceptionCatchingHandler.php(25): Phpactor\\Extension\\Rpc\\RequestHandler\\RequestHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#3 /home/james/dotfiles/vim/plugged/phpactor/vendor/phpactor/rpc-extension/lib/RequestHandler/LoggingHandler.php(39): Phpactor\\Extension\\Rpc\\RequestHandler\\ExceptionCatchingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#4 /home/james/dotfiles/vim/plugged/phpactor/vendor/phpactor/rpc-extension/lib/Command/RpcCommand.php(86): Phpactor\\Extension\\Rpc\\RequestHandler\\LoggingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#5 /home/james/dotfiles/vim/plugged/phpactor/vendor/phpactor/rpc-extension/lib/Command/RpcCommand.php(68): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->processRequest(Object(Phpactor\\Extension\\Rpc\\Request))\n#6 /home/james/dotfiles/vim/plugged/phpactor/vendor/symfony/console/Command/Command.php(255): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#7 /home/james/dotfiles/vim/plugged/phpactor/vendor/symfony/console/Application.php(908): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 /home/james/dotfiles/vim/plugged/phpactor/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Phpactor\\Extension\\Rpc\\Command\\RpcCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 /home/james/dotfiles/vim/plugged/phpactor/lib/Application.php(50): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 /home/james/dotfiles/vim/plugged/phpactor/vendor/symfony/console/Application.php(145): Phpactor\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 /home/james/dotfiles/vim/plugged/phpactor/bin/phpactor(41): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 {main}"}} []
{"version":"1.0.0","action":"error","parameters":{"message":"Do not know how to goto definition of symbol type \"<unknown>\", Word \"A3\\Helpers\\Editors\\}\" could not be resolved to a class","details":"0: Do not know how to goto definition of symbol type \"<unknown>\", Word \"A3\\Helpers\\Editors\\}\" could not be resolved to a class\n#0 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/phpactor\/reference-finder-rpc-extension\/lib\/Handler\/GotoDefinitionHandler.php(57): Phpactor\\ReferenceFinder\\ChainDefinitionLocationProvider->locateDefinition(Object(Phpactor\\TextDocument\\StandardTextDocument), Object(Phpactor\\TextDocument\\ByteOffset))\n#1 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/RequestHandler\/RequestHandler.php(33): Phpactor\\Extension\\ReferenceFinderRpc\\Handler\\GotoDefinitionHandler->handle(Array)\n#2 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/RequestHandler\/ExceptionCatchingHandler.php(25): Phpactor\\Extension\\Rpc\\RequestHandler\\RequestHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#3 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/RequestHandler\/LoggingHandler.php(39): Phpactor\\Extension\\Rpc\\RequestHandler\\ExceptionCatchingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#4 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/Command\/RpcCommand.php(86): Phpactor\\Extension\\Rpc\\RequestHandler\\LoggingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#5 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/Command\/RpcCommand.php(68): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->processRequest(Object(Phpactor\\Extension\\Rpc\\Request))\n#6 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/symfony\/console\/Command\/Command.php(255): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#7 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/symfony\/console\/Application.php(908): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/symfony\/console\/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Phpactor\\Extension\\Rpc\\Command\\RpcCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/lib\/Application.php(50): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/vendor\/symfony\/console\/Application.php(145): Phpactor\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/home\/james\/dotfiles\/vim\/plugged\/phpactor\/bin\/phpactor(41): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 {main}"}}
```

**Comment by FatBoyXPC** [comment]
Well this is interesting, when I can `:call phpactor#Status()` it looks like composer isn't found?

```sh
Info
----
Version: 2a14f2a (4 weeks ago) Adds-fzf-support-for-list-input-769
Work dir: /home/james/dev/aware3/web

Diagnostics
-----------
[✔] Git detected - enables faster refactorings in your repository scope!
[✔] XDebug is disabled. XDebug has a negative effect on performance.
[✘] Composer not found - some functionality will not be available (e.g. class creation) and class location will fallback to scanning the
filesystem - this can be slow. Make sure you've run `composer install` in your project!
Config files
------------
[✘] /home/james/.config/phpactor/phpactor.json
[✔] /home/james/.config/phpactor/phpactor.yml
[✘] /home/james/dev/aware3/web/.phpactor.json
[✘] /home/james/dev/aware3/web/.phpactor.yml
Press ENTER or type command to continue
```

**Comment by Einenlum** [comment]
@FatBoyXPC Actually here it's different. `Editors` does not match `Editor`.

**Comment by FatBoyXPC** [comment]
I still don't understand why it would be trying to go to `Editors` instead of `Editor`.

**Comment by elythyr** [comment]
@dantleech that might came from the interesting offset finder ?
If it can't resolve `'Editor` on the class declaration, the previous interesting offset might be the namespace statement ?

The class Editor is indeed in the exact same namespace that this class ?

**Comment by dantleech** [comment]
can#'t reproduce this, closing for now. open again if it is still happening
