### ISSUE TITLE
Listing extensions command shown on docs is not found

### ISSUE THREAD

**Issue by ilkermutlu** [phpactor/phpactor#761]
[https://phpactor.github.io/phpactor/extensions.html#usage](https://phpactor.github.io/phpactor/extensions.html#usage) page says `To list all available extensions` run `phpactor extension:list`

The output is:
```
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "extension" namespace.
```

**Comment by dantleech** [comment]
Are you running the latest version of Phpactor? the `master` branch should have this command.

in VIM you should be able to run `:call phpactor#Update()`

**Comment by ilkermutlu** [comment]
Already on master. The output of `:call phpactor#Update()` is

```
Already on 'master'
Your branch is up to date with 'origin/master'.
From https://github.com/phpactor/phpactor
 * branch            master     -> FETCH_HEAD
Already up to date.
```

Rather interestingly, without changing anything, now the error message is:

```
PHP Fatal error:  Uncaught OutOfBoundsException: Required package "phpactor/phpactor" is not installed: cannot detect its version in /Users/ilker/.local/share/nvim/plugged/phpactor/vendor/ocramius/package-versions/src/PackageVersions/Fallba
ckVersions.php:44
Stack trace:
#0 /Users/ilker/.local/share/nvim/plugged/phpactor/vendor/ocramius/package-versions/src/PackageVersions/Versions.php(28): PackageVersions\FallbackVersions::getVersion('phpactor/phpact...')
#1 /Users/ilker/.local/share/nvim/plugged/phpactor/lib/Application.php(31): PackageVersions\Versions::getVersion('phpactor/phpact...')
#2 /Users/ilker/.local/share/nvim/plugged/phpactor/bin/phpactor(37): Phpactor\Application->__construct('/Users/ilker/.l...')
#3 {main}
  thrown in /Users/ilker/.local/share/nvim/plugged/phpactor/vendor/ocramius/package-versions/src/PackageVersions/FallbackVersions.php on line 44

Fatal error: Uncaught OutOfBoundsException: Required package "phpactor/phpactor" is not installed: cannot detect its version in /Users/ilker/.local/share/nvim/plugged/phpactor/vendor/ocramius/package-versions/src/PackageVersions/FallbackVer
sions.php on line 44

OutOfBoundsException: Required package "phpactor/phpactor" is not installed: cannot detect its version in /Users/ilker/.local/share/nvim/plugged/phpactor/vendor/ocramius/package-versions/src/PackageVersions/FallbackVersions.php on line 44

Call Stack:
    0.0004     396184   1. {main}() /Users/ilker/.local/share/nvim/plugged/phpactor/bin/phpactor:0
    0.0097    1384144   2. Phpactor\Application->__construct() /Users/ilker/.local/share/nvim/plugged/phpactor/bin/phpactor:37
    0.0098    1386912   3. PackageVersions\Versions::getVersion() /Users/ilker/.local/share/nvim/plugged/phpactor/lib/Application.php:31
    0.0100    1396264   4. PackageVersions\FallbackVersions::getVersion() /Users/ilker/.local/share/nvim/plugged/phpactor/vendor/ocramius/package-versions/src/PackageVersions/Versions.php:28
```

**Comment by ilkermutlu** [comment]
Closing this as there is no traction.
