### ISSUE TITLE
[bug] phpactor/indexer extension should required phpactor/language-server-extension

### ISSUE THREAD

**Issue by elythyr** [phpactor/phpactor#939]
I wanted to install the indexer extension, so I follow the doc with `phpactor extension:install "phpactor/indexer"`

It seems OK, no error or anything composer did its part.
Then I try `phpactor extension:list`:
```bash
~/work/phpactor/phpactor (develop) ✗                                                                                 
➜ phpactor extension:list                                                                                  
PHP Fatal error:  Uncaught Error: Class 'Phpactor\Extension\LanguageServer\LanguageServerExtension' not found in /media/ewilan/php/phpactor/phpactor/extensions/phpactor/indexer/lib/Extension/IndexerExtension.php:1
85                                                          
Stack trace:                                         
#0 /media/ewilan/php/phpactor/phpactor/extensions/phpactor/indexer/lib/Extension/IndexerExtension.php(72): Phpactor\Indexer\Extension\IndexerExtension->registerLanguageServer()
#1 /media/ewilan/php/phpactor/phpactor/lib/Phpactor.php(141): Phpactor\Indexer\Extension\IndexerExtension->load()
#2 /media/ewilan/php/phpactor/phpactor/lib/Application.php(108): Phpactor\Phpactor::boot()          
#3 /media/ewilan/php/phpactor/phpactor/lib/Application.php(37): Phpactor\Application->initialize()
#4 /media/ewilan/php/phpactor/phpactor/vendor/symfony/console/Application.php(147): Phpactor\Application->doRun()
#5 /media/ewilan/php/phpactor/phpactor/bin/phpactor(41): Symfony\Component\Console\Application->run()     
#6 {main}                                                                                      
  thrown in /media/ewilan/php/phpactor/phpactor/extensions/phpactor/indexer/lib/Extension/IndexerExtension.php on line 185
```

So it seems there is a dependency between the two that should not be there.
I guess it should be removed in order to be able to use the indexer with the RPC protocol.
But at least it should not prevent phpactor to work ;)

**Comment by dantleech** [comment]
As of now the LanguageServerExtension is installed by default - but yeah, that looks like an undeclared dependency :)

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/indexer/commit/773eafa6ac518eb97968b4cb3480d226d27090b6
