### ISSUE TITLE
Variable completion helper throws NotFound exception

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#992]
Causes language server error:

```

  Message: Exception [Phpactor\WorseReflection\Core\Exception\SourceNotFound] Could not find source with "DMS\PHPUnitExtensions\ArraySubset\ArraySubsetAsserts"
  Code: -32603 
#0 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CoreReflector.php(126): Phpactor\WorseReflection\Core\SourceCodeLocator\ChainSourceLocator->locate(Object(Phpactor\WorseReflection\Core\ClassName))
#1 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CoreReflector.php(102): Phpactor\WorseReflection\Core\Reflector\CoreReflector->reflectClassLike(Object(Phpactor\WorseReflection\Core\ClassName))
#2 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CompositeReflector.php(64): Phpactor\WorseReflection\Core\Reflector\CoreReflector->reflectTrait(Object(Phpactor\WorseReflection\Core\ClassName))
#3 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflection/Collection/ReflectionTraitCollection.php(30): Phpactor\WorseReflection\Core\Reflector\CompositeReflector->reflectTrait(Object(Phpactor\WorseReflection\Core\ClassName))
#4 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflection/ReflectionClass.php(276): Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\Collection\ReflectionTraitCollection::fromClassDeclaration(Object(Phpactor\WorseReflection\Core\ServiceLocator), Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#5 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflection/ReflectionClass.php(205): Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass->traits()
#6 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Virtual/VirtualReflectionClassDecorator.php(87): Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass->methods()
#7 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflection/ReflectionClass.php(226): Phpactor\WorseReflection\Core\Virtual\VirtualReflectionClassDecorator->methods(Object(Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass))
#8 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Virtual/VirtualReflectionClassDecorator.php(87): Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass->methods()
#9 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php(399): Phpactor\WorseReflection\Core\Virtual\VirtualReflectionClassDecorator->methods()
#10 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php(353): Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->resolveParameterFromReflection(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\MethodDeclaration), Object(Microsoft\PhpParser\Node\Parameter))
#11 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php(144): Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->resolveParameter(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Parameter))
#12 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php(115): Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->__resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Parameter))
#13 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php(99): Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->_resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Parameter))
#14 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(107): Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Parameter))
#15 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder/FunctionLikeWalker.php(83): Phpactor\WorseReflection\Core\Inference\FrameBuilder->resolveNode(Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\Parameter))
#16 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder/FunctionLikeWalker.php(36): Phpactor\WorseReflection\Core\Inference\FrameBuilder\FunctionLikeWalker->walkFunctionLike(Object(Phpactor\WorseReflection\Core\Inference\FrameBuilder), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\MethodDeclaration))
#17 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(78): Phpactor\WorseReflection\Core\Inference\FrameBuilder\FunctionLikeWalker->walk(Object(Phpactor\WorseReflection\Core\Inference\FrameBuilder), Object(Phpactor\WorseReflection\Core\Inference\Frame), Object(Microsoft\PhpParser\Node\MethodDeclaration))
#18 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php(61): Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode(Object(Microsoft\PhpParser\Node\MethodDeclaration), Object(Microsoft\PhpParser\Node\Expression\Variable))
#19 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflector/TolerantSourceCodeReflector.php(60): Phpactor\WorseReflection\Core\Inference\FrameBuilder->build(Object(Microsoft\PhpParser\Node\Expression\Variable))
#20 /home/daniel/www/phpactor/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CompositeReflector.php(88): Phpactor\WorseReflection\Bridge\TolerantParser\Reflector\TolerantSourceCodeReflector->reflectOffset(Object(Phpactor\WorseReflection\Core\SourceCode), Object(Phpactor\WorseReflection\Core\Offset))
#21 /home/daniel/www/phpactor/phpactor/vendor/phpactor/completion/lib/Bridge/TolerantParser/WorseReflection/Helper/VariableCompletionHelper.php(37): Phpactor\WorseReflection\Core\Reflector\CompositeReflector->reflectOffset(Object(Phpactor\TextDocument\StandardTextDocument), 2157)
#22 /home/daniel/www/phpactor/phpactor/vendor/phpactor/completion/lib/Bridge/TolerantParser/WorseReflection/WorseLocalVariableCompletor.php(49): Phpactor\Completion\Bridge\TolerantParser\WorseReflection\Helper\VariableCompletionHelper->variableCompletions(Object(Microsoft\PhpParser\Node\Expression\Variable), Object(Phpactor\TextDocument\StandardTextDocument), 2157)
#23 /home/daniel/www/phpactor/phpactor/vendor/phpactor/completion/lib/Bridge/TolerantParser/ChainTolerantCompletor.php(58): Phpactor\Completion\Bridge\TolerantParser\WorseReflection\WorseLocalVariableCompletor->complete(Object(Microsoft\PhpParser\Node\Expression\Variable), Object(Phpactor\TextDocument\StandardTextDocument), Object(Phpactor\TextDocument\ByteOffset))
#24 /home/daniel/www/phpactor/phpactor/vendor/phpactor/completion/lib/Core/ChainCompletor.php(31): Phpactor\Completion\Bridge\TolerantParser\ChainTolerantCompletor->complete(Object(Phpactor\TextDocument\StandardTextDocument), Object(Phpactor\TextDocument\ByteOffset))
```

**Comment by dantleech** [comment]
Fixed with https://github.com/phpactor/completion/blob/1cf7ee4c90080c29fb03185c49c7b91957f9fb9b/lib/Bridge/TolerantParser/WorseReflection/Helper/VariableCompletionHelper.php#L41
